### ISSUE TITLE
AVS not giving response through 3.5mm jack in raspberrypi 3

### ISSUE THREAD

**Issue by jay7583** [alexa/avs-device-sdk#591] opened 2018-03-30 08:59 UTC
Hi,
i have installed updated avs sdk version in raspbian strech.alexa is responding but it's not giving voice output through 3.5mm jack.
I have tried in different ways but it's not doing .any suggestions?

**Comment by jguerreiro** [comment] 2018-03-30 11:38
I experienced same situation, though when I tested the speaker sepately, it
worked just fine.

**Comment by jay7583** [comment] 2018-03-30 13:31
3.5 mm jack is working i checked with audacity and other applications. it's giving output except for avs-sdk

**Comment by jguerreiro** [comment] 2018-03-30 13:35
Agreed, appears the issue is with avs-sdk.

**Comment by priyagsenthil** [comment] 2018-03-31 16:25
Hi,

We have seen this issue on few raspberry pi's. Have you be able to play with USB/HDMI headset.
Can you provide your ~/.asoundrc settings. 

Thanks
Priya

**Comment by kclchan** [comment] 2018-04-02 22:36
Hi @jay7583, please look at the "No audio output from SDK" section in https://github.com/alexa/avs-device-sdk/wiki/Troubleshooting-Guide and see if it helps.  Thanks!

**Comment by jay7583** [comment] 2018-04-03 17:24
Hi,
     I am using usb soundcard for microphone.AVS also giving output(speaking) from that soundcard only.
Even i change my ~.asoundrc file ,still it's accessing usb soundcard only.In which file i have to change audio output settings?
i want to to put usb soundcard for mic and 3.5mm jack for speaker.
here is my .asoundrc file
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}

**Comment by kclchan** [comment] 2018-04-03 20:41
Hi @jay7583, I found this link which might be helpful for you (https://raspberrypi.stackexchange.com/questions/67510/how-to-use-usb-mic-in-and-3-5-mm-audio-jack-out), although I see that the .asoundrc configuration is very similar to what you have already.

Could you also try to change in MediaPlayer.cpp to use "alsasink" instead of "autoaudiosink" as mentioned in https://github.com/alexa/avs-device-sdk/wiki/Troubleshooting-Guide?  Please note that you will need to recompile before running the SampleApp for the changes to take effect.

**Comment by dhpp** [comment] 2018-04-18 15:47
Please also see #577, #517 and #516 where this was solved by other users.  I'll close this for now - please re-open if you require further guidance.

**Closed by dhpp** 2018-04-18 15:47 UTC
