### ISSUE TITLE
AVS doesn't reply anything because of AIP Lost focus.

### ISSUE THREAD

**Issue by NyxRockchip2017** [alexa/avs-device-sdk#134] opened 2017-09-05 01:25 UTC
AVS doesn't reply anything because of AIP Lost focus.
```
2017-09-05 01:24:03.587 [  e] 0 AudioInputProcessor:setState:from=BUSY,to=IDLE
2017-09-05 01:24:03.593 [ 14] 9 AudioPlayer:onFocusChanged:newFocus=FOREGROUND
2017-09-05 01:24:03.612 [  e] 0 AudioInputProcessor:executeOnFocusChanged:newFocus=NONE
2017-09-05 01:24:03.624 [  e] 0 AudioInputProcessor:executeOnFocusChanged:reason=Lost focus
2017-09-05 01:24:03.838 [ 35] 0 HTTP2Stream:receivedRequestId:value=x-amzn-requestid\: 067ecffffea47dd0-0000713b-0001db2f-2d19e55
2017-09-05 01:24:03.849 [ 35] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
2017-09-05 01:24:04.268 [ 35] 0 HTTP2Stream:receivedRequestId:value=x-amzn-requestid\: 067ecffffea47dd0-0000713b-0001db2f-2d19e57
2017-09-05 01:24:04.279 [ 35] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
2017-09-05 01:24:05.617 [ 14] E AudioPlayer:onFocusChangedFailed:reason=timedout,cause=executorTimeout
```

**Comment by scotthea-amazon** [comment] 2017-09-07 00:50
Hello NxyRockchip2017,

The log you provided is interesting, but doesn't tell us enough to help resolve the problem you are encountering.  Can you please provide steps for reproducing the problem and provide complete logs so that we can get  better understanding of why API is losing focus.

Thanks,
-SWH

**Comment by NyxRockchip2017** [comment] 2017-09-12 01:37
You can reproduce the issue by running the following command for many times：
1.playing amazon music in the device.
2.I send the command “alexa，stop” to stop music.
3.And then I play audible book by saying "alexa,play my audible book".
4.After that,the avs won't reply anything.

**Comment by sanjayrd** [comment] 2017-09-15 20:15
@NyxRockchip2017,

I've not been able to reproduce this issue. What version of the SDK are you using? By the way, Audible is not yet supported in our SDK. Have you implemented that part yourself?

**Comment by NyxRockchip2017** [comment] 2017-10-13 07:06
I've been able to reproduce this issue in V1.1 version.The logs of this issue is too large to upload to here,can you provide the address of e-mail for me?

**Comment by sanjayrd** [comment] 2017-12-11 19:58
Hi @NyxRockchip2017,

Are you still experiencing this issue? If so, feel free to email me at sdy@amazon.com. I'm going to go ahead and close this issue since it's been a while, but feel free to reopen if you're still experiencing this issue.

Thanks,
Sanjay

**Closed by sanjayrd** 2017-12-11 19:58 UTC
Labels: AIP
