### ISSUE TITLE
There are no any response when down m3u8 failed

### ISSUE THREAD

**Issue by sundq** [alexa/avs-device-sdk#281] opened 2017-10-30 02:07 UTC
Hi 
I ask alexa "play happy", alexa tell me will play the music soon， but because my network have problem , it can not down the music stream from network， so the alexa always timeout and no any resonpse, here is the log:

```
###########################
#       Speaking...       #
###########################
2017-10-30 01:45:22.559 [  a] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
2017-10-30 01:45:22.560 [  a] 0 HTTP2StreamPool:getStream:streamId=21,numAcquiredStreams=2
2017-10-30 01:45:22.560 [  a] 9 HTTP2Transport:insertActiveStream:handle=0x396ee0
[2017-10-30 01:45:22.564] [tonly_avs_app] [INFO] msg interface is: tonly.led.operated
2017-10-30 01:45:22.927 [  a] 0 HTTP2Transport:cleanupFinishedStream:streamId=21,result=204
2017-10-30 01:45:22.927 [  a] 0 HTTP2StreamPool:releaseStream:streamId=21,numAcquiredStreams=1
2017-10-30 01:45:22.927 [  a] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
2017-10-30 01:45:23.850 [ 16] 9 BaseStreamSource:onNeedDataCalled:size=4096
2017-10-30 01:45:23.850 [  2] 9 BaseStreamSource:handleNeedDataCalled
2017-10-30 01:45:24.239 [  2] 9 MediaPlayer:messageReceived:messageType=eos
2017-10-30 01:45:24.239 [  2] 9 MediaPlayer:tearDownTransientPipelineElements
2017-10-30 01:45:24.284 [  2] 9 BaseStreamSource:~BaseStreamSource
2017-10-30 01:45:24.284 [  2] 0 MediaPlayer:callingOnPlaybackFinished
2017-10-30 01:45:24.284 [  2] 9 SpeechSynthesizer:onPlaybackFinished
2017-10-30 01:45:24.285 [  8] 0 SpeechSynthesizer:executePlaybackFinished
2017-10-30 01:45:24.285 [  8] 0 SpeechSynthesizer:executeProvideState:stateRequestToken=0
2017-10-30 01:45:24.285 [  8] 0 ContextManager:updateStateLocked:action=updatedState,state={"token"\:"amzn1.as-ct.v1.Domain\:Application\:Music#ACRI#DeviceTTSRendererV4_5ec5a471-3710-4b48-91a8-45d397a9bd42"\,"offsetInMilliseconds"\:0\,"playerActivity"\:"FINISHED"},namespace=SpeechSynthesizer,name=SpeechState
2017-10-30 01:45:24.285 [  8] 9 SpeechSynthesizer:releaseForegroundFocus
2017-10-30 01:45:24.285 [  8] 1 FocusManager:releaseChannel:channelName=Dialog
2017-10-30 01:45:24.285 [  c] 0 SpeechSynthesizer:onFocusChanged:newFocus=NONE
2017-10-30 01:45:24.286 [  c] 9 AudioPlayer:onFocusChanged:newFocus=FOREGROUND
2017-10-30 01:45:24.286 [  8] 0 EventBuilder:buildJsonEventString:messageId=e5f36f9c-bbe7-4b33-abeb-be3c35d1e15f,namespace=SpeechSynthesizer,name=SpeechFinished
2017-10-30 01:45:24.286 [  8] 9 SpeechSynthesizer:setHandlingCompleted
2017-10-30 01:45:24.286 [  8] 0 DirectiveProcessor:onHandlingCompeted:messageId=d3201a4a-922f-4944-90fd-1d36c07db74d,directiveBeingPreHandled=(nullptr)
2017-10-30 01:45:24.286 [  8] 0 CapabilityAgent:removingMessageIdFromMap:messageId=d3201a4a-922f-4944-90fd-1d36c07db74d
2017-10-30 01:45:24.287 [ 11] I DirectiveRouter:handleDirective:messageId=e6313789-a018-4b22-a943-c20b0ae2ee42,action=calling
2017-10-30 01:45:24.287 [ 11] 9 AudioPlayer:handlePlayDirective
2017-10-30 01:45:24.287 [ 11] E JsonUtils:findNodeFailed:reason=missingDirectChild,child=streamFormat
2017-10-30 01:45:24.288 [ 11] E JsonUtils:findNodeFailed:reason=missingDirectChild,child=progressReportIntervalInMilliseconds
2017-10-30 01:45:24.288 [ 11] E JsonUtils:findNodeFailed:reason=missingDirectChild,child=expectedPreviousToken
2017-10-30 01:45:24.288 [  2] 9 MediaPlayer:doStopSuccess
2017-10-30 01:45:24.331 [  a] 0 HTTP2StreamPool:getStream:streamId=23,numAcquiredStreams=2
2017-10-30 01:45:24.332 [  a] 9 HTTP2Transport:insertActiveStream:handle=0x3434c0
2017-10-30 01:45:24.490 [  e] 0 DialogUXStateAggregator:setState:from=FINISHED,to=IDLE
########################################
#       Alexa is currently idle!       #
########################################
[2017-10-30 01:45:24.491] [tonly_avs_app] [INFO] msg interface is: tonly.led.operated
2017-10-30 01:45:24.910 [  a] 0 HTTP2Transport:cleanupFinishedStream:streamId=23,result=204
2017-10-30 01:45:24.911 [  a] 0 HTTP2StreamPool:releaseStream:streamId=23,numAcquiredStreams=1
2017-10-30 01:45:24.911 [  a] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
2017-10-30 01:45:26.286 [  c] E AudioPlayer:onFocusChangedFailed:reason=timedout,cause=executorTimeout
2017-10-30 01:50:25.557 [  a] 0 HTTP2Transport:sendPing:pingStream=0
2017-10-30 01:50:25.557 [  a] 0 HTTP2StreamPool:getStream:streamId=25,numAcquiredStreams=2
2017-10-30 01:50:25.941 [  a] 0 HTTP2Transport:handlePingResponse
2017-10-30 01:50:25.942 [  a] 0 HTTP2StreamPool:releaseStream:streamId=25,numAcquiredStreams=1
2017-10-30 01:50:25.942 [  a] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
2017-10-30 01:55:26.602 [  a] 0 HTTP2Transport:sendPing:pingStream=0
2017-10-30 01:55:26.602 [  a] 0 HTTP2StreamPool:getStream:streamId=27,numAcquiredStreams=2
2017-10-30 01:55:26.991 [  a] 0 HTTP2Transport:handlePingResponse
2017-10-30 01:55:26.991 [  a] 0 HTTP2StreamPool:releaseStream:streamId=27,numAcquiredStreams=1
2017-10-30 01:55:26.991 [  a] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
2017-10-30 02:00:27.658 [  a] 0 HTTP2Transport:sendPing:pingStream=0
2017-10-30 02:00:27.659 [  a] 0 HTTP2StreamPool:getStream:streamId=29,numAcquiredStreams=2
2017-10-30 02:00:27.949 [  a] 0 HTTP2Transport:handlePingResponse
2017-10-30 02:00:27.949 [  a] 0 HTTP2StreamPool:releaseStream:streamId=29,numAcquiredStreams=1
2017-10-30 02:00:27.950 [  a] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT



```

**Comment by frozenberg** [comment] 2017-10-30 16:55
Hi @sundq, it's possible that a fix for this issue will be included in our next release. Could you attempt to reproduce the issue and reply with all the logs from the start of the program?

Thanks

**Comment by frozenberg** [comment] 2017-11-28 22:25
Closing due to lack of response.

**Closed by frozenberg** 2017-11-28 22:25 UTC
