### ISSUE TITLE
Cannot control endpoint through Amazon Alexa app

### ISSUE THREAD

**Issue by vikramdattu** [alexa/avs-device-sdk#1683] opened 2020-04-27 08:59 UTC
#908  Briefly summarize your issue:

Not able to control endpoint via Amazon Alexa app.

I have build SampleApp with Power Controller smart home feature enabled.
Extra endpoint device named Discoball is getting listed in Amazon Alexa app.
But I cannot control or do Power ON/OFF using the app. There is no such toggle.

I can say, "TurnOff Discoball" however to get TurnOff directive.

There is one Enable toggle however in app, which does not do the same thing.

## What is the expected behavior?

App should show TurnOff/On option which could send directive to device.

## What behavior are you observing?
Not able to control endpoint via Amazon Alexa app.

## Provide the steps to reproduce the issue, if applicable:
Build sample app with PowerController endpoint API.
(-DENDPOINT_CONTROLLERS_POWER_CONTROLLER=1)

### What version of the AVS Device SDK are you using?
     < 1.19.0>

### Tell us what hardware you're using:

Mac

### Tell us about your OS (Type & version):

- [ ] MacOS 

Please help with the same and let me know if I am missing something.
Or is there something that needs whitelisting etc?

Please find the attachment showing endpoint getting listed as Discoball:
![Screenshot_20200427-141628_Amazon%20Alexa](https://user-images.githubusercontent.com/5511751/80354095-eadacf80-8893-11ea-8e7a-32192017acab.jpg)

**Comment by caleighatamazon** [comment] 2020-04-27 16:59
Hi @vikramdattu, could you please provide more information? I'd like you to attach DEBUG9 logs and also provide the full cmake command you used to build the SDK.

You should not need to whitelist the account. I tried just briefly now and was able to control the Discoball via Alexa app, so I will need your help and some more information to figure out why this is not working for you.

**Comment by caleighatamazon** [comment] 2020-04-27 20:05
Hi again @vikramdattu, I was mistaken earlier - I am indeed able to reproduce this problem. It seems only to happen when the power controller is enabled, and no other controllers are enabled. I'm going to file an internal ticket for this for us to investigate. Thanks!

**Comment by caleighatamazon** [comment] 2020-04-29 01:42
Hi again @vikramdattu, I just wanted to follow up on this since I got a bit more information. This is not an issue with the SDK but rather with the Alexa app GUI. This is a known area for improvement in the Alexa app user interface.

Because the Discoball is an atypical device type, GUI controls for it will only show up if it supports one of the following controllers: Toggle, Mode, Range.

When you build the Discoball with just the Power controller, that option will not show up in the app.

If you want to see the controls in the Alexa app, you will need to enable at least one additional controller (Mode/Range/Toggle). 

We have a ticket filed internally to improve this experience. I'm going to close this issue, since it's unrelated to the SDK, but please feel free to ask more questions.

**Closed by caleighatamazon** 2020-04-29 01:42 UTC
Labels: Under investigation
