### ISSUE TITLE
Authentication return server error

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#848] opened 2018-07-12 15:35 UTC
Hi AVS team,

SDK 1.8.0 ,  ARM based OpenWRT embedded linux.

We got user's report from Australia while DUT reboot but authentication  failed.
User tried it many times in 20 minutes but all the same.
From the log, I saw a 405 error which I never saw it before. Could you help to check it ?

[avs_dbg_log.txt](https://github.com/alexa/avs-device-sdk/files/2189250/avs_dbg_log.txt)

**Comment by kclchan** [comment] 2018-07-13 00:56
Hi @zeusshuang, this sounds like a cloud issue.  Is it still happening, or was it happening only in that 20min timeframe?

**Comment by zeusshuang** [comment] 2018-07-13 02:47
Hi @kclchan ,

User said after overnight power off, and this morning (AUS time) is working well.
Is there any definition about the AVS server error code definitions ?  
Actually, I did not see 405 before, normally it may return 400 if it's registration fail or connection fail.

**Comment by kclchan** [comment] 2018-07-13 20:07
Hi @zeusshuang,

The 405 error is not from authentication but rather from the CapabilitiesDelegate failing to publish the device's capability to AVS:

`2018-07-12 13:06:22.172 [  f] E CapabilitiesDelegate:publishCapabilitiesFailed:reason=httpRequestFailed Code\: 405\, Body\: <html>`

I've checked with the owners of that endpoint and they couldn't find any problem during that period of time (i.e. 2018-07-12 13:06:20.930 @ Australia time).

Would you be able to send us some logs from that device when it's working?  We maybe able to gather more information on that particular device.

Thanks,
Kenneth

**Comment by zeusshuang** [comment] 2018-07-16 00:48
Hi @kclchan 

attached log is from the same device and working case.
by your comment, I saw at line#24, there is a log for CapabilitiesDelegate , it said missing configuration value, is it expected while first boot up ?

[avs_dbg_log-0714.zip](https://github.com/alexa/avs-device-sdk/files/2196290/avs_dbg_log-0714.zip)

**Comment by BennyAvramson** [comment] 2018-07-16 18:45
Hi @zeusshuang,

The error you've seen is not related to the 405 response issue. The later is because on DEBUG build, the SDK expects config node for the Capabilities endpoint.

We're checking again with Capabilities service owners for possible reasons for this.

I understand this was an one time issue and it's not reproducing. If not, please let me know.

Thanks,
Benny

**Comment by zeusshuang** [comment] 2018-07-16 23:03
Hi @BennyAvramson ,

Thanks for the comment, and yes, user saw this issue once and could not see it again until now.

**Comment by celinval** [comment] 2018-07-24 22:38
Thanks for letting us know, @zeusshuang. I'm going to close this issue for now, but feel free to re-open if one of your customers encounters the same problem.

**Closed by celinval** 2018-07-24 22:38 UTC

**Comment by zeusshuang** [comment] 2018-07-25 00:38
Hi @celinval ,

It's because it happened at user's home not in the Lab. We would like to know while it happens, how can we recover it or show something for user ?
In engineering site, we only see 400 error while authentication issue, we do not know where should we check this error response and show something to user (maybe system error LED indicator or play TTS)
