### ISSUE TITLE
ProgressReportIntervalElapsed is getting fail for TuneIn podcast MVT report generation

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1637] opened 2020-03-05 09:37 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
We are trying to generate the ALL PASS MVT report for TuneIn podcast but ProgressReportIntervalElapsed event is getting fail with tags [MISSING] or [DELAYED].

We have collected the DEBUG9 logs to debug the root cause for issue and used https://developer.amazon.com/en-US/docs/alexa/mvt/cert-requirements-mvt.html to analyse the logs.

As it is mentioned in Amazon URL the reason for DELAYED failure tag is -
**DELAYED** - Event sent too late. Typical acceptable latency is 2s (to reach AlexaService) after the actual event happening on the device.

Their are 2 possibilities for getting Delay -
- (Reason-1) - Device is taking too much of time to send the Event to AlexaService
- (Reason-2) - Device has send the event but it may be taking time to reach the AlexaService.

If we consider Delay is because of Reason-1, then the event ProgressReportIntervalElapsed may also get fail on TuneIn radio but we are able to generate ALL PASS report for the same just for TuneIn podcast its getting fail.

We were able to generate ALL PASS report for TuneIn podcast through AQT but now it is getting failed with AQT also.

As we are getting MISSING failure tag also -
**MISSING** -The event was not sent at the expected interval.

for this failure, same above possiblities can be the reason.

As per my analysis below issues can also be the reason for ProgressReportIntervalElapsed event failure -
- Cloud side issue
- Device side issue

Please find the attached DEBUG9 logs-
[MVT_DEBUG9_logs.txt](https://github.com/alexa/avs-device-sdk/files/4292056/MVT_DEBUG9_logs.txt)

We have done the analysis of AVS-SDK code and DEBUG9 log, do check the attached document of the analysis [analysis.txt](https://github.com/alexa/avs-device-sdk/files/4292061/analysis.txt)

## What is the expected behavior?
ProgressReportIntervalElapsed and PlaybackStopped event should get passed and we should able to generate ALL PASS report for MVT testing of TuneIn podcast. 

## What behavior are you observing?
ProgressReportIntervalElapsed and PlaybackStopped event is failing, due to this we are not able to generate ALL PASS report for MVT testing of TuneIn podcast. 

## Provide the steps to reproduce the issue, if applicable:
- Use the checklist provided by MVT to test TuneIn PODCAST.
- Generate report through MVT report generation tool

### What version of the AVS Device SDK are you using?
      <x.y.z>
Used AVS-SDK V-1.17

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mvelegon-amzn** [comment] 2020-03-08 15:41
Hi @dipalisb The failures you are observing could happen because of network latency. We suggest rerunning the test and see if it passes. Also make sure the internet connection you are on is good in order to eliminate network problems.

**Comment by dipalisb** [comment] 2020-03-20 08:21
Hi @mvelegon-amzn ,
We have used proper internet connection with a speed of 92.56 mbps and we followed all the step required for testing as -
1.Stable internet (Data speed - 94 mbps)
2.Quite environment

Even though its getting failed always.

**Comment by dipalisb** [comment] 2020-03-21 14:52
Hi @mvelegon-amzn ,
We have tested many times and every time it was failed

**Comment by scotthea-amazon** [comment] 2020-06-20 01:56
Hello @dipalisb,

I am closing this because it is a duplicate of https://github.com/alexa/avs-device-sdk/issues/1734 and https://github.com/alexa/avs-device-sdk/issues/1697.

Best regards,
-SWH

**Closed by scotthea-amazon** 2020-06-20 01:56 UTC
Labels: Under investigation
