### ISSUE TITLE
avs  aborted exit issue. (Version 1.0.3 alexa-client-sdk)

### ISSUE THREAD

**Issue by xurenjun** [alexa/avs-device-sdk#183] opened 2017-09-22 10:11 UTC
hi all:

Above the program during normal operation. (Version 1.0.3 alexa-client-sdk)

err log:
terminate called after throwing an instance of 'std::future_error'
  what():  Promise already satisfied

What is the reason?

**Comment by mradulan** [comment] 2017-09-25 20:29
Hi @xurenjun , do you get this when you are running the Sample app? Can you tell the specific operation you are doing so that we can reproduce the issue?

**Comment by mradulan** [comment] 2017-09-25 21:24
Hi @xurenjun , this has been observed and it will be resolved in future release. Please refer to #153 and the solution there. Below is the snippet of the temporary solution from #153:

It looks like the crash is occurring because m_playlistParsedPromise in MediaPlayer/URLSource is being set twice. In MediaPlayer/include/UrlSource.h, could you add a boolean flag that indicates whether a callback has been received, as well as a mutex? For example, bool m_hasReceivedAPlaylistCallback and std::mutex m_mutex. Then in URLSource's constructor, initialize m_hasReceivedAPlaylistCallback to false. Finally, in UrlSource::onPlaylistParsed, you could add something like the following:

std::lock_guard<std::mutex> lock{m_mutex};
if (!m_hasReceivedAPlaylistCallback) {
m_hasReceivedAPlaylistCallback = true;
m_playlistParsedPromise.set_value(urls);
}

**Comment by kclchan** [comment] 2017-10-03 16:51
This issue is fixed in v1.1.0.  Thanks.

**Closed by kclchan** 2017-10-03 16:51 UTC

**Comment by xurenjun** [comment] 2019-03-19 08:27
@mradulan Thanks.
