### ISSUE TITLE
Alexa for Android: CANNOT LINK EXECUTABLE "/data/app/avs/bin/SampleApp": cannot locate symbol "EVP_CIPHER_CTX_init" referenced by "/system/lib/libdrmmtkutil.so"...

### ISSUE THREAD

**Issue by TaoGegithub** [alexa/avs-device-sdk#1400] opened 2019-06-25 09:04 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
CANNOT LINK EXECUTABLE "/data/app/avs/bin/SampleApp": cannot locate symbol "EVP_CIPHER_CTX_init" referenced by "/system/lib/libdrmmtkutil.so"...

## What behavior are you observing?
Follow this link: [Android Quick Start Guide,](https://github.com/alexa/avs-device-sdk/wiki/Android-Quick-Start-Guide) I would like to build the alexa for android 

## Provide the steps to reproduce the issue, if applicable:
1.My android device info: 
CPU: MTK(mt8163)
ro.product.cpu.abi=arm64-v8a
ro.product.cpu.abilist=arm64-v8a,armeabi-v7a,armeabi
ro.product.cpu.abilist32=armeabi-v7a,armeabi
ro.product.cpu.abilist64=arm64-v8a

platform: Android 9

2. I set androidConfig.txt like this:
PLATFORM="android"
API_LEVEL="23"
TARGET_SYSTEM="arm"
DEVICE_INSTALL_PATH="/data/app/avs"
BUILD_TYPE="debug"

3. Follow the guide, When i execute this command: sudo bash startsample.sh, it show me the error: 
CANNOT LINK EXECUTABLE "/data/app/avs/bin/SampleApp": cannot locate symbol "EVP_CIPHER_CTX_init" referenced by "/system/lib/libdrmmtkutil.so"...

## Tell us about your environment:
Linux giec 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

### What version of the AVS Device SDK are you using?
      Follow this link, it should be the latest: [Android Quick Start Guide](https://github.com/alexa/avs-device-sdk/wiki/Android-Quick-Start-Guide)

### Tell us what hardware you're using:
- [ yes ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ yes ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment] 2019-06-25 21:10
Hello TaoGegithub,

It looks like SampleApp built, but it may be pulling in the wrong version of openssl when it is executed.

Can you provide a dump of your environment variables?

Also, can you provide the output from attempting to start SampeApp with the environment variable LD_DEBUG=all ?

Best regards,
-SWH

**Comment by scotthea-amazon** [comment] 2019-06-25 21:34
It looks like this is a duplicate of [Issue 1701](https://github.com/alexa/avs-device-sdk/issues/1071)

**Comment by TaoGegithub** [comment] 2019-06-26 02:10
Hello @scotthea-amazon ,

Yes, it just look like this [Issue 1701](https://github.com/alexa/avs-device-sdk/issues/1071), but i can not find any solution in this this page. 

I think you want to know these: 

1. From this link: [android-dependencies](https://github.com/alexa/avs-device-sdk/wiki/Dependencies#android-dependencies), i have installed the dependencies.

2. The dependencies that i built from the source code, the last command was `sudo make install` but not `make install`

3. openssl version: 
OpenSSL 1.1.1  11 Sep 2018

4. What i add to my ~/.bashrc: 
export JAVA_HOME=/home/giec/android/jdk1.8.0_211
export JRE_HOME=$JAVA_HOME/jre
export CLASSPATH=.:$JAVA_HOME/lib:$JRE_HOME/lib:$CLASSPATH
export PATH=$JAVA_HOME/bin:$JRE_HOME/bin:$PATH
export PATH=$PATH:~/android/platform-tools:~/android/tools:~/android/tools/bin

5. From this link: [Android-Quick-Start-Guide](https://github.com/alexa/avs-device-sdk/wiki/Android-Quick-Start-Guide), i can not find the any guide that you said `the output from attempting to start SampeApp with the environment variable LD_DEBUG=all`, what did it mean? And what should i do?

Thanks

**Comment by JSkubic-K4** [comment] 2019-07-18 14:27
@TaoGegithub Were you able to resolve this issue?

**Comment by TaoGegithub** [comment] 2019-07-19 03:41
@JSkubic-K4 
Yes! I solved it myself. Have you encountered this problem?

**Comment by JSkubic-K4** [comment] 2019-07-19 11:40
Yes. Can you share the solution?

**Comment by JSkubic-K4** [comment] 2019-07-21 19:22
@TaoGegithub can you please share your solution.  I have run into the same problem.  Thanks!

**Comment by TaoGegithub** [comment] 2019-07-22 01:39
@JSkubic-K4 
You just need no edit the bash `startsample.sh`, because the default command `LD_LIBRARY_PATH` inside the bash is not right. 

eg.
LD_LIBRARY_PATH=/system/lib: _default path, do not modify_ :$LD_LIBRARY_PATH

**Closed** 2019-08-07 03:09 UTC
