### ISSUE TITLE
Alexa is going to Listening State by triggering "Alexa" wakeword from its own response.

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1598] opened 2020-01-08 06:58 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment] 2020-01-13 18:54
Hi @dipalisb,

Can you provide more information on the issue? Which version of the SDK are you using, and have you been able to reproduce this in the latest version of the SDK? Can you also attach any applicable logs?

**Comment by caleighatamazon** [comment] 2020-03-11 18:54
Closing this as it's a duplicate of https://github.com/alexa/avs-device-sdk/issues/1590.

**Closed by caleighatamazon** 2020-03-11 18:54 UTC
