### ISSUE TITLE
Spoitfy playback issue - Transferring between the device and client breaks audio

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#980] opened 2018-09-26 00:30 UTC
Hi AVS team,

AVS SDK 1.8.1 and SDK 1.9.   ARM based embedded linux.

Issue:
Play Spotify from AVS (DUT), then click "pause" on mobile phone (Spotify APP).
Select device and switch to the mobile phone (Spotify APP) but still under pause state.
Then, switch back to AVS (DUT) by click available device on Spotify APP, click play.
You will see the Spotify APP display the music is playing, but AVS play nothing (no audio).
From the log (debug9), it seems it's playing but no audio.
You need to switch to another AVS first and back to restore the audio, or file a Q&A : Alexa, Hi,  it will resume the Spotify and play.

Steps:
Steps to reproduce:
1. Push playback to the device in a playing state.
2. Press pause.
3. Transfer playback back to the client.
4. Transfer playback (still paused) back the device.
5. Press play.
6. nothing playing on AVS DUT.

The logs are from SDK 1.8.1, but I tried it on SDK1.9, no lucky.

[spotify_debug9.log](https://github.com/alexa/avs-device-sdk/files/2417566/spotify_debug9.log)
[spotify_debug5.log](https://github.com/alexa/avs-device-sdk/files/2417567/spotify_debug5.log)

**Comment by zeusshuang** [comment] 2018-09-26 00:49
I attached SDK1.9 debug5 log, and it's included a Q&A and let it resume case.

For this issue, the key point is the "pause". 
If it just switch playback between AVS and Spotify APP under playing, it's working well.


[spotify_debug5-sdk1.9.log](https://github.com/alexa/avs-device-sdk/files/2417602/spotify_debug5-sdk1.9.log)

**Comment by kjkh** [comment] 2018-09-28 00:29
Hi @zeusshuang,

We are unable to reproduce the issue both on 1.8.1 and 1.9. Is the error always reproducible? Is there any amount of time you need to wait between switching users and resuming playback?

Can you point out specifically which lines the issue occurs in _spotify_debug9.log_
 and _spotify_debug5.log_? It appears playback resumes correctly after the DUT becoming active, but it would be helpful to be able to pinpoint exactly when the issue is occurring.

We've been looking at the 1.9 logs as well and notice that there is no call to acquire focus after the DUT becomes active and playback starts. This isn't observed in the other two logs, but it would explain why no playback occurred in that instance. Will continuing investigating and update with further findings.

**Comment by zeusshuang** [comment] 2018-09-28 01:14
Hi @kjkh ,

It's 100% reproducible.
the key steps is the pause Spotify from "Spotify APP".
Ideally all tests should be control by "Spotify APP", but I also tried to trigger Spotify by voice command first are also fine.
I will get the fail log again and point out the steps in log.

**Comment by kjkh** [comment] 2018-09-28 01:37
Thanks. I tried it with those steps and so far no luck.

Suspiciously, there is also a lack of "AttachmentReaderSource:read:size=4096,status=0" messages in the logs as well after the playback starts again on the DUT.

**Comment by zeusshuang** [comment] 2018-09-28 03:49
Hi @kjkh ,

I attached a new log file based on SDK 1.8.1 with debug 5.
You can see line number : 432, 531, 627, 677, and 852.

432 - before this line, it pause the audio from Spotify APP. (just click pause button)
531 - before this line, it switch to mobile phone from Spotify APP. (my APP is running on a phone)
627 - before this line, it switch back to AVS device.
677 - before this line, I click play on Spotify APP but nothing is playing. From APP, it show it's playing.
852 - you can see, after I interrupt the AVS by a trigger word, it will play music automatically.

Actually, you can see line 647, while it play from Spotify APP, the AVS did not send "PlaybackStarted" event to the server, I think it's the root cause, but I don't know why.

I will run a debug9 log later and post in next reply.

[debug5.log](https://github.com/alexa/avs-device-sdk/files/2426669/debug5.log)

**Comment by zeusshuang** [comment] 2018-09-28 05:58
Hi @kjkh ,

it's very interesting that while I tried to get log under DEBUG9.
Due to it will dump huge log, the audio will become stutter and drop, maybe I did not hear the audio in my previous test.
I found under DEBUG9, it's working !?  Did you try it under DEBUG9 ?
And I did a interesting test, change to DEBUG8 and it faild.
I guess ... there must be something different while it playing under DEBUG9. maybe something was changed in the debug process ?

**Comment by dhpp** [comment] 2018-09-28 15:12
As an additional thought, DEBUG9 results in a lot more trace being output to the logfile, which will add latency throughout the system.  This probably indicates that some part of this workflow completes 'too fast' with respect to some other timing aspect.

Forcing DEBUG9 slows everything down such that the timing is better.  The question now is to identify that element, and update it so that the sequence of operations becomes strictly serial regardless of debug level.

**Comment by kjkh** [comment] 2018-09-28 23:28
I am seeing additional logging that has been added into the code. Where there any additional logic changes made as well?

**Comment by zeusshuang** [comment] 2018-09-28 23:46
Hi @kjkh ,

Could you give me an example? I will check it.

**Comment by zeusshuang** [comment] 2018-09-28 23:54
Hi @kjkh ,

Cannot you still reproduce this case under DEBUG5 there ?

**Comment by kjkh** [comment] 2018-09-29 01:12
No, even with DEBUG5 I could not reproduced.

For example, in the logs:

`[  9] 5 SpotifyESDKAdapter:playbackNotify:event=kSpPlaybackNotifyPause`

This is marked as debug level 5. In the adapter this is debug level 9. 

`[  9] 5 SpotifyESDKAdapter:kSpPlaybackNotifyMetadataChanged:accumulatedPlaybackDuration=12`

I also could not find this anywhere in the code. 

Additionally, there would have been some changes to the volume playback call back signature to integrate with the newest versions of the libraries. These are trivial examples, but indicates code changes were made. Just want to ensure that no changes were made that could cause the behavior you are seeing.

**Comment by zeusshuang** [comment] 2018-09-29 01:56
Hi @kjkh ,

The changes you mentioned  are actually our changes for logging purpose.
It's because we got another trouble while playing Spotify and switch between different AVS device, sometimes, the target AVS device will play nothing, much same like this case but cannot 100% reproducible. (I still did not create case here due to we would like to make sure it's not Spotify APP / Server issue)

Other changes are for default config while initialized the Spotify lib.
I will try to remove our changes and check it again.

**Comment by zeusshuang** [comment] 2018-09-29 01:59
Hi @kjkh ,

Sorry forgot to question that which spotify eSDK version in your code base ?

**Comment by kjkh** [comment] 2018-09-29 02:56
Looking at the latest logs, I'm not seeing a callback to the `playbackAudioData` function. This is what should kick off media playback. This could either be due to the function not being called, exiting out early due to the sample_count check, or it's simply not printed because it's a DEBUG9 log.

Can you move the ACSDK_DEBUG9 logging in that function to the beginning of the function (before the sample_count check). Can you also change that to DEBUG5, and then test again and send me the new logs? I ask to change to DEBUG5 because running the system in DEBUG9 seems to cause the issue to go away for you.

Also, does this happen if you build it in release mode?

**Comment by zeusshuang** [comment] 2018-10-01 08:46
Hi @kjkh ,

I tried to removed our changes and move the DEBUG9 log to the beginning of the "playbackAudioData" function.  Attached is my new log. you can see line 1075, after it, I switch back to AVS DUT and click play, but no audio is playing.

Build to release mode is no help, the issue is persistent. 

[3.log](https://github.com/alexa/avs-device-sdk/files/2433238/3.log)

**Comment by kjkh** [comment] 2018-10-01 22:07
Thanks. Can you repeat but also convert the debug9 to debug5 inside `executeOnFocusChanged` and `executeFocusAcquire`? You can see in the _3.log_ that data is being sent, but m_mediaPlayer->play() is not being successfully called.

**Comment by zeusshuang** [comment] 2018-10-02 06:09
Hi @kjkh ,

I attached the new log. You can check line 1373, and 1494.
The symptom is the same as previous one.
And the same, after a barge-in, it will resume and play again (not in this log)

[1002-fail.log](https://github.com/alexa/avs-device-sdk/files/2436644/1002-fail.log)

**Comment by kjkh** [comment] 2018-10-02 17:19
Okay, we think we've discovered the issue. Can you add one more log to verify? Inside _executeOnFocusChanged_ there's an if statement in the FOREGROUND switch case which checks the haltInitiator and returns if it's equal to EXTERNAL_PAUSE. Can you add a DEBUG5 inside there and send the logs again? It looks like this branch is being entered incorrectly and preventing playback from occurring.

**Comment by kclchan** [comment] 2018-12-11 20:02
Hi @zeusshuang, I believe this issue has been resolved so I am closing it now.  Please feel free to re-open it if it's closed in error.  Thanks!

**Closed by kclchan** 2018-12-11 20:02 UTC
