### ISSUE TITLE
SDK 1.9.0/Ubuntu/Kitt-AI: SampleApp-Aborted (core dumped)

### ISSUE THREAD

**Issue by hinar24** [alexa/avs-device-sdk#1008] opened 2018-10-12 09:11 UTC
## Briefly summarize your issue:
With SDK 1.9.0 the sampleapp aborted while setup is running.It was working correctly without KeyWordDetector. I have attached log created with DEBUG9-Option.

## What is the expected behavior?
SampleApp should start

## What behavior are you observing?
 Error in `./SampleApp/src/SampleApp': munmap_chunk(): invalid pointer: 0x00007ffe6986ed90 ***
 Aborted (core dumped)

## Provide the steps to reproduce the issue, if applicable:
./SampleApp/src/SampleApp /home/heena/ALEXA/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json /home/heena/ALEXA/sdk-folder/sdk-build/ThirdParty/heena_models/ DEBUG9

### What version of the AVS Device SDK are you using?
      AVS SDK - 1.9.0
      gcc (Ubuntu 4.8.5-4ubuntu2) 4.8.5
      curl 7.54.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 librtmp/2.3
      cmake version 3.5.1

### Tell us what hardware you're using:
- [x] Desktop / Laptop

### Tell us about your OS (Type & version):
- [x] Linux

[alexa_1_9_0_logs.txt](https://github.com/alexa/avs-device-sdk/files/2471965/alexa_1_9_0_logs.txt)

**Comment by khassel** [comment] 2018-10-12 19:06
see #644
The problem on ubuntu is Kitt-AI: Version 1.2.0 (which is mentioned in the setup) is working, all versions above are not.

**Comment by celinval** [comment] 2018-10-13 00:37
Hi @hinar24,

Can you please run the sample application using valgrind and send us the logs. It would be extremely helpful since I cannot reproduce it in my environment.

Thanks

**Comment by hinar24** [comment] 2018-10-15 05:16
Hi,
[ALexa_valgrind_log.txt](https://github.com/alexa/avs-device-sdk/files/2477468/ALexa_valgrind_log.txt)

**Comment by hinar24** [comment] 2018-10-15 05:30
Hi @khassel,
I am using Kitt-AI Version 1.2.0. still getting the invalid pointer error.

**Comment by hinar24** [comment] 2018-10-15 07:28
Hi @khassel  @celinval 
Its working with KITT.AI version 1.2.0
Thank you for your help.

**Comment by visayamv** [comment] 2018-10-15 18:03
Hi @hinar24 , there is a known issue with gcc 4.8.5 and Kitt.AI which we have raised to Kitt.AI here:

https://github.com/Kitt-AI/snowboy/issues/459



You can upgrade your GCC to 5.4.0 and edit build/cmake/BuildOptions.cmake file.

Add a CFLAG option "D_GLIBCXX_USE_CXX11_ABI=0 -pg" to the CMAKE variables:
CXX_PLATFORM_DEPENDENT_FLAGS_DEBUG, CXX_PLATFORM_DEPENDENT_FLAGS_RELEASE and CXX_PLATFORM_DEPENDENT_FLAGS_MINSIZEREL

**Comment by hinar24** [comment] 2018-10-16 05:36
Hi @visayamv , thank you for help.I will check it.

**Comment by coderxx** [comment] 2018-10-16 05:47
Please don't post the entire dump inline! Can you remove it and just keep it in the log text file attached?

**Comment by hinar24** [comment] 2018-10-24 05:31
Hi @visayamv 
I  tried your solution but it didn't work.

**Comment by visayamv** [comment] 2018-10-25 02:44
@hinar24 , please provide the output of the following commands (from the build directory)

g++ --version
make VERBOSE=1

**Comment by hinar24** [comment] 2018-10-25 12:01
Hi @visayamv 
it was my mistake g++ was not updated now its working.

**Comment by scotthea-amazon** [comment] 2018-10-26 00:11
Hi @hinar24,

It sounds like this issue is resolved, so I am closing it.  If it has been closed in error, please feel free to re-open it!

Thank you,
-SWH

**Closed by scotthea-amazon** 2018-10-26 00:11 UTC
