### ISSUE TITLE
Jack server is not running and cannot be started

### ISSUE THREAD

**Issue by VijayalakshmiSundaravaradhan** [alexa/avs-device-sdk#780] opened 2018-06-12 11:00 UTC
ALSA lib ../../../alsa-lib-1.1.2/src/pcm/pcm_dsnoop.c:556:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib ../../../alsa-lib-1.1.2/src/pcm/pcm_dsnoop.c:556:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib ../../../alsa-lib-1.1.2/src/pcm/pcm_dsnoop.c:556:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib ../../../alsa-lib-1.1.2/src/pcm/pcm_dsnoop.c:556:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib ../../../alsa-lib-1.1.2/src/pcm/pcm_dsnoop.c:556:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
wm8750: could not get coeff for mclk 11289600 @ rate 48000
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

Is this an error? If so, how to resolve it?

**Comment by scotthea-amazon** [comment] 2018-06-12 23:00
Hi VijayalakshmiSundaravaradhan,

I am unfamiliar with 'jack server', and messages related to it.  Doing a little googling of the message ```
jack server is not running or cannot be started
```
...I am finding suggestions for:
```
- [Restarting Jack Server to get past this message](https://askubuntu.com/questions/557906/problem-starting-jack-server-jack-server-is-not-running-or-cannot-be-started)
- [Suggestions that the messages are harmless](https://github.com/ptrkrysik/gr-gsm/issues/385)

Sorry, but I do not have a definitive answer.

Besides the messages, are things working correctly for you?

Please let us know what you find!
-SWH

**Comment by VijayalakshmiSundaravaradhan** [comment] 2018-06-13 08:54
Yeah things are working fine. When I run the SampleApp on PC, I did not find such error but when I executed it on my system(ARM), I saw this error, between I was not sure whether it is an error or warning. Thank you for responding :)

**Comment by scotthea-amazon** [comment] 2018-06-15 21:19
Hi VijayalakshmiSundaravaradhan,

It sounds like the issue is resolved, so I will close it.  If I have closed it in error, please feel free to re-open it.

Thank you,
-SWH

**Closed by scotthea-amazon** 2018-06-15 21:19 UTC
