### ISSUE TITLE
fr-CA does not work for the first time

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#1722] opened 2020-06-05 08:27 UTC
SDK version: 1.12.0

Now our devices target for US and Canada. For Canada, we support fr-CA. 

Recently we found a problem that when a device is bootup with locale set to "fr-CA", it will still response with English. Then if we change the locale to another language, and then change it back  to "fr-CA", then it can response with French. 

From the device side, I can't explain this. So I'm checking if there is any update on the AVS server side recently, because there is no such issue before.

Thanks

**Comment by kclchan** [comment] 2020-06-08 16:26
Hi @subjectxbj, could you clarify on how your device is set to "fr-CA" at bootup?  Also, could you attach the DEBUG9 log.  Thanks!

**Comment by subjectxbj** [comment] 2020-06-16 04:31
Hi @kclchan ,
The log is attached.
[alexa.log](https://github.com/alexa/avs-device-sdk/files/4784363/alexa.log)

And here is the locale stored in db:
[alexa] / # sqlite3 /etc/alexa/db/settings.db
SQLite version 3.25.3 2018-11-05 20:37:38
Enter ".help" for usage hints.
sqlite> select * from settings;
locale|fr-CA
sqlite>

When I ask "Alexa, what time is it" in English. It is expected to response with French, but actually it response with English.

**Comment by subjectxbj** [comment] 2020-06-18 00:39
Any update?

**Comment by scotthea-amazon** [comment] 2020-06-18 23:17
Hello @subjectxbj,

Looking back at the 1.12 code here:

https://github.com/alexa/avs-device-sdk/blob/v1.12/CapabilityAgents/Settings/src/Settings.cpp#L253

It appears that the settings values in the configuration file are only sent if they do not already exist in the settings database.  So, if settings.db is populated with a locale before SampleApp starts, the value from the configuration file is ignored.

I think we can be pretty sure that is what is happening both from your description of the database contents above, and also because your log does not include any EventBuilder:buildJsonEventString log line with a "SettingsUpdated" event name, which would have been logged by this call:

https://github.com/alexa/avs-device-sdk/blob/v1.12/CapabilityAgents/Settings/src/SettingsUpdatedEventSender.cpp#L92

Best regards,
-SWH

**Comment by subjectxbj** [comment] 2020-06-19 01:50
Hi @scotthea-amazon ,
When I say "change" the locale actually contains following steps:
1. uninstall alexa software and also remove all the db files include "settings.db"
2. install alexa and create the configuration file and set the locale to fr-CA or other value in the configuration file.
3. start alexa, then alexa will parse configuration file and create "settings.db" and persist locale in the db.

In the last comment, I have attached the log, Are you able to find which locale the device report to AVS server from the information of the log? 

When alexa generate that log, both configuration file and "settings.db" indicates the locale is set to "fr-CA", but the response is still English. I'm not able to find what's wrong here.

**Comment by subjectxbj** [comment] 2020-06-19 06:27
We have tried installing alexa with "locale" set to "fr-CA" multiple times. 

After installation, ask the same question "what time is it?". In some installations, it response with French, but in some other installations, it response with English. We have checked the locale stored in db is always "fr-CA".

As you just mentioned, the locale information is only reported to AVS server once during initialization. Is it possible that sometimes it failed to send the locale information to AVS server due to network problem. And then AVS server assume the device works in default locale "en-US" in this case?

**Comment by scotthea-amazon** [comment] 2020-06-19 22:18
Hi @subjectxbj,

I did look at the log yesterday, and I found no "SettingsUpdated" event sent from the client.  So, in the run that generated that log, and assuming the config file specified "fr-CA", I expect that settings.db was present and included a "fr-CA" setting.  Either that, or something else prevented processing the default settings in Settings::initialize(), or your application never called Settings::sendDefaultSettings().

To your question about connectivity based issues, the SettingUpdated event is sent via CertifiedSender.  So, if there were connectivity issues at the time the initial send was attempted, the user may have interacted before CertifiedSender had gotten around to retrying to send the events.

In addition, back in 1.12, CertifiedSender had a bug where it did not read its database of stored outgoing requests from disk at start-up.  So, if there was poor internet connectivity, and the device was restarted before the settings were successfully sent, the outgoing event could have been lost even though the "fr-CA" values was written to settings.db.

Best regards,
-SWH

**Comment by subjectxbj** [comment] 2020-06-24 02:36
Following is the log when alexa response with English while locale is set to fr-CA:
[alexa.log](https://github.com/alexa/avs-device-sdk/files/4822906/alexa.log)

And following log is first install alexa with locale set to en-US, and then uninstall and install alexa with locale set to fr-CA, and alexa response with French. 
[alexa.log](https://github.com/alexa/avs-device-sdk/files/4822914/alexa.log)

You can see both log contains the line 
`2020-06-24 01:45:49.451 [  1] 0 EventBuilder:buildJsonEventString:messageId=5cb56616-652a-4b86-8db3-29650e58a46c,namespace=Settings,name=SettingsUpdated`

**Comment by caleighatamazon** [comment] 2020-06-26 23:10
Hi @subjectxbj, can you upgrade to our latest release, 1.20? I can't reproduce the problem on 1.20. I tried the following steps:

1. Modify AlexaClientSDKConfig.json so its default locale is fr-CA.
2. Delete all the Sample App's databases (a factory reset, so that no settings from a previous session are stored).
3. Run the Sample App.

When I do that, Alexa speaks in French.

Many changes have happened in the SDK regarding settings management since 1.12. I suggest you upgrade your SDK version.

**Comment by subjectxbj** [comment] 2020-07-02 08:06
Hi @caleighatamazon ,

We have no plan to upgrade to SDK 1.20. We will keep using SDK 1.12. Actually our Canadian customers use that for a few months without problem. Only recently we start testing new release and our test team found this problem.

**Comment by subjectxbj** [comment] 2020-07-02 09:48
I noticed there is a new feature "Multilingual Mode" added in 1.15. That means AVS server must have corresponding updates. Is it possible that this change cause AVS server can't support old SDK correctly?

**Comment by alexandrekm-amzn** [comment] 2020-07-14 20:43
hi @subjectxbj 

At this point we are not able to investigate this issue on 1.12.  We strongly recommend upgrading your device to 1.20 at which point we will be in a position to investigate this should this still be an issue.

**Closed by alexandrekm-amzn** 2020-07-14 20:43 UTC
Labels: Awaiting more information
