### ISSUE TITLE
[ERROR] Missing parameters!. 

### ISSUE THREAD

**Issue by aamir6629** [alexa/avs-device-sdk#1719] opened 2020-05-31 14:24 UTC
pi@raspberrypi:~ $ cd $HOME/sdk_folder/sdk-source/avs-device-sdk/tools/Install

pi@raspberrypi:~/sdk_folder/sdk-source/avs-device-sdk/tools/Install $  bash genConfig.sh config.json \
>  123456 \
>  $HOME/sdk_folder/db \
>  $HOME/sdk_folder/sdk-source/avs-device-sdk \
>  $HOME/sdk_folder/sdk-build/Integration/AlexaClientSDKConfig.json
[ERROR] Missing parameters!
Usage: genConfig.sh <config.json file> <device_serial_number> <db path> <SDK Source Directory>
<output AlexaClientSDKConfig.json file> [-D<variable>=<value>]+
1) <config.json file> can be downloaded from developer portal and must contain the following:
   "clientId": "<OAuth client ID>"
   "productId": "<your product name for device>"
2) <device_serial_number> specifies the deviceInfo deviceSerialNumber in the output json file.
3) <db path> specifies the path to where the databases will be located.
4) <SDK Source Directory> specifies the root directory to where the avs-device-sdk source code is located.
5) <output AlexaClientSDKConfig.json file> output file
6) Configure different variables that can be used to fill up extra information in the final configuration. Avaiable variables are:
   "SDK_CONFIG_MANUFACTURER_NAME": The name of the device manufacturer. This variable is required.
   "SDK_CONFIG_DEVICE_DESCRIPTION": The description of the device. This variable is required.

**Comment by aamir6629** [comment] 2020-05-31 14:27
What am I doing wrong here. Please help. 
It's from the project alexa smart screen .

**Comment by kjkh** [comment] 2020-06-03 18:16
Hi @aamir6629,

Your AlexaCientSDKConfig.json looks like it is missing some information. You can generate a populated AlexaCientSDKConfig.json by following the steps here: https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html#set-up-your-configuration-file.

**Comment by scotthea-amazon** [comment] 2020-06-20 00:41
Hi @aamir6629,

There has been no traffic on this issue for a couple of weeks.  It sounds like the issue is probably resolved, so I am closing this issue.  If you are still encountering problems, please create a new issue and refer to this one for context is appropriate.

Best regards,
-SWH

**Closed by scotthea-amazon** 2020-06-20 00:41 UTC
Labels: Awaiting more information
