### ISSUE TITLE
Invalid Configuration Causing SampleApp SegmentFault

### ISSUE THREAD

**Issue by changyp6** [alexa/avs-device-sdk#382] opened 2017-12-11 04:21 UTC
SDK 1.3.0
    "alertsCapabilityAgent":{
         **"databaseFilePath":"/usr/share/avs/alexa.db",**
    }, 
If this single line json is ended with comma ',', SampleApp just crashes after reporting "Failed to parse configuration".

SampleApp should just report "Failed to parse configuration" without segment fault.

**Comment by scotthea-amazon** [comment] 2017-12-11 09:58
Hello changyp6,

Thank you for bringing this to our attention!  We will look in to it.

-SWH

**Comment by kclchan** [comment] 2018-01-04 19:33
We have found the root cause and will include a fix for this in our next software release.  Thanks for reporting it!

**Closed by kclchan** 2018-01-04 19:33 UTC
Labels: bug, Configuration
