### ISSUE TITLE
Thinking no response

### ISSUE THREAD

**Issue by jikaihu** [alexa/avs-device-sdk#151] opened 2017-09-12 08:48 UTC
Sometimes sdk printed ‘HTTP2Transport:streamProgressTimedOut:streamId=19’ and no thinking response. SDK didn't upload the voice data to avs. 

What's wrong with the SDK?

Please help.

Here are the logs from one such instance :

====================================
sh-3.2# BTMIC: D: [btmic_RCHidrawDataType:336]poll timeout and RC_NONE.
[HI][BT_KEYCODE] keycode  is 0xd9
The keycode of hisense remoter input to dfb is 0x9f014
BTMIC: D: [btmic_RCHidrawDataType:372]RC_KEY_MIC_DOWN.
##hisense## DFB:key_symbol=0x9f014,type=0x1,flags=0x20,key_code=0xd9
[GOV][E][guiobserver.cpp:910] keyeventproc : event type = 1, flags = f9, device_id = 12, key_symbol = 9f014, key_id = f600( 0 : 0 ).
BTMIC: D: [btmic_RCHidrawDataType:413]RC_VOICE_START.
[avs][INF]<src/PortAudioMicrophoneWrapper.cpp, 350>: RC_VOICE_START
[avs][TRC]<src/PortAudioMicrophoneWrapper.cpp, 269>: LogFile(0) name: 20170812-083808
[avs][TRC]<src/PortAudioMicrophoneWrapper.cpp, 269>: LogFile(1) name: 20170812-082712
[avs][TRC]<src/PortAudioMicrophoneWrapper.cpp, 269>: LogFile(2) name: 20170812-083704
[avs][TRC]<src/PortAudioMicrophoneWrapper.cpp, 269>: LogFile(3) name: 20170812-083754
[avs][TRC]<src/PortAudioMicrophoneWrapper.cpp, 269>: LogFile(4) name: 20170812-083758
[avs][TRC]<src/PortAudioMicrophoneWrapper.cpp, 269>: LogFile(5) name: 20170812-083801
[avs][INF]<src/PortAudioMicrophoneWrapper.cpp, 276>: Filenum is 6, MinFileNameNum is 1
[avs][INF]<src/PortAudioMicrophoneWrapper.cpp, 282>: Delete the file /3rd_rw/avs/audioLogFile/20170812-082712
[avs][INF]<src/PortAudioMicrophoneWrapper.cpp, 219>: voiceFile name is /3rd_rw/avs/audioLogFile/20170812-083821
[GUI][E][:40] UI.js:2:17148: ___________2950 receive key: 473 VOICE: DOWN, currSubModule: searchDialog, currFocus: BtnSearch
[GUI][E][:40] base.js:1:13363: ___________714 key onkey_VOICE
[GUI][E][:40] AVSClient.js:6:11725: ___________775 model.avs.setControlType status = 1
[ASR][INFO][func_avs.cpp:405] type = 1
[ASR][INFO][avs_adapter.cpp:567] client Send: sockid_send = 102  msgid = 1, datalen= 8
[ASR][INFO][avs_adapter.cpp:575] ipc_socket_write ok 
[avs][INF]<src/RPCServerInterface.cpp, 54>: receive msg from client.[id:1, len:8]
2017-09-12 08:38:21.184 [ 7f] 0 AudioInputProcessor:setState:from=IDLE,to=RECOGNIZING
2017-09-12 08:38:21.184 [ 80] 0 DialogUXStateAggregator:setState:from=IDLE,to=LISTENING
[avs][ERR]<src/RPCClientInterface.cpp, 30>: notify client status :status:1
[avs][INF]<src/ConsolePrinter.cpp, 37>: ############################
[avs][INF]<src/ConsolePrinter.cpp, 38>: Listening...
[avs][INF]<src/ConsolePrinter.cpp, 39>: ############################
[ASR][INFO][avs_adapter.cpp:887] avs_client_handle_msg: socket_id = 102, msgid = 100, datalen= 12 
[ASR][INFO][avs_adapter.cpp:893] the MSG_CLI_ID_NOTIFY_STATUS  is 1 
[avs][INF]<src/PortAudioMicrophoneWrapper.cpp, 446>: startStreamingMicrophoneData
[ASR][INFO][func_avs.cpp:75] avs_i32_recogintion_state_pfset =  1.
[ASR][INFO][avs_adapter.cpp:969] client recv START: socket_id = 102, msg = 16392 
2017-09-12 08:38:21.185 [ 81] 0 ContextManager:buildContextSuccessful:context={"context"\:[{"header"\:{"namespace"\:"SpeechSynthesizer"\,"name"\:"SpeechState"}\,"payload"\:{"token"\:"amzn1.as-ct.v1.Domain\:Application\:Knowledge#ACRI#KnowledgePrompt.9be7901c-b49d-471e-b0c6-c4a4bec6bca6"\,"offsetInMilliseconds"\:0\,"playerActivity"\:"FINISHED"}}\,{"header"\:{"namespace"\:"Alerts"\,"name"\:"AlertsState"}\,"payload"\:{"allAlerts"\:[]\,"activeAlerts"\:[]}}\,{"header"\:{"namespace"\:"SpeechRecognizer"\,"name"\:"RecognizerState"}\,"payload"\:{"wakeword"\:""}}]}
2017-09-12 08:38:21.185 [ 82] 0 AudioInputProcessor:executeOnContextAvailable:jsonContext={"context"\:[{"header"\:{"namespace"\:"SpeechSynthesizer"\,"name"\:"SpeechState"}\,"payload"\:{"token"\:"amzn1.as-ct.v1.Domain\:Application\:Knowledge#ACRI#KnowledgePrompt.9be7901c-b49d-471e-b0c6-c4a4bec6bca6"\,"offsetInMilliseconds"\:0\,"playerActivity"\:"FINISHED"}}\,{"header"\:{"namespace"\:"Alerts"\,"name"\:"AlertsState"}\,"payload"\:{"allAlerts"\:[]\,"activeAlerts"\:[]}}\,{"header"\:{"namespace"\:"SpeechRecognizer"\,"name"\:"RecognizerState"}\,"payload"\:{"wakeword"\:""}}]}
2017-09-12 08:38:21.186 [ 83] I DirectiveProcessor:setDialogRequestId:dialogRequestId=b61abc44-e294-41be-8082-1e62f4013259
2017-09-12 08:38:21.186 [ 84] 0 EventBuilder:buildJsonEventString:messageId=2c70ced7-a5be-47f1-b0bf-e36d1fdfd496,namespace=SpeechRecognizer,name=Recognize
2017-09-12 08:38:21.187 [ 85] 0 AudioInputProcessor:executeOnFocusChanged:newFocus=FOREGROUND
[GUI][E][:40] voiceService.js:1:3040: ___________39 push voiceService
[GUI][E][:40] UI.js:2:27144: ___________3414 setOsdShowType:1
[SYS][I][func_timer-functions.cpp:1407] [TV_TIME]:get utc time = 1505205500.
[SYS][I][func_basic-settings.cpp:329] a_mtktvapi_config_get_value() ret = 0 , ctry = USA 
[SYS][I][func_timer-functions.cpp:2128] [TV_TIME]:c_dt_get_tz: tz = 0.
[SYS][I][func_timer-functions.cpp:2135] [TV_TIME]:a_mtkrpcapi_menu_get_time_zone: res = 0,tz = 0
[GUI][I][:46] PubFunc.js:4:21502: ___________4468 am_tv_mac_address :08:d0:b7:e6:51:bf
[GUI][I][:46] PubFunc.js:4:21541: ___________4469 length: 17
[GUI][I][:46] PubFunc.js:4:21614: ___________4478 deviceID :861003009000007000000712
[LRT][I][RunLogAgentImpl.cpp:1138] m_ShM_ImproveValue->improveValue = 1.
[LRT][D][RunLogAgentImpl.cpp:1146] writeTvRunLog : logType = 120, logInfo = 1.2|120|861003009000007000000712|1505205500|VOICE|USA|0|EN2A27|MT5658|shp|HU43N3070UW
[GUI][E][:40] UI.js:2:17396: ___________2966 send    key: VOICE: DOWN: true
[GOV][E][guiobserver.cpp:223] Do not repeat
[GUI][E][:40] voiceService.js:1:552: ___________90 voiceService status is 1
[LRT][I][RunLogService.cpp:498] curr_LogId.m_logId = 1.2|120.
[LRT][I][RunLogService.cpp:501] curr_logType = 2.
[LRT][D][ReportMessage.cpp:66] m_szContent = 1.2|120|861003009000007000000712|1505205500|VOICE|USA|0|EN2A27|MT5658|shp|HU43N3070UW.
[LRT][I][RunLogService.cpp:517] Successed to call MessageQueue::putMsg().
[LRT][I][RunLogService.cpp:582] nonrt_count = 1.
[LRT][D][RunLogService.cpp:640] Directly Write local file ---> Original Data : 1.2|120|861003009000007000000712|1505205500|VOICE|USA|0|EN2A27|MT5658|shp|HU43N3070UW.
[LRT][I][MessageQueue.cpp:292] Real MessageQueue is empty,so consumer is ready to access used message queue. 
[LRT][I][MessageQueue.cpp:274] MessageQueue is empty,so consumer thread is need to wait message 
[HAS][D][hiAvsData_process.c:279] HI_GET_DEV_SERIAL
[HI_GET_DEV_SERIAL: 662]:
please firstly to call HI_GLOBAL_INIT()!
[HAS][E][hiAvsData_process.c:284] HI_GET_DEV_SERIAL is failed, ret is -1
[HAS][D][hiAvsData_process.c:287] HI_GET_DEV_SERIAL, ret is -1
[HAS][D][hiAvsData_process.c:355] Waiting for device serial...
[HI][BT_KEYCODE] keycode  is 0xd9
BTMIC: D: [btmic_RCHidrawDataType:380]RC_KEY_MIC_UP.
The keycode of hisense remoter input to dfb is 0x9f014
##hisense## DFB:key_symbol=0x9f014,type=0x2,flags=0x20,key_code=0xd9
[GOV][E][guiobserver.cpp:910] keyeventproc : event type = 2, flags = f9, device_id = 12, key_symbol = 9f014, key_id = f600( 0 : 0 ).
BTMIC: D: [btmic_RCHidrawDataType:418]RC_VOICE_STOP.
[avs][INF]<src/PortAudioMicrophoneWrapper.cpp, 373>: RC_VOICE_STOP
[avs][INF]<src/PortAudioMicrophoneWrapper.cpp, 310>: save voice file finish
[GUI][E][:40] UI.js:2:17148: ___________2950 receive key: 473 VOICE: UP, currSubModule: searchDialog, currFocus: BtnSearch
[GUI][E][:40] base.js:1:2100: ___________727 releaseVoiceKeyHandle:UI.currKeyValue = VOICE
[GUI][E][:40] AVSClient.js:6:11725: ___________775 model.avs.setControlType status = 2
[ASR][INFO][func_avs.cpp:405] type = 2
[ASR][INFO][avs_adapter.cpp:590] client Send: sockid_send = 102  msgid = 2, datalen= 8 
[ASR][INFO][avs_adapter.cpp:598] ipc_socket_write ok 
[avs][INF]<src/RPCServerInterface.cpp, 54>: receive msg from client.[id:2, len:8]
[avs][INF]<src/PortAudioMicrophoneWrapper.cpp, 456>: stopStreamingMicrophoneData
2017-09-12 08:38:24.981 [ 86] 0 AudioInputProcessor:stopCapture:stopImmediately=false
2017-09-12 08:38:24.981 [ 87] 0 AudioInputProcessor:setState:from=RECOGNIZING,to=BUSY
2017-09-12 08:38:24.982 [ 88] 0 DialogUXStateAggregator:setState:from=LISTENING,to=THINKING
[avs][ERR]<src/RPCClientInterface.cpp, 30>: notify client status :status:2
[avs][INF]<src/ConsolePrinter.cpp, 37>: ###########################
[avs][INF]<src/ConsolePrinter.cpp, 38>: Thinking...
[avs][INF]<src/ConsolePrinter.cpp, 39>: ###########################
[ASR][INFO][avs_adapter.cpp:887] avs_client_handle_msg: socket_id = 102, msgid = 100, datalen= 12 
[ASR][INFO][avs_adapter.cpp:893] the MSG_CLI_ID_NOTIFY_STATUS  is 2 
[ASR][INFO][func_avs.cpp:75] avs_i32_recogintion_state_pfset =  2.
[ASR][INFO][avs_adapter.cpp:969] client recv START: socket_id = 102, msg = 16392 
[GUI][E][:40] UI.js:2:17396: ___________2966 send    key: VOICE: UP: true
[GUI][E][:40] voiceService.js:1:552: ___________90 voiceService status is 2
[GUI][E][:40] Alexa: ___________154  progressBar.y is 73
[GUI][E][:40] Alexa: ___________154  progressBar.y is 365
[GUI][E][:40] Alexa: ___________154  progressBar.y is 364.99343014783585
2017-09-12 08:38:28.139 [ 89] I HTTP2Transport:streamProgressTimedOut:streamId=19
[HAS][D][hiAvsData_process.c:279] HI_GET_DEV_SERIAL
[HI_GET_DEV_SERIAL: 662]:
please firstly to call HI_GLOBAL_INIT()!
[HAS][E][hiAvsData_process.c:284] HI_GET_DEV_SERIAL is failed, ret is -1
[HAS][D][hiAvsData_process.c:287] HI_GET_DEV_SERIAL, ret is -1
[HAS][D][hiAvsData_process.c:355] Waiting for device serial...
[GUI][E][:40] Alexa: ___________154  progressBar.y is 364.9941601166586
BTMIC: D: [btmic_RCHidrawDataType:336]poll timeout and RC_NONE.
[GUI][E][:40] Alexa: ___________154  progressBar.y is 364.997810016338
[GUI][E][:40] Alexa: ___________154  progressBar.y is 364.98686059159365
[GUI][E][:40] Alexa: ___________154  progressBar.y is 364.9956200657979
[GUI][E][:40] Alexa: ___________154  progressBar.y is 364.9970800289933
[HAS][D][hiAvsData_process.c:279] HI_GET_DEV_SERIAL
[HI_GET_DEV_SERIAL: 662]:
please firstly to call HI_GLOBAL_INIT()!
[HAS][E][hiAvsData_process.c:284] HI_GET_DEV_SERIAL is failed, ret is -1
[HAS][D][hiAvsData_process.c:287] HI_GET_DEV_SERIAL, ret is -1
[HAS][D][hiAvsData_process.c:355] Waiting for device serial...
[GUI][E][:40] Alexa: ___________154  progressBar.y is 364.9919702208685
BTMIC: D: [btmic_RCHidrawDataType:336]poll timeout and RC_NONE.
[GUI][E][:40] Alexa: ___________154  progressBar.y is 364.99562006552594
[GUI][E][:40] Alexa: ___________154  progressBar.y is 364.9956200657979
[GUI][E][:40] Alexa: ___________154  progressBar.y is 365
[GUI][E][:40] Alexa: ___________154  progressBar.y is 364.98029133072953
[HAS][D][hiAvsData_process.c:279] HI_GET_DEV_SERIAL
[HI_GET_DEV_SERIAL: 662]:
please firstly to call HI_GLOBAL_INIT()!
[HAS][E][hiAvsData_process.c:284] HI_GET_DEV_SERIAL is failed, ret is -1
[HAS][D][hiAvsData_process.c:287] HI_GET_DEV_SERIAL, ret is -1
[HAS][D][hiAvsData_process.c:355] Waiting for device serial...
[GUI][E][:40] Alexa: ___________154  progressBar.y is 364.997810016338
BTMIC: D: [btmic_RCHidrawDataType:336]poll timeout and RC_NONE.
2017-09-12 08:38:39.983 [ 8a] 0 DialogUXStateAggregator:transitionFromThinkingTimedOut
2017-09-12 08:38:39.983 [ 8b] 0 DialogUXStateAggregator:setState:from=THINKING,to=IDLE
[avs][ERR]<src/RPCClientInterface.cpp, 30>: notify client status :status:0
[avs][INF]<src/ConsolePrinter.cpp, 37>: ########################################
[avs][INF]<src/ConsolePrinter.cpp, 38>: Alexa is currently idle!
[avs][INF]<src/ConsolePrinter.cpp, 39>: ########################################
2017-09-12 08:38:39.983 [ 8c] 0 AudioInputProcessor:setState:from=BUSY,to=IDLE
[ASR][INFO][avs_adapter.cpp:421] hiavs_client_handle_msg: socket_id = 103, msgid = 100, datalen= 12 
[ASR][INFO][avs_adapter.cpp:477] AVS client get default msg, not handle
[ASR][INFO][avs_adapter.cpp:495] hiavs client recv START: socket_id = 103, msg = 16384 
2017-09-12 08:38:39.984 [ 8d] 0 AudioInputProcessor:executeOnFocusChanged:newFocus=NONE
2017-09-12 08:38:39.984 [ 8e] 0 AudioInputProcessor:executeOnFocusChanged:reason=Lost focus
[GUI][E][:40] Alexa: ___________154  progressBar.y is 365
[GUI][E][:40] Alexa: ___________154  progressBar.y is 364.97080291983684
[GUI][E][:40] Alexa: ___________154  progressBar.y is 364.9941601166586
<ACFG>Regular timer reached... run regular update! 
==>[acfg_common.c 3054]m_regular_delay = 60000
==>startTime = 0, current = 0, endTime = 0
==>b_time_interval_lock = 0
[GUI][E][:40] Alexa: ___________154  progressBar.y is 364.9897803579284
[HAS][D][hiAvsData_process.c:279] HI_GET_DEV_SERIAL
[HI_GET_DEV_SERIAL: 662]:
please firstly to call HI_GLOBAL_INIT()!
[HAS][E][hiAvsData_process.c:284] HI_GET_DEV_SERIAL is failed, ret is -1
[HAS][D][hiAvsData_process.c:287] HI_GET_DEV_SERIAL, ret is -1
[HAS][D][hiAvsData_process.c:355] Waiting for device serial...
[GUI][E][:40] Alexa: ___________154  progressBar.y is 365

**Comment by sanjayrd** [comment] 2017-09-13 22:37
Hi @jikaihu,

A few questions:
1. What version of the SDK are you using?
2. What platform are you running on?
3. Is this happening on normal scenarios or in scenarios with a flaky internet connection? 
4. Is this happening every time you interact with Alexa or only occasionally?

Thanks,
Sanjay

**Comment by kjkh** [comment] 2017-09-21 00:19
Hi @jikaihu,

Do you have any updates on the issue?

**Comment by jikaihu** [comment] 2017-09-21 08:55
Hi @kjkh,
    1.What version of the SDK are you using?
          The SDK version is 0.6.0.

     2.What platform are you running on?
         I ran SDK on our tv system， embedded linux with MTK SOC.

     3.Is this happening on normal scenarios or in scenarios with a flaky internet connection?
         I think it happened with an unstable connection. It's easily happened when AVS returned SERVER_SIDE_DISCONNCT. SDK try to connect to AVS but failed. And repeated again and again.

     4.Is this happening every time you interact with Alexa or only occasionally?
         It's happing only occasionally. And i don't know how it happened. i saw this error log:"streamProgressTimedOut".

     Thanks.

**Comment by dhpp** [comment] 2017-10-10 21:59
Hi jikaihu,

Similar to my response to [#180](https://github.com/alexa/avs-device-sdk/issues/180), I would recommend updating at least the ACL library if possible.  What you are describing does line up with the issues we found since 0.6, and fixed, such as streams being cleaned up correctly, and more robust handling of reconnections caused by both AVS-side disconnects, and local network drops (eg. wifi).

Similar to the other ticket, I will close this one for now, but again feel free to re-open if you feel it is appropriate to continue the discussion here.

-David

**Closed by dhpp** 2017-10-10 21:59 UTC
