### ISSUE TITLE
UpdateStatesLoop failed after wake up 

### ISSUE THREAD

**Issue by jacky-ge** [alexa/avs-device-sdk#233] opened 2017-10-12 07:18 UTC
I have met updateStatesLoopFailed error, the reson is stateProviderTimedOut.  Listening state quickly to Idle state, and can't normal conversation.
 

########################################
#       Alexa is currently idle!       #
########################################
disable timeout checking...
2017-10-10 02:35:40.948 [  9] 9 AudioPlayer:playNextItem:item.stream.offset=0
2017-10-10 02:35:40.952 [  9] 9 MediaPlayer:playCalled
2017-10-10 02:35:40.958 [  2] 0 MediaPlayer:handlePlayCalled
2017-10-10 02:35:40.963 [  2] 0 MediaPlayer:doStopSuccess:reason=alreadyStopped
2017-10-10 02:35:40.970 [  2] 9 MediaPlayer:doStopSuccess
2017-10-10 02:35:40.975 [  2] 0 MediaPlayer:handlePlay:attemptBuffering=0
2017-10-10 02:35:41.014 [ 14] 9 BaseStreamSource:onNeedDataCalled:size=4096
2017-10-10 02:35:41.019 [  2] 0 MediaPlayer:handlePlay:startingState=PLAYING,stateReturn=ASYNC
2017-10-10 02:35:41.031 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.036 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.061 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.077 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.084 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.089 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.107 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.113 [  2] 9 MediaPlayer:State Change:oldState=NULL,newState=READY,pendingState=PLAYING
2017-10-10 02:35:41.128 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.135 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.143 [  2] 9 MediaPlayer:messageReceived:messageType=stream-status
2017-10-10 02:35:41.161 [  2] 9 MediaPlayer:messageReceived:messageType=stream-status
2017-10-10 02:35:41.170 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.189 [  2] 9 BaseStreamSource:handleNeedDataCalled
2017-10-10 02:35:41.197 [  2] 9 BaseStreamSource:installOnReadDataHandler:action=newSourceId,sourceId=35
2017-10-10 02:35:41.217 [  2] 9 AttachmentReaderSource:read:size=4096,status=0
2017-10-10 02:35:41.228 [ 14] 9 BaseStreamSource:onNeedDataCalled:size=4096
2017-10-10 02:35:41.233 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.240 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.261 [  2] 9 AttachmentReaderSource:read:size=2861,status=0
2017-10-10 02:35:41.266 [ 14] 9 BaseStreamSource:onNeedDataCalled:size=4096
2017-10-10 02:35:41.272 [ 14] 9 BaseStreamSource:m_needDataCallbackId already set
2017-10-10 02:35:41.278 [  2] 9 BaseStreamSource:handleNeedDataCalled
2017-10-10 02:35:41.287 [  2] I InProcessAttachmentReader:readFailed:reason=SDS is closed
2017-10-10 02:35:41.295 [  2] 9 AttachmentReaderSource:read:size=0,status=3
2017-10-10 02:35:41.301 [  2] 9 BaseStreamSource:signalEndOfDataCalled
2017-10-10 02:35:41.308 [ 14] 9 BaseStreamSource:onNeedDataCalled:size=4096
2017-10-10 02:35:41.321 [  2] 9 BaseStreamSource:clearOnReadDataHandlerCalled:sourceId=35
2017-10-10 02:35:41.328 [  2] 9 BaseStreamSource:handleNeedDataCalled
2017-10-10 02:35:41.346 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.351 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.352 [ 14] 9 MediaPlayer:onPadAddedCalled
2017-10-10 02:35:41.359 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.372 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.380 [  2] 9 MediaPlayer:handlePadAddedSignalCalled
2017-10-10 02:35:41.467 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.474 [  2] 9 MediaPlayer:messageReceived:messageType=stream-start
2017-10-10 02:35:41.552 [  2] 9 MediaPlayer:messageReceived:messageType=latency
2017-10-10 02:35:41.558 [  2] 9 MediaPlayer:messageReceived:messageType=tag
2017-10-10 02:35:41.564 [  2] 9 MediaPlayer:messageReceived:messageType=tag
2017-10-10 02:35:41.571 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.578 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.585 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.593 [  2] 9 MediaPlayer:State Change:oldState=READY,newState=PAUSED,pendingState=PLAYING
2017-10-10 02:35:41.602 [  2] 9 MediaPlayer:messageReceived:messageType=async-done
2017-10-10 02:35:41.610 [  2] 9 MediaPlayer:messageReceived:messageType=new-clock
2017-10-10 02:35:41.617 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.624 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.632 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.639 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.655 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.660 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.667 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.675 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.683 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.690 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:35:41.697 [  2] 9 MediaPlayer:State Change:oldState=PAUSED,newState=PLAYING,pendingState=VOID_PENDING
2017-10-10 02:35:41.708 [  2] 0 MediaPlayer:callingOnPlaybackStarted
2017-10-10 02:35:41.714 [  2] 9 AudioPlayer:onPlaybackStarted
2017-10-10 02:35:41.719 [  9] 9 AudioPlayer:executePlay:playBehavior=ENQUEUE
UIManager::onPlaybackStarted
2017-10-10 02:35:41.726 [  9] 0 DirectiveProcessor:onHandlingCompeted:messageId=07851696-47d6-4900-bcba-1c6100c2c785,directiveBeingPreHandled=(nullptr)
2017-10-10 02:35:41.728 [  2] 9 MediaPlayer:messageReceived:messageType=tag
2017-10-10 02:35:41.748 [  9] 0 CapabilityAgent:removingMessageIdFromMap:messageId=07851696-47d6-4900-bcba-1c6100c2c785
2017-10-10 02:35:41.759 [  9] 0 AudioPlayer:changeActivity:from=IDLE,to=PLAYING
2017-10-10 02:35:41.766 [  9] 0 AudioPlayer:executeProvideState:sendToken=false,stateRequestToken=0
2017-10-10 02:35:41.775 [  9] 9 MediaPlayer:getOffsetCalled
2017-10-10 02:35:41.780 [  2] 0 MediaPlayer:handleGetOffsetCalled
2017-10-10 02:35:41.786 [  9] 0 ContextManager:updateStateLocked:action=updatedState,state={"token"\:"amzn1.as-ct.v1.Domain\:Application\:DailyBriefing\:TTS#ACRI#ssml#ACRI#DailyBriefingPrompt.7b384bd7-9c31-4167-b908-2bd67b546dd1\:ChannelIntroduction\:0"\,"offsetInMilliseconds"\:215\,"playerActivity"\:"PLAYING"},namespace=AudioPlayer,name=PlaybackState
2017-10-10 02:35:41.817 [  9] 9 MediaPlayer:getOffsetCalled
2017-10-10 02:35:41.822 [  2] 0 MediaPlayer:handleGetOffsetCalled
2017-10-10 02:35:41.829 [  9] 0 EventBuilder:buildJsonEventString:messageId=0c08f721-812d-4f7c-8e17-c47e794f3e6c,namespace=AudioPlayer,name=PlaybackStarted
2017-10-10 02:35:41.841 [  9] 9 MediaPlayer:getOffsetCalled
2017-10-10 02:35:41.848 [  2] 0 MediaPlayer:handleGetOffsetCalled
2017-10-10 02:35:41.853 [  9] 0 EventBuilder:buildJsonEventString:messageId=4a1d6b17-b8c1-41fe-876a-8b5909d295c6,namespace=AudioPlayer,name=PlaybackNearlyFinished
2017-10-10 02:35:42.047 [  b] 0 HTTP2Stream:receivedRequestId:value=x-amzn-requestid\: 06d802fffe77d8c8-00004301-00003d4c-c099a9d7cdce092f-e236ba9a-29
2017-10-10 02:35:42.060 [  b] 0 HTTP2Transport:cleanupFinishedStream:streamId=29,result=204
2017-10-10 02:35:42.067 [  b] 0 HTTP2StreamPool:releaseStream:streamId=29,numAcquiredStreams=1
2017-10-10 02:35:42.075 [  b] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
2017-10-10 02:35:42.084 [  b] 0 HTTP2StreamPool:getStream:streamId=31,numAcquiredStreams=2
2017-10-10 02:35:42.092 [  b] 9 HTTP2Transport:insertActiveStream:handle=0xb466f010
Event: time 1507602942.477099, input: type=1,code=cf,key down
Event: time 1507602942.477099, -------------- SYN_REPORT ------------
Event: time 1507602942.607105, input: type=1,code=cf,key up
Event: time 1507602942.607105, -------------- SYN_REPORT ------------
signal(short time press) is send to comsumer!
event_process pthread_cond_wait end. alexa_current_mode:0; alexa_current_ext_mode:3.
AlexaKeyHandler::keyEventLoop event_process end. event_typ:0.
AlexaKeyHandler::keyEventLoop event_process before.
event_process pthread_cond_wait before.
2017-10-10 02:35:42.677 [  a] 0 AudioInputProcessor:setState:from=IDLE,to=RECOGNIZING
2017-10-10 02:35:42.693 [  e] 0 DialogUXStateAggregator:setState:from=IDLE,to=LISTENING
################[ 1180.188248] multi_ctrl_breath_work_fn, new############
#       Listening...       #
############################
enable timeout checking...
 breath work is queued
2017-10-10 02:35:42.699 [  9] 0 AudioPlayer:executeProvideState:sendToken=true,stateRequestToken=5
2017-10-10 02:35:42.705 [  2] 9 MediaPlayer:messageReceived:messageType=eos
2017-10-10 02:35:42.734 [  2] 9 MediaPlayer:tearDownTransientPipelineElements
2017-10-10 02:35:42.745 [  9] 9 MediaPlayer:getOffsetCalled
2017-10-10 02:35:42.802 [  2] 9 BaseStreamSource:~BaseStreamSource
2017-10-10 02:35:42.806 [  2] 0 MediaPlayer:callingOnPlaybackFinished
2017-10-10 02:35:42.833 [  2] 9 AudioPlayer:onPlaybackFinished
UIManager::onPlaybackFinished
2017-10-10 02:35:42.841 [  2] 9 MediaPlayer:doStopSuccess
2017-10-10 02:35:42.851 [  2] 0 MediaPlayer:handleGetOffsetCalled
2017-10-10 02:35:42.857 [  2] E MediaPlayer:handleGetOffsetFailed:reason=invalidPipelineState,state=NULL,expectedStates=PAUSED/PLAYING
2017-10-10 02:35:42.878 [  9] 0 ContextManager:updateStateLocked:action=updatedState,state={"token"\:"amzn1.as-ct.v1.Domain\:Application\:DailyBriefing\:TTS#ACRI#ssml#ACRI#DailyBriefingPrompt.7b384bd7-9c31-4167-b908-2bd67b546dd1\:ChannelIntroduction\:0"\,"offsetInMilliseconds"\:0\,"playerActivity"\:"PLAYING"},namespace=AudioPlayer,name=PlaybackState
2017-10-10 02:35:42.922 [  7] 0 ContextManager:buildContextSuccessful:context={"context"\:[{"header"\:{"namespace"\:"AudioPlayer"\,"name"\:"PlaybackState"}\,"payload"\:{"token"\:"amzn1.as-ct.v1.Domain\:Application\:DailyBriefing\:TTS#ACRI#ssml#ACRI#DailyBriefingPrompt.7b384bd7-9c31-4167-b908-2bd67b546dd1\:ChannelIntroduction\:0"\,"offsetInMilliseconds"\:0\,"playerActivity"\:"PLAYING"}}\,{"header"\:{"namespace"\:"SpeechSynthesizer"\,"name"\:"SpeechState"}\,"payload"\:{"token"\:"amzn1.as-ct.v1.Domain\:Application\:DailyBriefing\:TTS#ACRI#DailyBriefingPrompt.ChannelIntroduction.7b384bd7-9c31-4167-b908-2bd67b546dd1\:Say\:DAILYBRIEFING\:DailyBriefingIntroduction"\,"offsetInMilliseconds"\:0\,"playerActivity"\:"FINISHED"}}\,{"header"\:{"namespace"\:"Alerts"\,"name"\:"AlertsState"}\,"payload"\:{"allAlerts"\:[]\,"activeAlerts"\:[]}}\,{"header"\:{"namespace"\:"SpeechRecognizer"\,"name"\:"RecognizerState"}\,"payload"\:{"wakeword"\:""}}]}
2017-10-10 02:35:42.936 [  9] 9 AudioPlayer:executeOnPlaybackFinished
2017-10-10 02:35:43.071 [  9] 9 MediaPlayer:getOffsetCalled
2017-10-10 02:35:43.075 [  a] 0 AudioInputProcessor:executeOnContextAvailable:jsonContext={"context"\:[{"header"\:{"namespace"\:"AudioPlayer"\,"name"\:"PlaybackState"}\,"payload"\:{"token"\:"amzn1.as-ct.v1.Domain\:Application\:DailyBriefing\:TTS#ACRI#ssml#ACRI#DailyBriefingPrompt.7b384bd7-9c31-4167-b908-2bd67b546dd1\:ChannelIntroduction\:0"\,"offsetInMilliseconds"\:0\,"playerActivity"\:"PLAYING"}}\,{"header"\:{"namespace"\:"SpeechSynthesizer"\,"name"\:"SpeechState"}\,"payload"\:{"token"\:"amzn1.as-ct.v1.Domain\:Application\:DailyBriefing\:TTS#ACRI#DailyBriefingPrompt.ChannelIntroduction.7b384bd7-9c31-4167-b908-2bd67b546dd1\:Say\:DAILYBRIEFING\:DailyBriefingIntroduction"\,"offsetInMilliseconds"\:0\,"playerActivity"\:"FINISHED"}}\,{"header"\:{"namespace"\:"Alerts"\,"name"\:"AlertsState"}\,"payload"\:{"allAlerts"\:[]\,"activeAlerts"\:[]}}\,{"header"\:{"namespace"\:"SpeechRecognizer"\,"name"\:"RecognizerState"}\,"payload"\:{"wakeword"\:""}}]}
2017-10-10 02:35:43.085 [  2] 0 MediaPlayer:handleGetOffsetCalled
2017-10-10 02:35:43.182 [  a] 1 FocusManager:acquireChannel:channelName=Dialog,activityId=SpeechRecognizer.Recognize
2017-10-10 02:35:43.187 [  2] E MediaPlayer:handleGetOffsetFailed:reason=invalidPipelineState,state=NULL,expectedStates=PAUSED/PLAYING
2017-10-10 02:35:43.198 [ 12] 9 AudioPlayer:onFocusChanged:newFocus=BACKGROUND
2017-10-10 02:35:43.198 [  a] I DirectiveProcessor:setDialogRequestIdLocked:oldValue=7ae6c5e8-0f30-41c3-abd9-774d69d4dda8,newValue=4121f372-ffef-43ed-9e11-0a6cb847adcc
2017-10-10 02:35:43.231 [  a] 0 DirectiveProcessor:scrubDialogRequestIdLocked:dialogRequestId=7ae6c5e8-0f30-41c3-abd9-774d69d4dda8
2017-10-10 02:35:43.210 [  9] 0 EventBuilder:buildJsonEventString:messageId=b1cdc2b3-9a0c-4252-933d-c1fd0f2782a9,namespace=AudioPlayer,name=PlaybackFinished
2017-10-10 02:35:43.256 [  9] 9 AudioPlayer:playNextItem:m_audioItems.size=1
2017-10-10 02:35:43.243 [  a] 0 EventBuilder:buildJsonEventString:messageId=a74ca542-5227-4d0f-94d7-968e22745313,namespace=SpeechRecognizer,name=Recognize
2017-10-10 02:35:43.263 [  9] 9 MediaPlayer:setSourceForUrlCalled
2017-10-10 02:35:43.282 [  2] 9 MediaPlayer:tearDownTransientPipelineElements
2017-10-10 02:35:43.289 [  2] 0 MediaPlayer:doStopSuccess:reason=alreadyStopped
2017-10-10 02:35:43.296 [  2] 9 MediaPlayer:doStopSuccess
2017-10-10 02:35:43.301 [ 15] 0 MediaPlayer:handleSetSourceForUrlCalled
2017-10-10 02:35:43.308 [ 15] 9 UrlSource:UrlSourceCreate
2017-10-10 02:35:43.313 [ 15] 0 UrlSource:initCalledForUrlSource
2017-10-10 02:35:43.326 [  9] 9 AudioPlayer:playNextItem:item.stream.offset=0
2017-10-10 02:35:43.330 [  9] 9 MediaPlayer:playCalled
2017-10-10 02:35:43.992 [  b] 0 HTTP2Stream:receivedRequestId:value=x-amzn-requestid\: 06d802fffe77d8c8-00004301-00003d4c-c099a9d7cdce092f-e236ba9a-31
2017-10-10 02:35:44.004 [  b] 0 HTTP2Transport:cleanupFinishedStream:streamId=31,result=204
2017-10-10 02:35:44.011 [  b] 0 HTTP2StreamPool:releaseStream:streamId=31,numAcquiredStreams=1
2017-10-10 02:35:44.019 [  b] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
2017-10-10 02:35:44.029 [  b] 0 HTTP2StreamPool:getStream:streamId=33,numAcquiredStreams=2
2017-10-10 02:35:44.037 [  b] 9 HTTP2Transport:insertActiveStream:handle=0xb466f010
2017-10-10 02:35:45.216 [ 12] E AudioPlayer:onFocusChangedFailed:reason=timedout,cause=executorTimeout
2017-10-10 02:35:45.223 [  a] 0 AudioInputProcessor:executeOnFocusChanged:newFocus=FOREGROUND
2017-10-10 02:35:45.324 [  b] 0 HTTP2Stream:receivedRequestId:value=x-amzn-requestid\: 06d802fffe77d8c8-00004301-00003d4c-c099a9d7cdce092f-e236ba9a-33
2017-10-10 02:35:45.336 [  b] 0 HTTP2Transport:cleanupFinishedStream:streamId=33,result=204
2017-10-10 02:35:45.343 [  b] 0 HTTP2StreamPool:releaseStream:streamId=33,numAcquiredStreams=1
2017-10-10 02:35:45.351 [  b] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
2017-10-10 02:35:45.361 [  b] 0 HTTP2StreamPool:getStream:streamId=35,numAcquiredStreams=2
2017-10-10 02:35:45.369 [  b] 9 HTTP2Transport:insertActiveStream:handle=0xb466f010
2017-10-10 02:35:45.871 [  b] 0 HTTP2Stream:receivedRequestId:value=x-amzn-requestid\: 06d802fffe77d8c8-00004301-00003d4c-c099a9d7cdce092f-e236ba9a-35
2017-10-10 02:35:45.882 [  b] 0 HTTP2Transport:cleanupFinishedStream:streamId=35,result=204
2017-10-10 02:35:45.890 [  b] 0 HTTP2StreamPool:releaseStream:streamId=35,numAcquiredStreams=1
2017-10-10 02:35:45.898 [  b] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
2017-10-10 02:35:45.908 [  b] 0 HTTP2StreamPool:getStream:streamId=37,numAcquiredStreams=2
2017-10-10 02:35:45.916 [  b] 9 HTTP2Transport:insertActiveStream:handle=0xb466f010
2017-10-10 02:35:52.793 [  f] 0 MessageInterpreter:receive:messageId=2278c084-81ce-4639-a027-c694347f1cac:No dialogRequestId attached to message.
2017-10-10 02:35:52.805 [  f] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechRecognizer"\,name\:"StopCapture"\,messageId\:"2278c084-81ce-4639-a027-c694347f1cac"\,dialogRequestId\:""}
2017-10-10 02:35:52.821 [ 10] I DirectiveRouter:preHandleDirective:messageId=2278c084-81ce-4639-a027-c694347f1cac,action=calling
2017-10-10 02:35:52.832 [ 10] 0 CapabilityAgent:addingMessageIdToMap:messageId=2278c084-81ce-4639-a027-c694347f1cac
2017-10-10 02:35:52.842 [ 11] I DirectiveRouter:handleDirective:messageId=2278c084-81ce-4639-a027-c694347f1cac,action=calling
2017-10-10 02:35:52.854 [  a] 0 AudioInputProcessor:stopCapture:stopImmediately=true
2017-10-10 02:35:52.861 [  a] 0 AudioInputProcessor:setState:from=RECOGNIZING,to=BUSY
2017-10-10 02:35:52.868 [  e] 0 DialogUXStateAggregator:setState:from=LISTENING,to=THINKING
###########################
#       Thinking...       #
###########################
enable timeout checking...
201[7 -1190.10-10 02:38520] m:52u.86l9 [  a] 0 tiire_ccttrivl_ePrsocecssorroll_onHandlingCompewtedo:messagrkIdfn, ne78c 0s84-81ce-4639-a0roll work is queued
27-c694347f1cac,directiveBeingPreHandled=(nullptr)
2017-10-10 02:35:52.893 [  b] I InProcessAttachmentReader:readFailed:reason=SDS is closed
2017-10-10 02:35:52.925 [  a] 0 CapabilityAgent:removingMessageIdFromMap:messageId=2278c084-81ce-4639-a027-c694347f1cac
2017-10-10 02:35:57.899 [  e] 0 DialogUXStateAggregator:transitionFromThinkingTimedOut
2017-10-10 02:35:57.904 [  e] 0 DialogUXStateAggregator:setState:from=THINKING,to=IDLE
2017-10-10 02:35:57.911 [  a] 1 FocusManager:releaseChannel:channelName=Dialog
-----mode OFF-------
########################################
#       Alexa is currently idle!       #
########################################
2017-10-10 02:35:57.926 [ 12] 9 AudioPlayer:onFocusChanged:newFocus=FOREGROUND
2017-10-10 02:35:57.926 [  a] 0 AudioInputProcessor:setState:from=BUSY,to=IDLE
disable timeout checking...
2017-10-10 02:35:57.953 [  a] 0 AudioInputProcessor:executeOnFocusChanged:newFocus=NONE
2017-10-10 02:35:57.959 [  a] 0 AudioInputProcessor:executeOnFocusChanged:reason=Lost focus
2017-10-10 02:35:59.942 [ 12] E AudioPlayer:onFocusChangedFailed:reason=timedout,cause=executorTimeout
2017-10-10 02:36:03.672 [ 16] 9 LibCurlHttpContentFetcher:getContent:responseCode=200
2017-10-10 02:36:03.678 [ 16] 9 LibCurlHttpContentFetcher:getContent:contentType=audio/mpeg
2017-10-10 02:36:03.686 [ 17] 9 PlaylistParser:PlaylistParser:contentType=audio/mpeg
2017-10-10 02:36:03.693 [ 17] 9 UrlSource:urlParsedSuccessfully
2017-10-10 02:36:03.699 [  2] 0 MediaPlayer:handlePlayCalled
2017-10-10 02:36:03.703 [  2] 0 MediaPlayer:doStopSuccess:reason=alreadyStopped
2017-10-10 02:36:03.711 [  2] 9 MediaPlayer:doStopSuccess
2017-10-10 02:36:03.716 [  2] 0 MediaPlayer:handlePlay:attemptBuffering=1
2017-10-10 02:36:05.118 [  2] 0 MediaPlayer:handlePlay:startingState=PAUSED,stateReturn=ASYNC
2017-10-10 02:36:05.125 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:36:05.125 [  9] 9 AudioPlayer:executeOnFocusChanged:from=FOREGROUND,to=BACKGROUND,m_starting=false,m_currentActivity=PLAYING
2017-10-10 02:36:05.141 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:36:05.146 [  9] 9 AudioPlayer:executeOnFocusChanged:action=pauseMediaPlayer
2017-10-10 02:36:05.157 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:36:05.162 [  9] 9 MediaPlayer:pausedCalled
2017-10-10 02:36:05.170 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:36:05.182 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:36:05.190 [  2] 9 MediaPlayer:State Change:oldState=NULL,newState=READY,pendingState=PAUSED
2017-10-10 02:36:05.199 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:36:05.207 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:36:05.214 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:36:05.222 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:36:05.230 [  2] 9 MediaPlayer:messageReceived:messageType=stream-status
2017-10-10 02:36:05.237 [  2] 9 MediaPlayer:messageReceived:messageType=state-changed
2017-10-10 02:36:05.244 [  2] 9 MediaPlayer:messageReceived:messageType=stream-status
2017-10-10 02:36:05.252 [  2] 0 MediaPlayer:handlePauseCalled
2017-10-10 02:36:05.547 [  b] 0 HTTP2Stream:receivedRequestId:value=x-amzn-requestid\: 06d802fffe77d8c8-00004301-00003d4c-c099a9d7cdce092f-e236ba9a-37
2017-10-10 02:36:05.558 [  b] 0 HTTP2Transport:cleanupFinishedStream:streamId=37,result=204
2017-10-10 02:36:05.566 [  b] 0 HTTP2StreamPool:releaseStream:streamId=37,numAcquiredStreams=1
2017-10-10 02:36:05.574 [  b] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
2017-10-10 02:36:16.887 [ 18] 9 MediaPlayer:onPadAddedCalled
2017-10-10 02:38:16.012 [  a] 0 AudioInputProcessor:setState:from=IDLE,to=RECOGNIZING
2017-10-10 02:38:16.017 [  e] 0 DialogUXStateAggregator:setState:from=IDLE,to=LISTENING
################[ 1331.071766] multi_ctrl_breath_work_fn, new breath work is queued
############
#       Listening...       #
############################
enable timeout checking...
[ 1331.187045] nf_conntrack: automatic helper assignment is deprecated and it will be removed soon. Use the iptables CT target to attach helpers instead.
2017-10-10 02:38:18.041 [  7] E ContextManager:updateStatesLoopFailed:reason=stateProviderTimedOut
2017-10-10 02:38:18.048 [  a] E AudioInputProcessor:executeOnContextFailure:error=STATE_PROVIDER_TIMEDOUT
2017-10-10 02:38:18.057 [  a] 0 AudioInputProcessor:setState:from=RECOGNIZING,to=IDLE
2017-10-10 02:38:18.064 [  e] 0 DialogUXStateAggregator:setState:from=LISTENING,to=IDLE
########################################
-----mode OFF-------
#       Alexa is currently idle!       #
########################################
disable timeout checking...
2017-10-10 02:38:25.306 [  a] 0 AudioInputProcessor:setState:from=IDLE,to=RECOGNIZING
2017-10-10 02:38:25.311 [  e] 0 DialogUXStateAggregator:setState:from=IDLE,to=LISTENING
#######[ 1340.##14####8]# mu##########
trl_# re   th_woListening...   rk  fn#, new br
                                              e############################
enaatbleh timeou w crk is qhecukineg..u.ed

2017-10-10 02:38:27.318 [  7] E ContextManager:updateStatesLoopFailed:reason=stateProviderTimedOut
2017-10-10 02:38:27.325 [  a] E AudioInputProcessor:executeOnContextFailure:error=STATE_PROVIDER_TIMEDOUT
2017-10-10 02:38:27.334 [  a] 0 AudioInputProcessor:setState:from=RECOGNIZING,to=IDLE
2017-10-10 02:38:27.342 [  e] 0 DialogUXStateAggregator:setState:from=LISTENING,to=IDLE
-----mode OFF-------
########################################
#       Alexa is currently idle!       #
########################################
disable timeout checking...
2017-10-10 02:38:33.040 [  a] 0 AudioInputProcessor:setState:from=IDLE,to=RECOGNIZING
2017-10-10 02:38:33.045 [  e] 0 DialogUXStateAggregator:setState:from=IDLE,to=LISTENING
############################
#       Listening...       #
############################
enab[ le13 ti4meo7ut .c8312h55] multking..trl_breath_wo
rk_fn, new breath work is queued
2017-10-10 02:38:35.046 [  7] E ContextManager:updateStatesLoopFailed:reason=stateProviderTimedOut
2017-10-10 02:38:35.053 [  a] E AudioInputProcessor:executeOnContextFailure:error=STATE_PROVIDER_TIMEDOUT
2017-10-10 02:38:35.062 [  a] 0 AudioInputProcessor:setState:from=RECOGNIZING,to=IDLE
2017-10-10 02:38:35.070 [  e] 0 DialogUXStateAggregator:setState:from=LISTENING,to=IDLE
########################################
-----mode OFF-------
#       Alexa is currently idle!       #
########################################
disable timeout checking...
2017-10-10 02:38:37.614 [  a] 0 AudioInputProcessor:setState:from=IDLE,to=RECOGNIZING
2017-10-10 02:38:37.619 [  e] 0 DialogUXStateAggregator:setState:from=IDLE,to=LISTENING
0#####[ #####1#####3#52.######68#4####
 ]#      m  Listeultni_ing.c..       #
r##########_##br##eat##h_work_fn, new breath w############
checking...i ism queeouued
2017-10-10 02:38:39.621 [  7] E ContextManager:updateStatesLoopFailed:reason=stateProviderTimedOut
2017-10-10 02:38:39.627 [  a] E AudioInputProcessor:executeOnContextFailure:error=STATE_PROVIDER_TIMEDOUT
2017-10-10 02:38:39.636 [  a] 0 AudioInputProcessor:setState:from=RECOGNIZING,to=IDLE
2017-10-10 02:38:39.644 [  e] 0 DialogUXStateAggregator:setState:from=LISTENING,to=IDLE
-----mode OFF-------
########################################
#       Alexa is currently idle!       #
########################################

**Comment by dhpp** [comment] 2017-10-12 15:08
Hi jacky-ge,

Thanks for posting this.  The text "ContextManager:updateStatesLoopFailed:reason=stateProviderTimedOut" means that one of the CapabilityAgents within the SDK became unresponsive, and could not provide Context to the ContextManager when requested.  This is needed for for some events - looking at your trace it appears your application was trying to send a Recognize Event to AVS, which is one of the Events which requires Context.  Context is an aggregation of the current state of the client.

I would like to ask if this is something that you can replicate?  How much have you changed the underlying code, if any?  Thanks.  -David

**Comment by dhpp** [comment] 2017-10-12 15:48
As one more update, this does seem similar to an issue we're currently working on, and for which we expect to release a fix soon.

**Comment by scotthea-amazon** [comment] 2017-12-08 20:14
Hi jacky-ge,

A few issues in this area have been fixed in recent releases.  Can you reproduce this problem in the current release?

Thank you,
-SWH

**Comment by sanjayrd** [comment] 2017-12-11 22:10
Closing due to inactivity

**Closed by sanjayrd** 2017-12-11 22:10 UTC
Labels: MediaPlayer
