### ISSUE TITLE
Unable to create the Sample App

### ISSUE THREAD

**Issue by sai13ram** [alexa/avs-device-sdk#1620] opened 2020-02-13 11:20 UTC
## Briefly summarize your issue:
After executing this command `sudo bash setup.sh config.json -a androidConfig.txt -s 998987` as mentioned in the the third step of Authorizatoin in the page [https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/android.html](url), i am getting an error. Help would be appreciated

## What is the expected behavior?
The SDK should finish building the AVS SDK and then save the Configuration file

## What behavior are you observing?
`================================================================================
= ANDROID_HOME:         /home/rpa13/Android
= ANDROID_NDK:          /home/rpa13/Android/ndk/ndk-bundle/android-ndk-r16
= CMAKE_TOOLCHAIN_FILE: /home/rpa13/Android/ndk/ndk-bundle/android-ndk-r16/build/cmake/android.toolchain.cmake
= CXX:                  /home/rpa13/Android/ndk/toolchains/android-ndk-r16/toolchain-x86/android-24/bin/i686-linux-android-clang++
= READELF:              /home/rpa13/Android/ndk/toolchains/android-ndk-r16/toolchain-x86/android-24/bin/i686-linux-android-readelf
= STRIP:                /home/rpa13/Android/ndk/toolchains/android-ndk-r16/toolchain-x86/android-24/bin/i686-linux-android-strip
= SYSROOT:              /home/rpa13/Android/ndk/toolchains/android-ndk-r16/toolchain-x86/android-24/sysroot
= TOOLCHAIN:            /home/rpa13/Android/ndk/toolchains/android-ndk-r16/toolchain-x86/android-24
= TOOLCHAIN_HOST:       i686-linux-android
= INSTALL_PATH:         /home/rpa13/AVS-SDK/debug/android-24/x86/install
= DEVICE_INSTALL_PATH:  /home/rpa13/AVS-SDK/Sample App and Dependencies

################################################################################
################################################################################

AVS Device SDK Android Script - Terms and Agreements

The AVS Device SDK is dependent on several third-party libraries, environments, 
and/or other software packages that are installed using this script from 
third-party sources ("External Dependencies"). These are terms and conditions 
associated with the External Dependencies 
(available at https://github.com/alexa/avs-device-sdk/wiki/Dependencies) that 
you need to agree to abide by if you choose to install the External Dependencies.

If you do not agree with every term and condition associated with the External 
Dependencies, enter "QUIT" in the command line when prompted by the installer.
Else enter "AGREE".

################################################################################
################################################################################
AGREE
################################################################################
Proceeding with installation
################################################################################
[ 35%] Built target AVSCommon
[ 35%] Built target SynchronizeStateSender
[ 38%] Built target ACL
[ 41%] Built target ADSL
[ 43%] Built target AFML
[ 46%] Built target Captions
[ 46%] Built target RegistrationManager
[ 48%] Built target SQLiteStorage
[ 48%] Built target Alexa
[ 51%] Built target EqualizerImplementations
[ 51%] Built target ContextManager
[ 53%] Built target SystemSoundPlayer
[ 56%] Built target PlaylistParser
[ 56%] Built target SpeechEncoder
[ 58%] Built target AudioResources
[ 58%] Built target ApiGateway
[ 58%] Built target AudioPlayer
[ 61%] Built target Bluetooth
[ 61%] Built target Equalizer
[ 61%] Built target ExternalMediaPlayer
[ 61%] Built target InteractionModel
[ 61%] Built target Notifications
[ 64%] Built target PlaybackController
[ 64%] Built target SpeakerManager
[ 66%] Built target SpeechSynthesizer
[ 69%] Built target TemplateRuntime
[ 71%] Built target AndroidUtilities
[ 74%] Built target CBLAuthDelegate
[ 74%] Built target AVSGatewayManager
[ 76%] Built target CertifiedSender
[ 79%] Built target Endpoints
[ 82%] Built target AndroidSLESMediaPlayer
[ 84%] Built target DeviceSettings
[ 87%] Built target CapabilitiesDelegate
[ 87%] Built target AIP
[ 87%] Built target DoNotDisturbCA
[ 89%] Built target Alerts
[ 92%] Built target AVSSystem
[ 94%] Built target DefaultClient
[100%] Built target SampleApp

==============> SAVING CONFIGURATION FILE ==============

[ERROR] Alexa Device Source directory not found!
Usage: genConfig.sh <config.json file> <device_serial_number> <db path> <SDK Source Directory>
<output AlexaClientSDKConfig.json file> [-D<variable>=<value>]+
1) <config.json file> can be downloaded from developer portal and must contain the following:
   "clientId": "<OAuth client ID>"
   "productId": "<your product name for device>"
2) <device_serial_number> specifies the deviceInfo deviceSerialNumber in the output json file.
3) <db path> specifies the path to where the databases will be located.
4) <SDK Source Directory> specifies the root directory to where the avs-device-sdk source code is located.
5) <output AlexaClientSDKConfig.json file> output file
6) Configure different variables that can be used to fill up extra information in the final configuration. Avaiable variables are:
   "SDK_CONFIG_MANUFACTURER_NAME": The name of the device manufacturer. This variable is required.
   "SDK_CONFIG_DEVICE_DESCRIPTION": The description of the device. This variable `

## Provide the steps to reproduce the issue, if applicable:

Run android.sh, using config.json, androidConfix.txt, and the device serial number (DSN) as arguments. You can either provide your own DSN, or use the system default (123456). The DSN can be any unique alpha-numeric string (up to 64 characters). You should use this string to identify your product or application instance. Many developers choose to use a product's SKU for this value.
For example: `sudo bash setup.sh config.json -a androidConfig.txt -s 998987`

## Tell us about your environment:
Ubuntu 18.04 LTS with Android Emulator ( Rooted). Building Amazon AVS SDk for Android

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment] 2020-02-17 21:30
Hello @sai13ram,

What version of the SDK are you using?

Looking at the current (1.17) version [genConfig.sh](https://github.com/alexa/avs-device-sdk/blob/v1.17.0/tools/Install/genConfig.sh), it seems that the script has passed the check for seven arguments, so the issue is not that the fourth parameter is missing.  Rather, it seems that somehow the fourth parameter ($SOURCE_PATH/avs-device-sdk in [setup.sh](https://github.com/alexa/avs-device-sdk/blob/v1.17.0/tools/Install/setup.sh#L281)) has resolved in to something other than a directory.

You might try:
- Adding a line in genConfig.sh right before the [output of the error message](https://github.com/alexa/avs-device-sdk/blob/v1.17.0/tools/Install/genConfig.sh#L68) that echos the value of "$SDK_SRC_PATH".
- Adding a line in setup.sh [right before the invocation of genConfig.sh](https://github.com/alexa/avs-device-sdk/blob/v1.17.0/tools/Install/setup.sh#L281) to echo the command line that is about to be invoked.

Best regards,
-SWH

**Comment by caleighatamazon** [comment] 2020-03-11 20:40
I'm going to close this issue due to inactivity. Please feel free to comment here or open a new issue if you have further questions or problems.

**Closed by caleighatamazon** 2020-03-11 20:40 UTC

**Comment by gustavosinbandera1** [comment] 2020-09-03 20:26
I am getting this issue following the steps on AVS documentation 
```
gustavo@gustavo-VirtualBox:~/sdk_folder/avs-device-sdk/tools/Install$ ./genConfig.sh /home/gustavo/sdk_folder/config.json "SDKTestProduct" $HOME/sdk_folder/db/ $HOME/sdk_folder/avs-device-sdk $HOME/sdk_folder/sdk-build/Integration/AlexaClientSDKConfig.json
[ERROR] Missing parameters!
Usage: genConfig.sh <config.json file> <device_serial_number> <db path> <SDK Source Directory>
<output AlexaClientSDKConfig.json file> [-D<variable>=<value>]+
1) <config.json file> can be downloaded from developer portal and must contain the following:
   "clientId": "<OAuth client ID>"
   "productId": "<your product name for device>"
2) <device_serial_number> specifies the deviceInfo deviceSerialNumber in the output json file.
3) <db path> specifies the path to where the databases will be located.
4) <SDK Source Directory> specifies the root directory to where the avs-device-sdk source code is located.
5) <output AlexaClientSDKConfig.json file> output file
6) Configure different variables that can be used to fill up extra information in the final configuration. Avaiable variables are:
   "SDK_CONFIG_MANUFACTURER_NAME": The name of the device manufacturer. This variable is required.
   "SDK_CONFIG_DEVICE_DESCRIPTION": The description of the device. This variable is required.
```
