### ISSUE TITLE
[AVS SDK v1.6]Alexa SDK not responding after two hour.

### ISSUE THREAD

**Issue by MTKYZ** [alexa/avs-device-sdk#1023] opened 2018-10-22 23:22 UTC
Hi Amazon,

**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
We met a problem, after two hour started, alexa doesn’t work properly, there is no response on music play or weather checking.
We checked the log and found AVS to be in Listening state, And it always in that state.
Is this because there is no feedback from the server? The SampleApp program didn't hang up in this case. Could you give me some advices? 
## Here is the detail log:
2018-10-22 10:54:26.886 [  c] 0 AudioInputProcessor:setState:from=IDLE,to=RECOGNIZING
2018-10-22 10:54:26.886 [  3] 0 DialogUXStateAggregator:setState:from=IDLE,to=LISTENING
2018-10-22 10:54:26.887 [  3] 5 TemplateRuntime:onDialogUXStateChanged:state=LISTENING
2018-10-22 10:54:26.887 [  8] 5 VisualActivityTracker:provideState
2018-10-22 10:54:26.887 [  8] 0 NotificationsCapabilityAgent:provideState:stateRequestToken=3
2018-10-22 10:54:26.887 [  8] 5 AudioActivityTracker:provideState
############################
#       Listening...       #
############################
2018-10-22 10:54:26.887 [  9] 5 VisualActivityTracker:executeProvideState
2018-10-22 10:54:26.887 [  9] 0 ContextManager:updateStateLocked:action=updatedState,namespace=VisualActivityTracker,name=ActivityState
2018-10-22 10:54:26.887 [  a] 0 ExternalMediaPlayer:executeProvideState:sendToken=true,stateRequestToken=3
2018-10-22 10:54:26.887 [  a] 0 ContextManager:updateStateLocked:action=updatedState,namespace=Alexa.PlaybackStateReporter,name=playbackState
2018-10-22 10:54:26.887 [  a] 0 ExternalMediaPlayer:executeProvideState:sendToken=true,stateRequestToken=3
2018-10-22 10:54:26.887 [  a] 0 ContextManager:updateStateLocked:action=updatedState,namespace=ExternalMediaPlayer,name=ExternalMediaPlayerState
2018-10-22 10:54:26.887 [  6] 5 NotificationsCapabilityAgent:executeProvideState:sendToken=true,stateRequestToken=3
2018-10-22 10:54:26.888 [  6] 0 ContextManager:updateStateLocked:action=updatedState,namespace=Notifications,name=IndicatorState
2018-10-22 10:54:26.888 [  b] 5 AudioActivityTracker:executeProvideState
2018-10-22 10:54:26.888 [  b] 0 ContextManager:updateStateLocked:action=updatedState,namespace=AudioActivityTracker,name=ActivityState
2018-10-22 10:54:26.888 [  8] 9 ContextManager:buildContextIgnored:namespace=VisualActivityTracker,name=ActivityState
2018-10-22 10:54:26.889 [  8] 0 ContextManager:buildContextSuccessful
2018-10-22 10:54:26.889 [  c] 0 AudioInputProcessor:executeOnContextAvailable
2018-10-22 10:54:26.889 [  c] 1 FocusManager:acquireChannel:channelName=Dialog,interface=SpeechRecognizer
2018-10-22 10:54:26.889 [  c] I DirectiveProcessor:setDialogRequestIdLocked:oldValue=4cbcffbf-ac68-4fd5-b4af-6a4b47938077,newValue=364f2a07-d2f0-4b5b-a117-6513ad3c4bdf
2018-10-22 10:54:26.889 [  c] 0 DirectiveProcessor:scrubDialogRequestIdLocked:dialogRequestId=4cbcffbf-ac68-4fd5-b4af-6a4b47938077
2018-10-22 10:54:26.889 [  c] 0 EventBuilder:buildJsonEventString:messageId=86a390eb-aff8-436f-85f0-17475971c773,namespace=SpeechRecognizer,name=Recognize
2018-10-22 10:54:26.889 [ 12] 9 AudioInputProcessor:onFocusChanged:newFocus=FOREGROUND
2018-10-22 10:54:26.889 [ 12] 5 AudioActivityTracker:notifyOfActivityUpdates
2018-10-22 10:54:26.889 [  b] 5 AudioActivityTracker:executeNotifyOfActivityUpdates
2018-10-22 10:54:26.889 [  c] 0 AudioInputProcessor:executeOnFocusChanged:newFocus=FOREGROUND
2018-10-22 10:54:26.889 [  c] 9 HTTP2Transport:enqueueRequest
onKeyWordDetected keyword: alexa, beginIndex: 70928400, endIndex:70936322
2018-10-22 10:54:28.487 [  c] E AudioInputProcessor:executeRecognizeFailed:reason=New audio provider can not override
[ 4504.698003] <0>-(0)[0:swapper/0]android_usb gadget: [ratelimit]non-core control req21.00 v0000 i0000 l12
[ 4504.700285] <0>-(0)[0:swapper/0]android_usb gadget: [ratelimit]non-core control reqa1.01 v0000 i0000 l4096

### What version of the AVS Device SDK are you using?
      <1.6>

### Tell us what hardware you're using:
- [ ] Other 

### Tell us about your OS (Type & version):
- [ ] Linux

**Comment by scotthea-amazon** [comment] 2018-10-22 23:53
Hello MTKYZ,

It is hard to tell what is going on from a partial log, but it looks like AIP has gotten stuck in a listening state.  If you have the complete log from this run, or you can reproduce the problem, would you please attach it to this thread (attach is much preferred to pasting in to the comment window, so the comments on this issue remain readable)?

If you can reproduce the problem, there is something you can try that may address the problem:  In AudioInputProcessor::onSendCompleted(), inside the if(){} clause, add a call to stopCapture() before the return.  If you do give this a try, please let us know if it resolves the problem.

Thank you,
-SWH

**Comment by MTKYZ** [comment] 2018-10-23 00:05
Thank you very much, i will try it.

**Comment by scotthea-amazon** [comment] 2018-10-26 00:16
Hello MTKYZ,

The suggested fix is included in release 1.10, here: https://github.com/alexa/avs-device-sdk/blob/v1.10/CapabilityAgents/AIP/src/AudioInputProcessor.cpp#L954

I hope that helps,
-SWH

**Comment by kclchan** [comment] 2018-12-12 00:12
I am closing this issue due to inactivity. Please feel free to re-open it if it has been closed in error.

**Closed by kclchan** 2018-12-12 00:12 UTC
