### ISSUE TITLE
[Auto SDK]: Alexa doesn't play the alarm for few min time set from now.

### ISSUE THREAD

**Issue by DeepikaBalaga** [alexa/avs-device-sdk#1791] opened 2020-09-13 13:37 UTC
## Briefly summarize your issue:
 if the current time is 11.25 am and I set the alarm to 11.26 am , it doesn’t play the alarm. But if I say "Alexa, play 1 min from now" it plays the alarm

## What is the expected behavior?
• Alexa states the time for which the alarm was set. 
• The alarm begins sounding at the specified time. 
• The alarm sounds for at least 60 seconds.

## What behavior are you observing?
It doesnt play the alarm for few min set from now.
Eg: if the current time is 11.25 am and I set the alarm to 11.26 am , it doesn’t play the alarm. But if I say "Alexa, play 1 min from now" it plays the alarm

## Provide the steps to reproduce the issue, if applicable:
1. Set an alarm (multi-turn).
2. After being asked "for what time," answer the time that is a minute from now.
3. Let the alarm sounds for at least 60 seconds.
## Tell us about your environment:
SW:  app-local-debug.apk

Utterance:

1. Set an alarm.
2. [The time that is one minute from now.]

### What version of the AVS Device SDK are you using?
     AUTO SDK v2.3

### Tell us what hardware you're using:
- [ ] Other

### Tell us about your OS (Type & version):
- [ ] Other

**Comment by scotthea-amazon** [comment] 2020-09-14 17:50
Hello @DeepikaBalaga,

Please use this link for assistance with the Auto SDK: https://github.com/alexa/alexa-auto-sdk/blob/2.3/NEED_HELP.md

That said, this sounds suspiciously like a problem with the time-zone setting on the client device.  When you ask "Alexa, what time is it?".  Does Alexa respond with the expected time?

Best regards,
-SWH

**Comment by scotthea-amazon** [comment] 2020-09-15 17:26
Hello @DeepikaBalaga,

Closing as this is an Auto SDK issue. Of course, if it the root cause is found to be in the AVS Device SDK, please feel free to create a new issue with information to help is reproduce and diagnose the issue.

Best regards,
-SWH

**Closed by scotthea-amazon** 2020-09-15 17:26 UTC
