### ISSUE TITLE
Endpoint getting listed in wrong category

### ISSUE THREAD

**Issue by vikramdattu** [alexa/avs-device-sdk#1684] opened 2020-04-28 15:37 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

This is kind of a generic issue, related to modified version of this SDK which runs on ESP32.

To AlexaDiscovery I am sending following event with capabilities:

```
{"event": {"header": {"namespace": "Alexa.Discovery","name": "AddOrUpdateReport","payloadVersion": "3","messageId": "4e1e9100-37f1-c5a4-e900-e863dc37e6f1","eventCorrelationToken": "4e1e9100-37f1-c5a4-e900-e863dc37e6f1"},"payload": {"scope": {"type": "BearerToken","token": "------------------------------"},"endpoints": [{"endpointId": "amzn1.application-oa2-client.320d0c28204541e4a061b7aff8e7d1b9::<product_id>::240ac49d0028","registration": {"productId": "<product_id>","deviceSerialNumber": "1425d6a5-ae31-d0d1-c7bb-d60069cd34bf"},"manufacturerName": "Espressif","description": "Alexa Device","friendlyName": "ESP Alexa","displayCategories": ["SWITCH"],"additionalAttributes": {"manufacturer": "Espressif","model": "ESP32","serialNumber": "1425d6a5-ae31-d0d1-c7bb-d60069cd34bf","firmwareVersion": "v1.2","softwareVersion": "v1.2","customIdentifier": "1425d6a5-ae31-d0d1-c7bb-d60069cd34bf"},"capabilities": [{"type":"AlexaInterface","interface":"InteractionModel","version":"1.2"},{"type":"AlexaInterface","interface":"Bluetooth","version":"1.0"},{"type":"AlexaInterface","interface":"Alexa","version":"3"},{"type":"AlexaInterface","interface":"System","version":"2.0","configurations": {"locales":["de-DE","en-AU","en-CA","en-GB","en-IN","en-US","es-ES","es-MX","es-US","fr-CA","fr-FR","hi-IN","it-IT","ja-JP","pt-BR"],"localeCombinations":[["en-US","es-US"],["es-US","en-US"],["en-IN","hi-IN"],["hi-IN","en-IN"],["fr-CA","en-CA"],["en-CA","fr-CA"]]}},{"type":"AlexaInterface","interface":"Alexa.ApiGateway","version":"1.0"},{"type":"AlexaInterface","interface":"Speaker","version":"1.0"},{"type":"AlexaInterface","interface":"SpeechRecognizer","version":"2.3","configurations":{"wakeWords":[{"scopes":["DEFAULT"],"values":[["ALEXA"]]}]}},{"type":"AlexaInterface","interface":"SpeechSynthesizer","version":"1.0"},{"type":"AlexaInterface","interface":"AudioPlayer","version":"1.0"},{"type":"AlexaInterface","interface":"AudioActivityTracker","version":"1.0"},{"type":"AlexaInterface","interface":"Alerts","version":"1.1","configurations":{"maximumAlerts":{"overall":3,"alarms":2,"timers":2}}},{"type":"AlexaInterface","interface":"Notifications","version":"1.0"},{"type":"AlexaInterface","interface":"Alexa.DoNotDisturb","version":"1.0"},{"type": "AlexaInterface","interface": "Alexa","version": "3"},{"type":"AlexaInterface","interface":"Alexa.PowerController","version":"3","properties": {"supported": [{"name": "powerState"}],"proactivelyReported": true,"retrievable": true}},{"type":"AlexaInterface","interface":"Alexa.ToggleController","version":"3","instance": "ESPAlexa.Light","properties": {"supported": [{"name": "toggleState"}],"proactivelyReported": true,"retrievable": true,"nonControllable": false},"capabilityResources":{"friendlyNames":[{"@type":"text","value":{"text":"Light","locale":"en-US"}}]}}],"connections":[]},{"endpointId": "amzn1.application-oa2-client.320d0c28204541e4a061b7aff8e7d1b9::esp_avs_master::240ac49d0028_1","registration": {"productId": "esp_avs_master","deviceSerialNumber": "cd569918-6544-48ac-8f8d-4000b740c973"},"manufacturerName": "Espressif","description": "Alexa Device","friendlyName": "ESP Bulb","displayCategories": ["LIGHT"],"additionalAttributes": {"manufacturer": "Espressif","model": "ESP32","serialNumber": "cd569918-6544-48ac-8f8d-4000b740c973","firmwareVersion": "v1.2","softwareVersion": "v1.2","customIdentifier": "cd569918-6544-48ac-8f8d-4000b740c973"},"capabilities": [{"type":"AlexaInterface","interface":"Alexa.PowerController","version":"3","properties": {"supported": [{"name": "powerState"}],"proactivelyReported": true,"retrievable": true}},{"type":"AlexaInterface","interface":"Alexa.ToggleController","version":"3","instance": "ESPAlexa.Light","properties": {"supported": [{"name": "toggleState"}],"proactivelyReported": true,"retrievable": true,"nonControllable": false},"capabilityResources":{"friendlyNames":[{"@type":"text","value":{"text":"Light","locale":"en-US"}}]}}],"connections":[]}]}}}
```

Please note that there are two endpoints: One with Alexa and another which Alexa implements on behalf of.

For both I have set distinct serial numbers and unique Device ID etc.

Category for one device I have set is for SWITCH and for other LIGHT.
In Alexa app however, both are listed under LIGHT section. (ESP Alexa and ESP Bulb)

## What is the expected behavior?
Both endpoints should not be categorised under LIGHT section.

## What behavior are you observing?
Both endpoints get listed as LIGHT section.

### What version of the AVS Device SDK are you using?

Alexa Interface 3.0.
PowerController and ToggleController.      

### Tell us what hardware you're using:
- [ ] Other - tell us more:
Custom: ESP32 based LyraT board

### Tell us about your OS (Type & version):
- [ ] Other - tell us more:
FreeRTOS (esp-idf)

![Screenshot_20200428-202230_Amazon%20Alexa](https://user-images.githubusercontent.com/5511751/80507169-28268680-8994-11ea-8c4e-a521769221a8.jpg)

**Comment by caleighatamazon** [comment] 2020-04-28 18:59
Hi @vikramdattu, I'm investigating this issue further. I'll let you know when I have updates.

**Comment by caleighatamazon** [comment] 2020-04-28 19:17
Hi @vikramdattu, I've created an internal ticket for the responsible team. This does not seem to be an issue with the SDK, so I can't directly help you further. However, I'll follow up on this ticket internally to ensure the responsible team is able to get this fixed.

In the meantime, I'm going to close this issue with the "Bug Filed" label. Please comment further if you have more information to share or have further questions.

**Comment by caleighatamazon** [comment] 2020-04-29 16:55
Hi @vikramdattu, the team that's looking into this issue has asked for some follow-up information from you. Please respond with this information when you get a chance: 

1) What is the Alexa app version number? Navigate to Settings → Scroll all the way down → Tap on "About" → Ask the customer for the "App Version"
2) What is the Host Name? Navigate to Settings → Scroll all the way down → Tap on "About" → Ask the customer for the "Host Name"
3) What is the mobile device model and OS version?  [iOS/Android/FireOS, Mobile device model, OS version]
4) Is this issue always reproducible?
5) What was the time of occurrence (UTC)?
6) Was there any error message or feedback displayed in the GUI App?
7) How’s the customer’s Internet connectivity and what's the connection method (4G/LTE/WIFI)? (Internet connectivity)

**Comment by vikramdattu** [comment] 2020-04-30 04:55
Hello @caleighatamazon 

I want to share some info about my further experiments first:
Extra info:

Here is what I did to get rid of the issue:
I went to https://alexa.amazon.in/ . Did forget all from SmartHome tab.
And sent the above mentioned event again. Now devices get listed properly.


The reason for the issue could be that, I am still in development phase and am experimenting with the endpoints.
Nevertheless, the issue shouldn't exist IMHO.



Please find the replies inline:

What is the Alexa app version number? Navigate to Settings → Scroll all the way down → Tap on "About" → "App Version"

**2.2.329454.0**

What is the Host Name? Navigate to Settings → Scroll all the way down → Tap on "About" → "Host Name"

**alexa.amazon.in**

What is the mobile device model and OS version? [iOS/Android/FireOS, Mobile device model, OS version]

Samsung GalaxyS10 (SM-G973F) / Android10 + OneUI2.1

Is this issue always reproducible?
**Yes** Before doing above procedure to remove all devices.

What was the time of occurrence (UTC)?
It always happened.

Was there any error message or feedback displayed in the GUI App?

**No specific error messages.**

How’s the Internet connectivity and what's the connection method (4G/LTE/WIFI)? 
**Tried both on 4G n/w and WiFi. Issue is there irrespective of network conditions.**

**Comment by caleighatamazon** [comment] 2020-04-30 16:09
Thanks for the additional information. So, if I'm understanding you correctly, you have resolved this problem on your own -- this is no longer a problem for you, right?

I'll pass your information along to the team. They may wish to have a followup conversation with you about the bug, in which case I'll provide contact information for them.

In the meantime I'll close this ticket since (1) this is not an issue with the SDK, so it's outside the scope of this support forum, and (2) the problem appears to be resolved.

Thanks again for reporting this.

**Closed by caleighatamazon** 2020-04-30 16:09 UTC
Labels: Awaiting more information

**Comment by vikramdattu** [comment] 2020-04-30 16:28
What I did(removed all the previous endpoints) looks like a workaround. I still think this is a bug.

**Comment by caleighatamazon** [comment] 2020-05-12 18:16
Hi @vikramdattu, just a quick update -- as we've established, this isn't a bug with the SDK, so we did close the issue here. But I looked into how you can reach the right team for further debugging help (they will need some private customer information from you to help debug the issue, which is not safe for you to share in this public forum).

You can file a bug with the owning team by submitting a customer service ticket (using Help & Feedback inside the Alexa App). That will get routed to the right team. Hope this helps.

**Comment by Thomas-fang** [comment] 2021-11-05 07:34
Hi,I am Thomas-fang, On the Alexa homepage, the SDK is only applicable to five operating systems. How to make the SDK run in the FreeRTOS operating system? I hope to get your reply. Thank you.
