### ISSUE TITLE
how to SpeechSynthesizer sound become a Stereo mp3/wav

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#418] opened 2017-12-27 02:20 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

My ARM machine can't play mono sound file, otherwise how could i recive the stereo sound file from SpeechSynthesizer?
## What is the expected behavior?

receive the Stereo Speech sound file
## What behavior are you observing?

just receive mono sound file from Speech
## Provide the steps to reproduce the issue, if applicable:

'tell me a joke' for asking alexa,and response the Speech sound 
## Tell us about your environment:
NXP in yocto

### What version of the AVS Device SDK are you using?
    AVS DEVICE SDK  <1.2.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ V] Other - NXP in yocto

### Tell us about your OS (Type & version):
- [V ] Linux
- [ ] MacOS
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mradulan** [comment] 2017-12-27 23:19
@captainpanther , mono or stereo sound file comes from AVS. SpeechSynthesizer only plays the sound file. Can you convert to stereo sound file on your ARM platform?

**Comment by captainpanther** [comment] 2017-12-28 05:38
No, i can't find other method that convert Stereo in ARM.

**Comment by mradulan** [comment] 2017-12-28 23:17
if you are using gstreamer, you can convert mono to stereo. Are you using gstreamer? What version?

**Comment by captainpanther** [comment] 2017-12-29 02:01
i use gstreamer 1.10.4 , so can u tell me that how could i transform mono
to stereo in gstreamer for sound file?

2017-12-29 7:17 GMT+08:00 Mradula Nayak <notifications@github.com>:

**Comment by kclchan** [comment] 2018-01-04 17:34
Hi @captainpanther, one way to transform mono to stereo is to add an audioconvert element in the pipeline in MediaPlayer.  You can learn more about the gstreamer element in (https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-plugins/html/gst-plugins-base-plugins-audioconvert.html).

But I think it's more appropriate to find the root cause as to why your platform cannot play mono sound files.  Maybe there is a misconfiguration?

**Comment by captainpanther** [comment] 2018-01-05 09:28
Thank ur reply,but i have been solved the problem for transfer stream buff
to local sound file .

2018-01-05 1:34 GMT+08:00 Kenneth Chan <notifications@github.com>:

**Comment by kclchan** [comment] 2018-01-05 17:38
Hi @captainpanther, looks like you've found a way to resolve the issue you are seeing.  I will close this ticket then.  Thanks!

**Closed by kclchan** 2018-01-05 17:38 UTC
