### ISSUE TITLE
Alex a setup in raspberry pi 3 stops at 95%

### ISSUE THREAD

**Issue by DP0077bruh** [alexa/avs-device-sdk#2012] opened 2022-01-30 10:44 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:

**Comment by wryley-amzn** [comment] 2022-02-08 18:16
HI, this a duplicate of #2011, please check for updates and discuss on that thread.

**Comment by wryley-amzn** [comment] 2022-02-08 18:18
Duplicate of #2011

**Comment by mariopaonessa** [comment] 2022-02-12 10:02
Hello folks in my case it worked to increase the swap size. I believe it runs into OOM:

1. stop the swap
`sudo dphys-swapfile swapoff`

2. change the swap size CONF_SWAPSIZE=100 for example to 1024 (vi or your editor of choice)
`sudo vi /etc/dphys-swapfile`

3. renew the swap file
`sudo dphys-swapfile setup`

4. restart the swap service
`sudo dphys-swapfile swapon`

**Comment by blazusiak-amazon** [comment] 2022-02-28 18:40
Hello @DP0077bruh,
Did the suggestions above resolve the issue you were experiencing?

**Comment by womw** [comment] 2022-03-21 22:59
Hello @DP0077bruh due to inactivity I'll be closing this ticket. Please feel free to open a new one if you continue experiencing this issue.

**Closed by womw** 2022-03-21 22:59 UTC
Labels: Awaiting more information
