### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by coderdude207** [alexa/avs-device-sdk#1463] opened 2019-08-13 10:10 UTC
/usr/bin/ld: CMakeFiles/SampleApp.dir/SampleApplication.cpp.o: in function `std::__atomic_base<unsigned long long>::operator=(unsigned long long)':
/usr/include/c++/8/bits/atomic_base.h:374: undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/SampleApp.dir/PortAudioMicrophoneWrapper.cpp.o: in function `alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits>::Writer::write(void const*, unsigned int, std::chrono::duration<long long, std::ratio<1ll, 1000ll> >)':
/usr/include/c++/8/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/SampleApp.dir/PortAudioMicrophoneWrapper.cpp.o: in function `alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits>::Writer::Writer(alexaClientSDK::avsCommon::utils::sds::WriterPolicy, std::shared_ptr<alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits>::BufferLayout>)':
/usr/include/c++/8/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/SampleApp.dir/PortAudioMicrophoneWrapper.cpp.o: in function `std::__atomic_base<unsigned long long>::operator unsigned long long() const':
/usr/include/c++/8/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
/usr/bin/ld: ../../ACL/src/libACL.so: undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[3]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/build.make:288: SampleApp/src/SampleApp] Error 1
make[2]: *** [CMakeFiles/Makefile2:10227: SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:10239: SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [Makefile:2580: SampleApp] Error 2

My hardware is raspberry pi 3
and os is raspbian.
Please tell me how can I fix this issue

**Comment by scotthea-amazon** [comment] 2019-08-15 18:54
Hello @coderdude207,

This sounds just like the issue #1404.  Please try the fix suggested for that issue.

If that does not help, would you tell us what version of Raspian you are using by posting the contents of /etc/os-release.

Best regards,
-SWH

**Comment by scotthea-amazon** [comment] 2019-08-15 19:56
Hello @coderdude207,

I am closing this issue as a duplicate of #1404.  If you think it has been closed in error, please feel free to re-open it.

Best regards,
-SWH

**Closed by scotthea-amazon** 2019-08-15 19:56 UTC
