### ISSUE TITLE
SiriusXM will loop play automatically

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1291] opened 2019-03-22 04:43 UTC
Hi AVS team,

SDK 1.9.0  , ARM based embedded linux.

We got a report from US user that the SiriusXM will continue to loop the same station about every 5 minutes for all channels. 
There is no loop option for stations, so I asked user to help collect log (attachment)
You can find the keyword "RenderPlayerInfoCard" for display card message and it seems it will auto-stopped while playing and re-play automatically with same station.
I can also see some error before stop playing in the log.
Could you please help to check this case ? 

[siriusXM-loop.zip](https://github.com/alexa/avs-device-sdk/files/2994991/siriusXM-loop.zip)

**Comment by aumatsui** [comment] 2019-03-22 20:39
Hi zeusshuang,

We believe this issue is already on our radar, but just to make sure that we are looking at the same thing, can you elaborate on the user experience when the loop happens? Are the loops necessarily happening at the end of a song or randomly?

Unfortunately the logs at v1.9.0 do not help us see the root cause of this issue.

Thank you,

**Comment by zeusshuang** [comment] 2019-03-26 02:25
Hi @aumatsui ,

By user's feedback, it's not from the end of the song, it's random and usually in the middle of the song.
And user said there is a behavior for reference -
Play song A -> song B -> song C -> song D, but in the middle of the song D, it jump back to song C. 
Then the content plays until it reaches the exact same spot in song D and then jump back to the exact same spot in the song C, then go into loop.

**Comment by aumatsui** [comment] 2019-03-26 17:33
Thank  you @zeusshuang  for the additional details. This is, indeed, the same issue that we have already identified and we already have an internal ticket to fix it.

**Comment by zeusshuang** [comment] 2019-03-26 23:44
Hi @aumatsui ,
thanks for the information.

**Comment by kclchan** [comment] 2019-07-05 18:49
This issue is fixed in SDK v1.13.  Please re-open this issue if you can still reproduce it.  Thank!

**Closed by kclchan** 2019-07-05 18:49 UTC
