### ISSUE TITLE
When a reminder interrupt Alexa interaction, once the request TTS is finished, the full reminder package (sound cue plus TTS) should play once.

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1578] opened 2019-12-09 09:50 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When we set a reminder and interrupt alexa then as per amazon guidelines 
https://developer.amazon.com/docs/alexa-voice-service/ux-design-interrupts.html#alerts-interrupting-alexa

https://developer.amazon.com/docs/alexa-voice-service/ux-design-interrupts.html#when-an-alert-is-playing-in-full-mode
It has to play audio cue 2 times of full reminder after TTS is done.

But,when we are interrupting Alexa while reminder is ringing then it is not giving any response to related to reminder i.e., it is not playing the reminder audio cue 2 times.
## What is the expected behavior?

If reminder is set and Alexa is  interrupted while reminder is rendering then it has to play the reminder in full mode after TTS is completed
.
## What behavior are you observing?

Alexa is not playing reminder in full mode if TTS is completed
## Provide the steps to reproduce the issue, if applicable:

1.Alexa set kitchen reminder for 10 secs.
2.When reminder is about to start. Ask weather for next 7 days.
## Tell us about your environment:
android pie

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ .] Other - tell us more:
android
#
## Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ .] Other - tell us more:
9.0

**Comment by scotthea-amazon** [comment] 2019-12-10 22:36
@dipalisb,

Thank you for bringing this to our attention.  I have been able to reproduce the behavior you describe.  We will investigate.

Best regards,
-SWH

**Comment by dipalisb** [comment] 2020-01-06 05:53
Hi @scotthea-amazon ,
Could you please tell us , Is there any update on this issue.
Thanks,

**Comment by dipalisb** [comment] 2020-01-06 05:54
Hi,
Could you please tell us, Is there any update on this issue.
Thanks,

**Comment by womw** [comment] 2020-01-06 23:55
@dipalisb we are still currently investigating this issue.

**Comment by caleighatamazon** [comment] 2020-03-11 19:02
@dipalisb Please re-try this on 1.18. I am not able to reproduce this issue on our 1.18 release.

**Comment by kclchan** [comment] 2020-04-09 23:25
I am closing this issue due to inactivity. Please feel free to re-open it if it has been closed in error.

**Comment by scotthea-amazon** [comment] 2020-04-13 23:07
@dipalisb,

This was closed in error.  The problem was reproduced and there is still an open investigation.  Unfortunately, no update on a fix.

Thank you,
-SWH

**Comment by scotthea-amazon** [comment] 2020-04-15 01:28
@dipalisb 

We are now closing issues for which we have filed an internal ticket to our backlog.

If you have further input on this issue, please feel free to re-open it and add more comments.

Best regards,
-SWH

**Closed by scotthea-amazon** 2020-04-15 01:28 UTC

**Comment by dipalisb** [comment] 2020-04-29 07:22
Hi,

We have checked with 1.19 version and we are facing this issue again. 
Please  help us by by checking at your end.

Thanks

**Comment by caleighatamazon** [comment] 2020-04-29 16:35
Hi @dipalisb, unfortunately this issue remains in our backlog and we did not fix it for 1.19.
