### ISSUE TITLE
Alexa is going to listening state though mute key is turned ON.(waking up Alexa through touch initiation)

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1539] opened 2019-10-24 09:23 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

The device we are using is both touch and voice initiated.If Mute Key is ON and if we wake up Alexa using wake word "Alexa". It will not go to listening state. But,with touch initiated that is if we press action button then it is going to listening state.
Also please find the screen-shot from AVS design guidelines.

## What is the expected behavior?

Please confirm us, what is the actual behavior.

## What behavior are you observing?

If Mute key is turned ON and if we press action button to wake up Alexa then it is going to Listening and thinking state.With wake word  "Alexa", it is not going to listening and thinking state if Mute key is ON.

## Provide the steps to reproduce the issue, if applicable:

Turn on the Mute key.
Press action button to wake up Alexa.

### What version of the AVS Device SDK are you using?
      <x.y.z>
avs sdk-1.12.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ .] Other - tell us more:
android
### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ .] Other - tell us more:
Pie-9.0
![microphone](https://user-images.githubusercontent.com/52921278/67471583-40c48580-f66d-11e9-8b08-0a721735c2a4.png)
Please confirm us what is the actual behaviour.

**Comment by samcoult** [comment] 2019-10-25 22:00
Hi @dipalisb , that behaviour sounds correct. The mute or Microphone Off mode means the microphone will not be active to detect wake words. If however you also have a touch interaction to start the microphone, Alexa should be in a listening state.

Does this answer your question?

**Comment by caleighatamazon** [comment] 2019-10-30 19:19
Since this is expected behaviour, I'm going to close this issue. Feel free to re-open it if you have more questions or concerns. Thanks!

**Closed by caleighatamazon** 2019-10-30 19:19 UTC
