### ISSUE TITLE
Raspberry pi3 avs Build Fail 93% 

### ISSUE THREAD

**Issue by Wasu-RPI** [alexa/avs-device-sdk#1856] opened 2020-12-28 14:19 UTC
It long Time to Build And Stop To Build AVS At 
[ 93%] Building CXX object Application Utilities/DefaultClient/src/CMakeFiles/DefaultClient.dir/DefaultClient.cpp.o

**Comment by omk10** [comment] 2020-12-28 18:50
I have also faced a similar issue this week. As we are using Raspberry Pi 3 Model, it consists of only 1 gb ram and some of the object building processes (like [ 93%] Building CXX object Application Utilities/DefaultClient/src/CMakeFiles/DefaultClient.dir/DefaultClient.cpp.o) from recent avs-device-sdk version requires more memory for object building task. 

To solve this issue I increased my swap memory size from 100 mb (default) to 512 mb. After this only my AVS Build process completed. It is not much efficient as it takes a lot of time but it is better than a terminated build. 

To increase the swap memory: 

Open the terminal, then run 
1) sudo dphys-swapfile swapoff
2) sudo nano /etc/dphys-swapfile

After the second command, dphys-swapfile file will open and you will need to modify 

CONF_SWAPSIZE=100

to 

CONF_SWAPSIZE=512 

After changing swap size value from 100 to 512
Press CTRL+O then Enter then CTRL+X 
(To save the changes made in the file) 

Then run 
3) sudo dphys-swapfile swapon 

Now, reboot or shutdown and start your raspberry pi again and you can see your swap memory size will be increased to 512 mb 
(You can check this by running command "free -h" before and after changing the swapsize)

Now, you can run your BUILD AVS process without any error or termination.

**Comment by Wasu-RPI** [comment] 2020-12-29 07:12
Thank You. I Can Run My  Build AVS  Process 100%  And Job Finish But Long Time Not Without Error  And  I Editor Your Script As CONF_SWAPSIZE=1024.It Can Build AVS  To Smooth.

**Comment by kclchan** [comment] 2020-12-29 18:25
I am glad that setting the swap memory works for you.

**Comment by TinkerJeff** [comment] 2021-01-01 01:39
I encountered an identical issue. I added a USB thumb drive, noticed that it was setup as /dev/sda, and added /dev/sda to the swap space. After that I had no issues.

**Comment by caleighatamazon** [comment] 2021-01-05 18:48
It looks like you've resolved this issue, so I'll close this. So far we haven't been able to reproduce the problem on our Pi 3, but we're still investigating. Thanks for letting us know how you fixed it.

**Closed by caleighatamazon** 2021-01-05 18:48 UTC
