### ISSUE TITLE
No playback sound

### ISSUE THREAD

**Issue by pappy15** [alexa/avs-device-sdk#500] opened 2018-02-08 13:01 UTC
Hi, I installed the avs device sdk 1.4 on raspberry pi 2 with raspbian stretch, one usb microphone and one usb sound card for playback.
The startsample.sh works now and it recognizes the word commands. But there is no playback over usb sound card.
If I record and play a .wav over arecord/aplay everything works fine.

/home/pi/.asoundrc looks like:

> pcm.!default {
>   type asym
>    playback.pcm {
>      type plug
>      slave.pcm "hw:0,0"
>    }
>    capture.pcm {
>      type plug
>      slave.pcm "hw:1,0"
>    }
> }

**Comment by mradulan** [comment] 2018-02-08 19:53
can you check #484 and set your asoundrc according to that?

**Comment by pappy15** [comment] 2018-02-09 12:33
I checked this, but no matter what I write in /home/pi/.asoundrc, sample app uses always the 3.5mm jack of raspberry pi.

I already found a asound.conf in /home/pi/Desktop/third-party/alexa-rpi/config/, but choosing the right card there, the usb sound card doesn't work in the sample app too.

**Comment by jguerreiro** [comment] 2018-02-15 16:43
I have been experiencing the same issue and have not found a solution on this code line (git hub project).
I am using the hardware recommendations, and it listens but, it does not speak.
I have reinstalled the portaudio binaries, and still no sound from Alexa but, oddly, the AYL speaker works well with other output.

**Comment by jguerreiro** [comment] 2018-02-15 20:51
############################
#       Listening...       #
############################

2018-02-15 20:48:47.388 [  2] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2018-02-15 20:48:47.388 [  2] I DirectiveProcessor:setDialogRequestIdLocked:oldValue=,newValue=9208f3a8-2f64-4725-b26e-e3077716c2f6
2018-02-15 20:48:49.251 [  3] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechRecognizer"\,name\:"StopCapture"\,messageId\:"38e08fb2-8cc6-4e77-9b54-345bfba226de"\,dialogRequestId\:""}
2018-02-15 20:48:49.252 [  4] I DirectiveRouter:preHandleDirective:messageId=38e08fb2-8cc6-4e77-9b54-345bfba226de,action=calling
2018-02-15 20:48:49.252 [  5] I DirectiveRouter:handleDirective:messageId=38e08fb2-8cc6-4e77-9b54-345bfba226de,action=calling
###########################
#       Thinking...       #
###########################

2018-02-15 20:48:49.261 [  6] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2018-02-15 20:48:49.262 [  6] I InProcessAttachmentReader:readFailed:reason=SDS is closed
2018-02-15 20:48:49.622 [  3] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechSynthesizer"\,name\:"Speak"\,messageId\:"7e23554d-b1b9-40e8-8bdb-999e0fb90278"\,dialogRequestId\:"9208f3a8-2f64-4725-b26e-e3077716c2f6"}
2018-02-15 20:48:49.623 [  4] I DirectiveRouter:preHandleDirective:messageId=7e23554d-b1b9-40e8-8bdb-999e0fb90278,action=calling
2018-02-15 20:48:49.624 [  5] I DirectiveRouter:handleDirective:messageId=7e23554d-b1b9-40e8-8bdb-999e0fb90278,action=calling
2018-02-15 20:48:49.629 [  7] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2018-02-15 20:48:49.629 [  7] E MediaPlayer:saveOffsetBeforeTeardown - gst_element_query_position failed
2018-02-15 20:48:49.773 [  7] I InProcessAttachmentReader:readFailed:reason=SDS is closed
###########################
#       Speaking...       #
###########################

########################################
#       Alexa is currently idle!       #
########################################

**Comment by celinval** [comment] 2018-02-15 22:12
Hi,

Can you please paste the results for the following commands:

```
cat /proc/asound/cards
cat /proc/asound/modules
aplay -l -L
arecord -l -L
arecord -v /tmp/test.wav
aplay -v /tmp/test.wav
```

**Comment by yoelrc88** [comment] 2018-02-16 17:34
The same happening to me. Looks like is getting the wakeword but I can't hear the response from alexa. Here is my output:
```
pi@matrixpi:~ $ cat /proc/asound/card
card0/ card1/ cards  
pi@matrixpi:~ $ cat /proc/asound/cards 
 0 [ALSA           ]: bcm2835 - bcm2835 ALSA
                      bcm2835 ALSA
 1 [U0x46d0x81b    ]: USB-Audio - USB Device 0x46d:0x81b
                      USB Device 0x46d:0x81b at usb-3f980000.usb-1.4, high speed
pi@matrixpi:~ $ cat /proc/asound/modules 
 0 snd_bcm2835
 1 snd_usb_audio
pi@matrixpi:~ $ aplay -l -L
null
    Discard all samples (playback) or generate zero samples (capture)
default
sysdefault:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
dmix:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample mixing device
dmix:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample mixing device
dsnoop:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample snooping device
hw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct hardware device without any conversions
plughw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Hardware device with all software conversions
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@matrixpi:~ $ arecord -l -L
null
    Discard all samples (playback) or generate zero samples (capture)
default
sysdefault:CARD=U0x46d0x81b
    USB Device 0x46d:0x81b, USB Audio
    Default Audio Device
front:CARD=U0x46d0x81b,DEV=0
    USB Device 0x46d:0x81b, USB Audio
    Front speakers
surround21:CARD=U0x46d0x81b,DEV=0
    USB Device 0x46d:0x81b, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=U0x46d0x81b,DEV=0
    USB Device 0x46d:0x81b, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=U0x46d0x81b,DEV=0
    USB Device 0x46d:0x81b, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=U0x46d0x81b,DEV=0
    USB Device 0x46d:0x81b, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=U0x46d0x81b,DEV=0
    USB Device 0x46d:0x81b, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=U0x46d0x81b,DEV=0
    USB Device 0x46d:0x81b, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=U0x46d0x81b,DEV=0
    USB Device 0x46d:0x81b, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=U0x46d0x81b,DEV=0
    USB Device 0x46d:0x81b, USB Audio
    Direct sample mixing device
dsnoop:CARD=U0x46d0x81b,DEV=0
    USB Device 0x46d:0x81b, USB Audio
    Direct sample snooping device
hw:CARD=U0x46d0x81b,DEV=0
    USB Device 0x46d:0x81b, USB Audio
    Direct hardware device without any conversions
plughw:CARD=U0x46d0x81b,DEV=0
    USB Device 0x46d:0x81b, USB Audio
    Hardware device with all software conversions
**** List of CAPTURE Hardware Devices ****
card 1: U0x46d0x81b [USB Device 0x46d:0x81b], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
pi@matrixpi:~ $ 
```

**Comment by celinval** [comment] 2018-02-16 18:54
@yoelrc88,  can you also please try the two following commands? Let me know if you hear a beep in any of them:

```
gst-launch-1.0 -m audiotestsrc ! alsasink 
gst-launch-1.0 -m audiotestsrc ! autoaudiosink 
```

Thanks

**Comment by yoelrc88** [comment] 2018-02-19 23:54
Hi @celinval, Thanks for the response,

At the begin I got that didn't have the comand
```
$ gst-launch-1.0 -m audiotestsrc ! alsasink
zsh: command not found: gst-launch-1.0
```
Then installed 
```
sudo apt install gstreamer1.0-tools gstreamer1.0-alsa
```
and got this:
```

**Comment by yoelrc88** [comment] 2018-02-23 17:24
Anyone that can help here?

**Comment by mavamazon** [comment] 2018-02-23 17:38
Hi Yoel!
In your case - could you please make sure that all of those are installed:
gst-plugins-base gst-plugins-good gst-plugins-bad

Also, in case it didn't help, try to install gst-plugins-ugly as well.

**Comment by mavamazon** [comment] 2018-02-23 17:40
@jguerreiro,

Could you please provide the output requested or let us know if problem is already solved?

**Comment by a2ron** [comment] 2018-02-24 17:15
I had the same problem, now solved. Ensure you can reproduce commands/configurations below:

You should be able to reproduce a mp3 file like below:
```
wget https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3
mpg123 SoundHelix-Song-1.mp3
```

You should hear a beep when executing: 

`gst-launch-1.0 -m audiotestsrc ! alsasink 
`
> I had to install the following packages first.
`sudo apt install gstreamer1.0-tools gstreamer1.0-alsa
`

My .asoundrc file (jack for audio, usb for micro)
```
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}
```

**Comment by vishnudevk** [comment] 2018-02-26 06:35
In my case audio is always directed to HDMI.  All other applications including aplay send audio to 3.5 jack.
But  sampleapp always send audio to HDMI. What change I should make for redirecting audio to 3.5 jack?

**Comment by jazzkitt** [comment] 2018-02-26 09:54
@vishnudevk have the same question, leaving a comment to receive update when someone replies. Thanks in advance. Also changing audio output using `sudo raspi-config ` doesn't change anything.

**Comment by mavamazon** [comment] 2018-02-26 10:52
@vishnudevk, @jazzkitt,

You can try to modify boot/config.txt: comment out the following line: hdmi_force_hotplug=1 and then reboot and try if SDK plays audio to correct output. Also you can change the [line in MediaPlayer.cpp﻿](https://github.com/alexa/avs-device-sdk/blob/0be45093215d3e9594cb38228f2743a7b461c795/MediaPlayer/src/MediaPlayer.cpp#L599), so that instead of:

m_pipeline.audioSink = gst_element_factory_make("autoaudiosink", "audio_sink");

you have:

m_pipeline.audioSink = gst_element_factory_make("alsasink", "audio_sink");

**Comment by a2ron** [comment] 2018-02-26 19:10
other issue I had it was volume was 0 when rebooting, so I added a crontab:
```
@reboot amixer set Master 65536
```

**Comment by vishnudevk** [comment] 2018-02-27 04:40
@mavamazon
Changing
m_pipeline.audioSink = gst_element_factory_make("autoaudiosink", "audio_sink");
to 
m_pipeline.audioSink = gst_element_factory_make("alsasink", "audio_sink");

Worked for me. Thank you very much !!

**Comment by davorf** [comment] 2018-02-27 13:29
Hello!

I've had similar problem with USB Speaker/Microphone combo (handsfree). Microphone was working fine, but all the sounds (Alexa Speech) were redirected to HDMI. Since this is single USB device, both microphone and speaker were CARD 1 (aplay -l). Changing default sound card in Raspbian worked with aplay, but not with Alexa. The only solution to that worked for me was changing part of the setup.sh script, namely, changing:

```
cat << EOF > "$SOUND_CONFIG"
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}
EOF
```
to
```
cat << EOF > "$SOUND_CONFIG"
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}
EOF
```
After that change, you need to run `sudo bash setup.sh` config.txt again (delete any previously created folders/files, so setup would be executed from the begining).

Best regards,
Davor

**Comment by kencecka** [comment] 2018-02-28 19:25
Hi All,

There are a number of good suggestions and success stories that have accumulated on this thread.  It's a little unclear who still has issues as there have been multiple users posting here.  I'm going to go ahead and close this issue; please post a new issue if you are still having problems and we will continue to troubleshoot.

Ken

**Closed by kencecka** 2018-02-28 19:25 UTC

**Comment by Likhitha11** [comment] 2019-12-13 11:00
Hi. 
I know the issue has been long closed but I've recently started working with the AVS Sample app. I face the same issue of not being able to send and receive audio through my desired sound card which is a DSP connected to the raspberry pi. After changes in MediaPlayer.cpp, the output is now given from the desired sound card while the problem persists with capturing the audio as in it still takes the audio from the other device. Can you please tell me how I can go ahead? I've tried making changes in pi.sh, asoundrc and thirdparty/alexa-rpi/config/asound.conf. Sadly nothing seems to work..I've been trying to do this for a long time now. Kindly help. Thank you

**Comment by antonjudes** [comment] 2020-07-28 15:14
> Hi.
> I know the issue has been long closed but I've recently started working with the AVS Sample app. I face the same issue of not being able to send and receive audio through my desired sound card which is a DSP connected to the raspberry pi. After changes in MediaPlayer.cpp, the output is now given from the desired sound card while the problem persists with capturing the audio as in it still takes the audio from the other device. Can you please tell me how I can go ahead? I've tried making changes in pi.sh, asoundrc and thirdparty/alexa-rpi/config/asound.conf. Sadly nothing seems to work..I've been trying to do this for a long time now. Kindly help. Thank you

Like davorf mentioned in his comment. You need to update the sound config settings before running avs setup.sh.

first check the proper soundcards using 
aplay -l
arecord -l
note the hardware and card number

new avs installation wgets 3 sh files. in pi.sh change your sound cards in below section
cat << EOF > "$SOUND_CONFIG"
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}
EOF

then run the sudo bash setup.sh config.json [-s 1234]
if you have already installed, you have to delete everything related to this avs, mainly avs-device-sdk and build folders
works like a charm

need a lot of patience to rebuild avs.. if anybody can find a easier solution to just change the sound card and build only that part, would be of great help.
