### ISSUE TITLE
AVS connection will be kicked off after 2nd AVS on-line

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1266] opened 2019-03-08 10:02 UTC
Hi AVS team,

SDK 1.12 .  ARM based embedde linux system.

We received a very strange issue from user's site, and user said, while he run two DUT (AVS enabled device) in the same network, these two DUT will off-line.
But if only one is on-line, it's working. Or set these two DUT in different networking environment (different public IP), it's also working.

I attached two logs here. "avs_dbg_log_1" is DUT1, and "avs_dbg_log_2" is DUT2.
In this case, DUT1 on-line first, and it's working well. Then, power on DUT2, I can see, while DUT2 is ready, DUT1 will receive a "SERVER_SIDE_DISCONNECT" message and disconnected. 
Then, DUT2 also received "SERVER_SIDE_DISCONNECT" and disconnected.

In DUT1 log, you will see at timestamp "2019-03-08 08:51:36.615" disconnected
In DUT2 log, it's at "2019-03-08 08:51:41.460".

We can make sure the serial number and MAC address are different, but it's use the same Alexa account.
It's reproducible there every time.

We tried this case in our Lab, but all working even I ran 6 DUT at the same network.
Maybe from server site's point of view, there is something needed to check and failed but we don't know.

Could you have suggestions ?

[avs_dbg_log_1.txt](https://github.com/alexa/avs-device-sdk/files/2945284/avs_dbg_log_1.txt)
[avs_dbg_log_2.txt](https://github.com/alexa/avs-device-sdk/files/2945285/avs_dbg_log_2.txt)

**Comment by kclchan** [comment] 2019-03-08 22:17
Hi @zeusshuang, from the AVS side, both devices are identical and that's the reason it's getting the SERVER_SIDE_DISCONNECT.  Please double check if the serial number between the two device are indeed unique.

**Comment by zeusshuang** [comment] 2019-03-08 23:03
Hi @kclchan ,

No, it's not the same serial number. I also checked the token in these two devices, these are not the same.
If the device serial number is the same, it will be always failed. But in this case, if the user move the DUT2 to another network (different public IP), it will be working fine.

Is there any way it can check the root cause from the server side ? if it's doable, I can contact my amazon business contact. Any advanced information I need to collect ?

**Comment by kclchan** [comment] 2019-03-08 23:23
Hi @zeusshuang, that's so strange.  Yes, please contact your Amazon business contact.  This will allow us to gather more information to root cause this.  Thanks!

**Comment by subjectxbj** [comment] 2019-03-15 02:22
We met the same problem as well. When 2 DUT authorized with the same Amazon account work under the same LAN network, this issue will happen.

**Comment by zeusshuang** [comment] 2019-03-20 08:19
@kclchan , we have found our root cause for this case, and it's same serial number issue. 
But I am not sure if @subjectxbj 's issue is the same as my.

**Comment by kclchan** [comment] 2019-07-05 20:52
I am closing this issue now.  Thanks!.

**Closed by kclchan** 2019-07-05 20:52 UTC
