### ISSUE TITLE
Web app doesn't pause after Audible sending PlaybackPaused event

### ISSUE THREAD

**Issue by mynewsty23** [alexa/avs-device-sdk#670] opened 2018-04-30 06:01 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

We ask weather when playing Audible. The Audible paused on device but the web app still showing playing Audible.

From Log, we send a pause event in listening status but the icon on web app doesn't change to pause.
> ############################
> #       Listening...       #
> ############################
> 2018-04-30 04:00:33.587 [  6] 0 AudioPlayer:executeProvideState:sendToken=true,stateRequestToken=5
> 2018-04-30 04:00:33.589 [  6] 0 ContextManager:updateStateLocked:action=updatedState,namespace=AudioPlayer,name=PlaybackState
> 2018-04-30 04:00:33.592 [  4] 0 ContextManager:buildContextSuccessful
> 2018-04-30 04:00:33.593 [  a] 0 AudioPlayer:onFocusChanged:newFocus=BACKGROUND
> 2018-04-30 04:00:33.593 [  6] 1 AudioPlayer:executeOnFocusChanged:from=FOREGROUND,to=BACKGROUND,m_currentActivity=PLAYING
> 2018-04-30 04:00:33.594 [  6] 1 AudioPlayer:executeOnFocusChanged:action=pauseMediaPlayer
> 2018-04-30 04:00:33.610 [  b] 0 AudioPlayer:onPlaybackPaused:id=6
> 2018-04-30 04:00:33.611 [  6] 1 AudioPlayer:executeOnPlaybackPaused:id=6
> 2018-04-30 04:00:33.611 [  6] 1 AudioPlayer:sendEventWithTokenAndOffset:eventName=PlaybackPaused
> 2018-04-30 04:00:33.612 [  6] 9 HTTP2Transport:enqueueRequest
> 2018-04-30 04:00:33.612 [  6] 0 AudioPlayer:changeActivity:from=PLAYING,to=PAUSED
> 2018-04-30 04:00:33.613 [  6] 0 AudioPlayer:executeProvideState:sendToken=false,stateRequestToken=0
> 2018-04-30 04:00:33.613 [  7] 9 HTTP2Transport:enqueueRequest
> 2018-04-30 04:00:33.613 [  6] 0 ContextManager:updateStateLocked:action=updatedState,namespace=AudioPlayer,name=PlaybackState
> 2018-04-30 04:00:33.622 [  6] 1 AudioPlayer:notifyObserver:playerActivity=PAUSED
> 2018-04-30 04:00:33.648 [  8] 0 HTTP2Transport:processNextOutgoingMessage:jsonContent={"event"\:{"header"\:{"namespace"\:"AudioPlayer"\,"name"\:"PlaybackPaused"\,"messageId"\:"e13aca1a-969d-4247-a1b5-e16675a08f44"}\,"payload"\:{"token"\:"amzn1.as-ct.v1.AudibleClientId#ACRI#url#ACRI#playq\:audiobook/audible;mv\=Audible\,c53b9497-3f3d-4451-9d64-3b247d721366#6"\,"offsetInMilliseconds"\:418000}}}

Did I miss any event or wrong flow?

Full log can be found here.
[audible_webapp_no_pause.txt](https://github.com/alexa/avs-device-sdk/files/1959660/audible_webapp_no_pause.txt)

## What is the expected behavior?

Audible should pause on web app when speaking weather.

## What behavior are you observing?

The web app still shows playing Audible when speaking weather.

## Provide the steps to reproduce the issue, if applicable:

Alexa, Play Audible.
(Wait for playing Audible)
Alexa, What's the weather.
(Audible pause and speak weather but the web app still in playing status)

### What version of the AVS Device SDK are you using?
        <1.4.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [X] Other - tell us more: ARM A7

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [X] Other - tell us more: Linux OpenWRT

**Comment by frozenberg** [comment] 2018-04-30 21:48
Hi @mynewsty23,

Does this also reproduce on the mobile app?

Fede

**Comment by zeusshuang** [comment] 2018-05-01 01:28
Hi @frozenberg ,

We also got some issues while playing audible books or Kindle.
To follow this case, may I say may mobile APP behavior is different from web APP ?
for example, while I interrupt the audible book playing and resume, the progress bar will become different between mobile and web APP (sometimes, mobile APP will be correct).

**Comment by frozenberg** [comment] 2018-05-01 16:43
Hi @zeusshuang,

Yes, it seems that the behaviors of the web app and the mobile app aren't always consistent. Does that answer your question?

Fede

**Comment by mynewsty23** [comment] 2018-05-02 02:32
Hi @frozenberg 

Yes, this problem is the same as mobile app.

**Comment by mynewsty23** [comment] 2018-05-21 03:47
Can you reproduce this problem?

**Comment by dhpp** [comment] 2018-11-07 16:38
I'll close this one out.  As @frozenberg mentioned, this is a known issue which AVS will be continuing to address, and is not caused by the client implementation on the device, it is related to how various cloud infrastructures interact with AVS.

**Closed by dhpp** 2018-11-07 16:38 UTC
