### ISSUE TITLE
connection fail - retry 

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#530] opened 2018-02-22 07:14 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

i use command : TZ=UTC ./Sample ../../Integration/AlexaXXXX.json DEBUG9
but it always fail to launch.

#############################
#       Connecting...       #
#############################

2018-01-26 07:18:42.030 [  4] E HTTP2Transport:networkLoopRetryingToConnect:reason=establishConnectionFailed,retryCount=0,retryBackoff=199
2018-01-26 07:18:43.447 [  4] E HTTP2Transport:networkLoopRetryingToConnect:reason=establishConnectionFailed,retryCount=1,retryBackoff=1438
2018-01-26 07:18:45.918 [  4] E HTTP2Transport:networkLoopRetryingToConnect:reason=establishConnectionFailed,retryCount=2,retryBackoff=4054
2018-01-26 07:18:51.012 [  4] E HTTP2Transport:networkLoopRetryingToConnect:reason=establishConnectionFailed,retryCount=3,retryBackoff=3385
2018-01-26 07:18:55.323 [  4] E HTTP2Transport:networkLoopRetryingToConnect:reason=establishConnectionFailed,retryCount=4,retryBackoff=12835
Failed to connect to AVS!
2018-01-26 07:19:00.847 [  1] I DirectiveSequencer:doShutdown

## What is the expected behavior?

it should start SampleApp successfully.
## What behavior are you observing?

Failed to connect to AVS!
## Provide the steps to reproduce the issue, if applicable:

TZ=UTC ./Sample ../../Integration/AlexaXXXX.json DEBUG9
## Tell us about your environment:

ubuntu 14.04 64 bit

### What version of the AVS Device SDK are you using?
      <x.y.z>
     SDK 1.2
### Tell us what hardware you're using:
- [V ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [V ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by captainpanther** [comment] 2018-02-22 07:15
i use another AlexXXXX.json to authorize but it still fail.

**Comment by scotthea-amazon** [comment] 2018-02-22 15:56
Hi captainpanther,

We will need more detailed logs to diagnose what is going wrong with the connection process.  I do not see ay of the DEBUG0-9 level logs even though you specified DEBUG9 on the command line.  That hints very strongly that this is a RELEASE build (DEBUG0-9 logs are compiled out of RELEASE builds).  Can you re-run the cmake command with -DCMAKE_BUILD_TYPE=DEBUG, re-run make, reproduce the issue, and post the full log (as an attachment please, if possible).

Thank you,
-SWH

**Comment by captainpanther** [comment] 2018-02-27 03:58
hi scotthea:
   the issue even happen, [(https://github.com/alexa/avs-device-sdk/issues/260)]
if  avs sdk 1.5.0 have solved, maybe don't need ongoing  the issue. Just i recompile for sdk 1.5.0 ?!!

**Comment by scotthea-amazon** [comment] 2018-02-27 04:03
Hi captainpanther,
Sorry, but I do not quite understand what you meant with your last comment.  Are you saying that the problem went away when you rebuild with the 1.5.0 version of the SDK?  If so, feel free to close the issue.
Thank you,
-SWH

**Comment by captainpanther** [comment] 2018-02-27 04:07
No, i am not sure that the issue have solved for recompiling sdk 1.5.0.
I experiment sdk 1.5.0 for my embedded system. just wait and don't closed this topic.thx.

**Comment by captainpanther** [comment] 2018-02-27 06:02
i have been recompile for sdk 1.5.0  ,it still fail to connect:

root@imx7dsabresd:/opt/avs_build_15/SampleApp/src# TZ=UTC ./SampleApp ../../../AlexaClientSDKConfig_14format.json DEBUG9 2018-02-14 05:42:38.437 [ 1] I sdkVersion: 1.5.0 Running app with log level: DEBUG9 2018-02-14 05:42:38.441 [ 1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9: WARNING: By default DEBUG logs are compiled out of RELEASE builds. Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs. 2018-02-14 05:42:38.441 [ 1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9: WARNING: By default DEBUG logs are compiled out of RELEASE builds. Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs. 2018-02-14 05:42:38.612 [ 1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9: WARNING: By default DEBUG logs are compiled out of RELEASE builds. Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs. 2018-02-14 05:42:38.612 [ 1] I NotificationsCapabilityAgent:init:databaseFilePath is=/opt/avs_files/db/certified_db1.db ############################# # Connecting... # ############################# 2018-02-14 05:42:43.601 [ 2] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9: WARNING: By default DEBUG logs are compiled out of RELEASE builds. Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs. 2018-02-14 05:42:43.602 [ 2] E HTTP2Transport:networkLoopRetryingToConnect:reason=establishConnectionFailed,retryCount=0,retryBackoff=200 2018-02-14 05:42:44.829 [ 2] E HTTP2Transport:networkLoopRetryingToConnect:reason=establishConnectionFailed,retryCount=1,retryBackoff=769 2018-02-14 05:42:46.468 [ 2] E HTTP2Transport:networkLoopRetryingToConnect:reason=establishConnectionFailed,retryCount=2,retryBackoff=4454 2018-02-14 05:42:52.202 [ 2] E HTTP2Transport:networkLoopRetryingToConnect:reason=establishConnectionFailed,retryCount=3,retryBackoff=7329 2018-02-14 05:43:00.804 [ 2] E HTTP2Transport:networkLoopRetryingToConnect:reason=establishConnectionFailed,retryCount=4,retryBackoff=9272 Failed to connect to AVS! ##################################### # Client not connected! # ##################################### Failed to initialize SampleApplication Failed to create to SampleApplication! 2018-02-14 05:43:02.176 [ 1] W RequiresShutdown:ShutdownMonitor:reason=never deleted,name=SpeakerManager 2018-02-14 05:43:02.176 [ 1] W RequiresShutdown:ShutdownMonitor:reason=never deleted,name=ExternalMediaPlayer 2018-02-14 05:43:02.176 [ 1] W RequiresShutdown:ShutdownMonitor:reason=never deleted,name=NotificationsMediaPlayer 2018-02-14 05:43:02.177 [ 1] W RequiresShutdown:ShutdownMonitor:reason=never deleted,name=AlertsMediaPlayer 2018-02-14 05:43:02.177 [ 1] W RequiresShutdown:ShutdownMonitor:reason=never deleted,name=AudioMediaPlayer 2018-02-14 05:43:02.177 [ 1] W RequiresShutdown:ShutdownMonitor:reason=never deleted,name=SpeakMediaPlayer 2018-02-14 05:43:02.177 [ 1] W RequiresShutdown:ShutdownMonitor:reason=never deleted,name=AVSConnectionManager

**Comment by scotthea-amazon** [comment] 2018-02-27 16:29
Hi captainpanther,

As before, we need more detailed logs to help diagnose this issue.  You need to restart the build from the cmake step, adding -DCMAKE_BUILD_TYPE=DEBUG to the cmake command line, otherwise the DEBUG level logs are compiled out.

Thank you,
-SWH

**Comment by captainpanther** [comment] 2018-03-05 03:14
i use -DCMAKE_BUILD_TYPE=DEBUG ,and add my print log.

log is below:

TZ=UTC ./SampleApp ../../../AlexaClientSDKConfig.json DEBUG9
Running app with log level: DEBUG9
2018-02-14 05:58:36.214 [ 1] I ConfigurationNode:initializeSuccess
2018-02-14 05:58:36.227 [ 1] 9 MediaPlayer:createCalled
2018-02-14 05:58:36.342 [ 1] 9 MediaPlayer:setupPipeline
2018-02-14 05:58:36.361 [ 1] 9 MediaPlayer:createCalled
2018-02-14 05:58:36.361 [ 1] 9 MediaPlayer:setupPipeline
2018-02-14 05:58:36.365 [ 1] 9 MediaPlayer:createCalled
2018-02-14 05:58:36.365 [ 1] 9 MediaPlayer:setupPipeline
2018-02-14 05:58:36.372 [ 1] 9 MediaPlayer:setObserverCalled
2018-02-14 05:58:36.372 [ 2] 0 MediaPlayer:handleSetObserverCalled
2018-02-14 05:58:36.373 [ 1] 9 SpeechSynthesizer:addObserver:observer=0x131d34c
2018-02-14 05:58:36.373 [ 1] 9 MediaPlayer:setObserverCalled
2018-02-14 05:58:36.373 [ 2] 0 MediaPlayer:handleSetObserverCalled
2018-02-14 05:58:36.373 [ 1] 9 MediaPlayer:setObserverCalled
2018-02-14 05:58:36.373 [ 2] 0 MediaPlayer:handleSetObserverCalled
2018-02-14 05:58:36.379 [ 1] 9 AlertScheduler:setTimerForNextAlertLocked
2018-02-14 05:58:36.379 [ 1] I AlertScheduler:executeScheduleNextAlertForRendering::no work to do.
2018-02-14 05:58:36.379 [ 3] 1 AlertsCapabilityAgent:executeOnConnectionStatusChanged:status=DISCONNECTED,reason=ACL_CLIENT_REQUEST
2018-02-14 05:58:36.382 [ 1] 9 MediaPlayer:getSpeakerTypeCalled
2018-02-14 05:58:36.382 [ 1] 9 MediaPlayer:getSpeakerTypeCalled
2018-02-14 05:58:36.382 [ 1] 9 MediaPlayer:getSpeakerTypeCalled
2018-02-14 05:58:36.382 [ 1] 0 SpeakerManager:mapCreated:numAvsSynced=2,numLocal=1
2018-02-14 05:58:36.383 [ 1] 1 AudioPlayer:addObserver
2018-02-14 05:58:36.383 [ 1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0x1331c38,policy=BLOCKING
2018-02-14 05:58:36.383 [ 1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=ClearQueue,handler=0x13327d0,policy=NON_BLOCKING
2018-02-14 05:58:36.383 [ 1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Stop,handler=0x13327d0,policy=NON_BLOCKING
2018-02-14 05:58:36.384 [ 1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Play,handler=0x13327d0,policy=NON_BLOCKING
2018-02-14 05:58:36.384 [ 1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0x13311c8,policy=NON_BLOCKING
2018-02-14 05:58:36.384 [ 1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=StopCapture,handler=0x13311c8,policy=NON_BLOCKING
2018-02-14 05:58:36.384 [ 1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=DeleteAlert,handler=0x1333548,policy=NON_BLOCKING
2018-02-14 05:58:36.384 [ 1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=SetAlert,handler=0x1333548,policy=NON_BLOCKING
2018-02-14 05:58:36.384 [ 1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=SetEndpoint,handler=0x1392970,policy=NON_BLOCKING
2018-02-14 05:58:36.384 [ 1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=ResetUserInactivity,handler=0x1330fa4,policy=NON_BLOCKING
2018-02-14 05:58:36.384 [ 1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=AdjustVolume,handler=0x1374e78,policy=NON_BLOCKING
2018-02-14 05:58:36.384 [ 1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetMute,handler=0x1374e78,policy=NON_BLOCKING
2018-02-14 05:58:36.384 [ 1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetVolume,handler=0x1374e78,policy=NON_BLOCKING
2018-02-14 05:58:36.384 [ 1] 9 TemplateRuntime:getConfiguration
2018-02-14 05:58:36.384 [ 1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=TemplateRuntime,name=RenderPlayerInfo,handler=0x13748a0,policy=NON_BLOCKING
2018-02-14 05:58:36.384 [ 1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=TemplateRuntime,name=RenderTemplate,handler=0x13748a0,policy=NON_BLOCKING
2018-02-14 05:58:39.912 [ 4] 0 HttpPost:doPostSucceeded:code=200
2018-02-14 05:58:39.912 [ 4] 0 AuthDelegate:handleLwaResponseSucceeded:expiresInSeconds=3600
2018-02-14 05:58:39.912 [ 4] 0 AuthDelegate:onAuthStateChangeCalled:state=1,error=0
2018-02-14 05:58:39.913 [ 1] 0 MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=PENDING
2018-02-14 05:58:39.913 [ 1] 0 HTTP2StreamPool:getStream:streamId=1,numAcquiredStreams=1
2018-02-14 05:58:39.914 [ 3] 1 AlertsCapabilityAgent:executeOnConnectionStatusChanged:status=PENDING,reason=ACL_CLIENT_REQUEST
establishConnection
HTTP2Transport isStopping0.
2018-02-14 05:58:39.916 [ 6] 9 HTTP2Transport:HTTP2Transport:isStopping=false
downchannelResponseCode 0.
2018-02-14 05:58:39.916 [ 6] 9 HTTP2Transport:downchannelResponseCode:==0
wait(WAIT_FOR_ACTIVITY_TIMEOUT, &numTransfersUpdated result0.
2018-02-14 05:58:39.916 [ 6] 9 HTTP2Transport:wait(WAIT_FOR_ACTIVITY_TIMEOUT, &numTransfersUpdated:result=0
2018-02-14 05:58:39.917 [ 6] 0 HTTP2StreamPool:releaseStream:streamId=1,numAcquiredStreams=0
2018-02-14 05:58:39.917 [ 6] 0 HTTP2StreamPool:getStream:streamId=3,numAcquiredStreams=1
2018-02-14 05:58:39.914 [ 5] 9 PostConnectSynchronize:Entering postConnectLoop thread
2018-02-14 05:58:39.918 [ 6] 9 HTTP2Transport:setupDownchannelStream:result=
HTTP2Transport isStopping0.
2018-02-14 05:58:39.918 [ 6] 9 HTTP2Transport:HTTP2Transport:isStopping=false
2018-02-14 05:58:39.918 [ 6] E HTTP2Transport:networkLoopRetryingToConnect:reason=establishConnectionFailed,retryCount=0,retryBackoff=358
2018-02-14 05:58:39.918 [ 7] 9 SpeakerManager:provideStateCalled
2018-02-14 05:58:39.918 [ 7] 9 SpeechSynthesizer:provideState:token=1
2018-02-14 05:58:39.919 [ 7] 0 AudioPlayer:provideState:stateRequestToken=1
2018-02-14 05:58:39.919 [ 8] 9 SpeakerManager:executeProvideStateCalled
2018-02-14 05:58:39.919 [ 8] E SpeakerManager:readFileVolume volumeValue:line=50
2018-02-14 05:58:39.919 [ 8] E SpeakerManager:readFileVolume volumeValue3:volumeValue=5
2018-02-14 05:58:39.919 [ 8] E SpeakerManager:executeProvideStateCalled :settings.volume=5
2018-02-14 05:58:39.919 [ 8] 9 MediaPlayer:getSpeakerSettingsCalled
2018-02-14 05:58:39.922 [ 9] 0 SpeechSynthesizer:executeProvideState:stateRequestToken=1
2018-02-14 05:58:39.922 [ 9] 0 ContextManager:updateStateLocked:action=updatedState,state={"token":"","offsetInMilliseconds":0,"playerActivity":"FINISHED"},namespace=SpeechSynthesizer,name=SpeechState
2018-02-14 05:58:39.922 [ a] 0 AudioPlayer:executeProvideState:sendToken=true,stateRequestToken=1
2018-02-14 05:58:39.923 [ a] 0 ContextManager:updateStateLocked:action=updatedState,state={"token":"","offsetInMilliseconds":0,"playerActivity":"IDLE"},namespace=AudioPlayer,name=PlaybackState
2018-02-14 05:58:39.923 [ b] 0 ContextManager:updateStateLocked:action=updatedState,state={"wakeword" : ""},namespace=SpeechRecognizer,name=RecognizerState
2018-02-14 05:58:39.923 [ 2] 9 MediaPlayer:handleGetSpeakerSettingsCalled
2018-02-14 05:58:39.923 [ 2] 9 MediaPlayer:handleGetSpeakerSettings :m_pipeline.volume=0x1300138
2018-02-14 05:58:39.923 [ 2] 9 MediaPlayer:handleGetSpeakerSettings:change_volume=-1
2018-02-14 05:58:39.924 [ 2] E MediaPlayer:readFileVolume volumeValue:line=50
2018-02-14 05:58:39.924 [ 2] E MediaPlayer:readFileVolume volumeValue3:volumeValue=
2018-02-14 05:58:39.924 [ 2] 9 MediaPlayer:handleGetSpeakerSettings:avsVolume=60
2018-02-14 05:58:39.924 [ 8] 9 MediaPlayer:getSpeakerSettingsCalled
2018-02-14 05:58:39.924 [ 2] 9 MediaPlayer:handleGetSpeakerSettingsCalled
2018-02-14 05:58:39.924 [ 2] 9 MediaPlayer:handleGetSpeakerSettings :m_pipeline.volume=0x13004c8
2018-02-14 05:58:39.924 [ 2] 9 MediaPlayer:handleGetSpeakerSettings:change_volume=-1
2018-02-14 05:58:39.924 [ 2] E MediaPlayer:readFileVolume volumeValue:line=50
2018-02-14 05:58:39.924 [ 2] E MediaPlayer:readFileVolume volumeValue3:volumeValue=
2018-02-14 05:58:39.924 [ 2] 9 MediaPlayer:handleGetSpeakerSettings:avsVolume=60
2018-02-14 05:58:39.924 [ 8] 9 SpeakerManager:validateSpeakerSettingsConsistencyResult:consistent=true
2018-02-14 05:58:39.925 [ 8] 9 SpeakerManager:global_volume volume-:volume2-=60
#############################

Connecting...
#############################

2018-02-14 05:58:40.257 [ 8] 9 SpeakerManager:validateSpeakerSettings:volume=60,mute=false
2018-02-14 05:58:40.257 [ 8] 0 ContextManager:updateStateLocked:action=updatedState,state={"volume":60,"muted":false},namespace=Speaker,name=VolumeState
2018-02-14 05:58:40.257 [ 7] 0 ContextManager:buildContextSuccessful:context={"context":[{"header":{"namespace":"Speaker","name":"VolumeState"},"payload":{"volume":60,"muted":false}},{"header":{"namespace":"SpeechSynthesizer","name":"SpeechState"},"payload":{"token":"","offsetInMilliseconds":0,"playerActivity":"FINISHED"}},{"header":{"namespace":"AudioPlayer","name":"PlaybackState"},"payload":{"token":"","offsetInMilliseconds":0,"playerActivity":"IDLE"}},{"header":{"namespace":"SpeechRecognizer","name":"RecognizerState"},"payload":{"wakeword":""}},{"header":{"namespace":"Alerts","name":"AlertsState"},"payload":{"allAlerts":[],"activeAlerts":[]}}]}
2018-02-14 05:58:40.258 [ 7] 0 EventBuilder:buildJsonEventString:messageId=c245200e-cf04-4d4f-a87c-2a6d296d0528,namespace=System,name=SynchronizeState
2018-02-14 05:58:40.258 [ 7] 0 PostConnectSynchronize:onContextAvailable : Send PostConnectMessage to transport
2018-02-14 05:58:40.258 [ 7] 9 HTTP2Transport:enqueueRequest
establishConnection
HTTP2Transport isStopping0.
2018-02-14 05:58:40.276 [ 6] 9 HTTP2Transport:HTTP2Transport:isStopping=false
downchannelResponseCode 0.
2018-02-14 05:58:40.276 [ 6] 9 HTTP2Transport:downchannelResponseCode:==0
wait(WAIT_FOR_ACTIVITY_TIMEOUT, &numTransfersUpdated result0.
2018-02-14 05:58:40.276 [ 6] 9 HTTP2Transport:wait(WAIT_FOR_ACTIVITY_TIMEOUT, &numTransfersUpdated:result=0
2018-02-14 05:58:40.276 [ 6] 0 HTTP2StreamPool:releaseStream:streamId=3,numAcquiredStreams=0
2018-02-14 05:58:40.276 [ 6] 0 HTTP2StreamPool:getStream:streamId=5,numAcquiredStreams=1
2018-02-14 05:58:40.277 [ 6] 9 HTTP2Transport:setupDownchannelStream:result=
HTTP2Transport isStopping0.
2018-02-14 05:58:40.277 [ 6] 9 HTTP2Transport:HTTP2Transport:isStopping=false
2018-02-14 05:58:40.277 [ 6] E HTTP2Transport:networkLoopRetryingToConnect:reason=establishConnectionFailed,retryCount=1,retryBackoff=1097
establishConnection
HTTP2Transport isStopping0.
2018-02-14 05:58:41.374 [ 6] 9 HTTP2Transport:HTTP2Transport:isStopping=false
downchannelResponseCode 0.
2018-02-14 05:58:41.374 [ 6] 9 HTTP2Transport:downchannelResponseCode:==0
wait(WAIT_FOR_ACTIVITY_TIMEOUT, &numTransfersUpdated result0.
2018-02-14 05:58:41.374 [ 6] 9 HTTP2Transport:wait(WAIT_FOR_ACTIVITY_TIMEOUT, &numTransfersUpdated:result=0
2018-02-14 05:58:41.374 [ 6] 0 HTTP2StreamPool:releaseStream:streamId=5,numAcquiredStreams=0
2018-02-14 05:58:41.374 [ 6] 0 HTTP2StreamPool:getStream:streamId=7,numAcquiredStreams=1
2018-02-14 05:58:41.375 [ 6] 9 HTTP2Transport:setupDownchannelStream:result=
HTTP2Transport isStopping0.
2018-02-14 05:58:41.375 [ 6] 9 HTTP2Transport:HTTP2Transport:isStopping=false
2018-02-14 05:58:41.375 [ 6] E HTTP2Transport:networkLoopRetryingToConnect:reason=establishConnectionFailed,retryCount=2,retryBackoff=4319
establishConnection
HTTP2Transport isStopping0.
2018-02-14 05:58:45.694 [ 6] 9 HTTP2Transport:HTTP2Transport:isStopping=false
downchannelResponseCode 0.
2018-02-14 05:58:45.694 [ 6] 9 HTTP2Transport:downchannelResponseCode:==0
wait(WAIT_FOR_ACTIVITY_TIMEOUT, &numTransfersUpdated result0.
2018-02-14 05:58:45.694 [ 6] 9 HTTP2Transport:wait(WAIT_FOR_ACTIVITY_TIMEOUT, &numTransfersUpdated:result=0
2018-02-14 05:58:45.694 [ 6] 0 HTTP2StreamPool:releaseStream:streamId=7,numAcquiredStreams=0
2018-02-14 05:58:45.695 [ 6] 0 HTTP2StreamPool:getStream:streamId=9,numAcquiredStreams=1
2018-02-14 05:58:45.695 [ 6] 9 HTTP2Transport:setupDownchannelStream:result=
HTTP2Transport isStopping0.
2018-02-14 05:58:45.695 [ 6] 9 HTTP2Transport:HTTP2Transport:isStopping=false
2018-02-14 05:58:45.695 [ 6] E HTTP2Transport:networkLoopRetryingToConnect:reason=establishConnectionFailed,retryCount=3,retryBackoff=5382
establishConnection
HTTP2Transport isStopping0.
2018-02-14 05:58:51.077 [ 6] 9 HTTP2Transport:HTTP2Transport:isStopping=false
downchannelResponseCode 0.
2018-02-14 05:58:51.077 [ 6] 9 HTTP2Transport:downchannelResponseCode:==0
wait(WAIT_FOR_ACTIVITY_TIMEOUT, &numTransfersUpdated result0.
2018-02-14 05:58:51.077 [ 6] 9 HTTP2Transport:wait(WAIT_FOR_ACTIVITY_TIMEOUT, &numTransfersUpdated:result=0
2018-02-14 05:58:51.078 [ 6] 0 HTTP2StreamPool:releaseStream:streamId=9,numAcquiredStreams=0
2018-02-14 05:58:51.078 [ 6] 0 HTTP2StreamPool:getStream:streamId=11,numAcquiredStreams=1
2018-02-14 05:58:51.078 [ 6] 9 HTTP2Transport:setupDownchannelStream:result=
HTTP2Transport isStopping0.
2018-02-14 05:58:51.078 [ 6] 9 HTTP2Transport:HTTP2Transport:isStopping=false
2018-02-14 05:58:51.078 [ 6] E HTTP2Transport:networkLoopRetryingToConnect:reason=establishConnectionFailed,retryCount=4,retryBackoff=13478

**Comment by sanjayrd** [comment] 2018-03-05 21:20
Closing as this is a duplicate of https://github.com/alexa/avs-device-sdk/issues/541

**Closed by sanjayrd** 2018-03-05 21:20 UTC
