### ISSUE TITLE
Alexa build sdk source: problem gstreamer-1.0

### ISSUE THREAD

**Issue by echcon** [alexa/avs-device-sdk#462] opened 2018-01-21 17:13 UTC
**IMPORTANT**: I have some error when i try to build alexa voice service.

## Briefly summarize my issue:
_https://github.com/alexa/avs-device-sdk/wiki/macOS-Quick-Start-Guide#2-build-the-sdk_

## What is the expected behavior?
_Creating the build directory for the AlexaClientSDK with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.29.2") 
-- Checking for modules 'gstreamer-1.0>=1.8;gstreamer-app-1.0>=1.8'
--   No package 'gstreamer-1.0' found
--   No package 'gstreamer-app-1.0' found
CMake Error at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  build/cmake/MediaPlayer.cmake:14 (pkg_check_modules)
  build/BuildDefaults.cmake:28 (include)
  CMakeLists.txt:7 (include)_

## What behavior are you observing?
I try to check & install version 1.0 but any things do not change: brew install gstreamer

## Provide the steps to reproduce the issue, if applicable:
- Step 2: build sdk

## Tell us about your environment:
Version of the AVS Device SDK: 1.4.0
### Tell us what hardware you're using:
- [Macbook pro 2016 ] Desktop / Laptop
### Tell us about your OS (Type & version):
- [10.13.2 ] MacOS

**Comment by cldy309** [comment] 2018-01-22 11:25
@echcon hi  i have same issue~~ have you ever fix this?

----------log----

-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Creating the build directory for the AlexaClientSDK with build type: DEBUG
WARNING: Logging of sensitive information enabled!
Creating AlexaClientSDK with keyword detector type: Sensory
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28")
-- Checking for modules 'gstreamer-1.0>=1.8;gstreamer-app-1.0>=1.8'
--
--
CMake Error at /usr/share/cmake-3.6/Modules/FindPkgConfig.cmake:424 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindPkgConfig.cmake:597 (_pkg_check_modules_internal)
  build/cmake/MediaPlayer.cmake:14 (pkg_check_modules)
  build/BuildDefaults.cmake:28 (include)
  CMakeLists.txt:7 (include)


-- Configuring incomplete, errors occurred!

**Comment by bandkenamazoncom** [comment] 2018-01-22 17:59
Ddi you install gstreamer (brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-libav)?

**Comment by echcon** [comment] 2018-01-23 05:51
Thanks for your comment.  I have installed gstreamer by brew command and version is 1.8. You can see on my issue.

**Comment by bandkenamazoncom** [comment] 2018-01-23 16:59
Can you see if this directory exists?  
/usr/local/Cellar/gstreamer

Can you paste the contents of that directory?

**Comment by peifeng000** [comment] 2018-01-29 08:58
@echcon I have met the same issue. My OS is ubuntu 14.04. Could you please tell me how you fix it?

**Comment by frozenberg** [comment] 2018-01-29 21:52
Hi @peifeng000,

Have you installed gstreamer and all its plugins? The command is brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-libav

Fede

**Comment by peifeng000** [comment] 2018-01-30 10:35
Hi @frozenberg

Thanks for your reply.

I followed the instructions on https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide.
My environment is ubuntu 14.04.
I used following command to install gstreamer:

sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good libgstreamer-plugins-good1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-libav

And the log is like this:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
gstreamer1.0-plugins-good is already the newest version.
libgstreamer-plugins-base1.0-dev is already the newest version.
libgstreamer-plugins-good1.0-dev is already the newest version.
libgstreamer1.0-dev is already the newest version.
gstreamer1.0-libav is already the newest version.
libgstreamer-plugins-bad1.0-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.



So I think I have installed gstreamer. But this issue still occurs.

-- checking for modules 'gstreamer-1.0>=1.8;gstreamer-app-1.0>=1.8'
--   package 'gstreamer-1.0>=1.8' not found
--   package 'gstreamer-app-1.0>=1.8' not found

Please help me.

**Comment by frozenberg** [comment] 2018-01-30 17:20
Ok, thanks for the reply. It looks like gstreamer is being installed somewhere that the SDK isn't looking.

Can you see if this directory exists?
/usr/local/Cellar/gstreamer

Can you paste the contents of that directory if it does exist?

Fede

**Comment by peifeng000** [comment] 2018-01-31 02:22
Thanks for your information.

There is no such directory named "Cellar" in "/usr/local".

peifeng@ubuntu:/usr/local$ ls
bin  etc  games  include  lib  man  sbin  share  src

**Comment by frozenberg** [comment] 2018-01-31 17:25
@peifeng000 

Sorry, somehow it went over my head that you are on ubuntu. The Cellar directory shouldn't exist there. Instead, can you show me the contents of /usr/local/lib ?

Fede

**Comment by peifeng000** [comment] 2018-02-01 01:33
Hi @frozenberg

Here are the contents:

peifeng@ubuntu:/usr/local/lib$ ls
libcurl.a     libcurl.so.4.4.0  libnghttp2.so.14       python2.7
libcurl.la    libnghttp2.a      libnghttp2.so.14.15.1  python3.4
libcurl.so    libnghttp2.la     ocaml                  site_ruby
libcurl.so.4  libnghttp2.so     pkgconfig

**Comment by frozenberg** [comment] 2018-02-01 19:59
Ok, just to make sure that gstreamer is correctly installed:

Do you have any file that looks like this:

`/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-plugins-base-1.0.pc`

you can also try `find /usr/lib -name "*gstreamer*"`

**Comment by peifeng000** [comment] 2018-02-02 02:00
Yes, there does exist such file in /usr/lib/x86_64-linux-gnu/pkgconfig:

-rw-r--r--   1 root root   346 Nov 16  2016 gstreamer-plugins-bad-0.10.pc
-rw-r--r--   1 root root   338 Nov 16  2016 gstreamer-plugins-bad-1.0.pc
-rw-r--r--   1 root root   445 Mar 24  2017 gstreamer-plugins-base-0.10.pc
-rw-r--r--   1 root root   428 Mar 24  2017 gstreamer-plugins-base-1.0.pc
-rw-r--r--   1 root root   341 Mar 24  2017 gstreamer-plugins-good-1.0.pc


When I execute command: find /usr/lib -name "*gstreamer*"

peifeng@ubuntu:/usr/lib/x86_64-linux-gnu/pkgconfig$ find /usr/lib -name "*gstreamer*"
/usr/lib/ruby/vendor_ruby/1.9.1/x86_64-linux/gstreamer.so
/usr/lib/libgstreamermm_get_plugin_defs-0.10.so.2.0.1
/usr/lib/liquidsoap/1.1.1/gstreamer.liq
/usr/lib/liquidsoap/1.1.1/plugins/gstreamer.cmxs
/usr/lib/packagekit/pk-gstreamer-install
/usr/lib/libgstreamermm-0.10.a
/usr/lib/x86_64-linux-gnu/libgstreamer-0.10.so.0
/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.0.0/gstreamer.so
/usr/lib/x86_64-linux-gnu/cornucopia/modules/fsodevice/player_gstreamer.so
/usr/lib/x86_64-linux-gnu/qt5/plugins/phonon4qt5_backend/phonon_gstreamer.so
/usr/lib/x86_64-linux-gnu/libgstreamer-0.10.la
/usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so
/usr/lib/x86_64-linux-gnu/libgstreamer-0.10.a
/usr/lib/x86_64-linux-gnu/libgstreamer-0.10.so.0.30.0
/usr/lib/x86_64-linux-gnu/gstreamer-0.10
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-net-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-video-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-allocators-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-plugins-good-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-pbutils-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-riff-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-plugins-base-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-mpegts-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-cdda-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-sdp-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-vaapi-glx-1.2.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-rtsp-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-codecparsers-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-controller-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-egl-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-interfaces-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-insertbin-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-plugins-bad-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-audio-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-netbuffer-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-controller-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-codecparsers-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-dataprotocol-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-fft-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-vaapi-1.2.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-rtsp-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-rtp-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-sdp-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-base-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-app-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-plugins-base-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-check-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-vaapi-drm-1.2.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-base-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-pbutils-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-vaapi-x11-1.2.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-floatcast-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-tag-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-video-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-rtp-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-net-1.0.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-fft-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-basevideo-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-audio-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-plugins-bad-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-tag-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-app-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-check-0.10.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-riff-0.10.pc
/usr/lib/x86_64-linux-gnu/libgstreamer-0.10.so
/usr/lib/x86_64-linux-gnu/gstreamer-1.0
/usr/lib/x86_64-linux-gnu/gstreamer0.10
/usr/lib/x86_64-linux-gnu/gstreamer0.10/gstreamer-0.10
/usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
/usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0.204.0
/usr/lib/x86_64-linux-gnu/libcanberra-0.30/libcanberra-gstreamer.so
/usr/lib/x86_64-linux-gnu/gstreamer1.0
/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0
/usr/lib/x86_64-linux-gnu/qt4/plugins/phonon_backend/phonon_gstreamer.so
/usr/lib/haskell-packages/ghc/lib/gstreamer-0.12.1.2
/usr/lib/haskell-packages/ghc/lib/gstreamer-0.12.1.2/ghc-7.6.3/HSgstreamer-0.12.1.2.o
/usr/lib/haskell-packages/ghc/lib/gstreamer-0.12.1.2/ghc-7.6.3/libHSgstreamer-0.12.1.2_p.a
/usr/lib/haskell-packages/ghc/lib/gstreamer-0.12.1.2/ghc-7.6.3/libHSgstreamer-0.12.1.2.a
/usr/lib/mono/gac/gstreamer-sharp
/usr/lib/mono/gac/gstreamer-sharp/0.9.2.0__4956b48baf980190/gstreamer-sharp.dll
/usr/lib/mono/gac/gstreamer-sharp/0.9.2.0__4956b48baf980190/gstreamer-sharp.dll.config
/usr/lib/python2.7/dist-packages/deejayd/player/gstreamer.pyc
/usr/lib/python2.7/dist-packages/deejayd/player/gstreamer.py
/usr/lib/gstreamer-0.10
/usr/lib/pkgconfig/gstreamermm-0.10.pc
/usr/lib/pkgconfig/gstreamer-sharp-0.10.pc
/usr/lib/cli/gstreamer-sharp-0.9
/usr/lib/cli/gstreamer-sharp-0.9/libgstreamersharpglue-0.10.so
/usr/lib/cli/gstreamer-sharp-0.9/gstreamer-sharp.dll
/usr/lib/cli/gstreamer-sharp-0.9/gstreamer-sharp.dll.config
/usr/lib/monodoc/sources/gstreamer-sharp-docs.source
/usr/lib/monodoc/sources/gstreamer-sharp-docs.tree
/usr/lib/monodoc/sources/gstreamer-sharp-docs.zip
/usr/lib/libgstreamermm_get_plugin_defs-0.10.a
/usr/lib/gstreamer-1.0
/usr/lib/libgstreamermm-0.10.so
/usr/lib/ghc-doc/hoogle/gstreamer.txt
/usr/lib/ghc-doc/haddock/gstreamer-0.12.1.2
/usr/lib/ghc-doc/haddock/gstreamer-0.12.1.2/gstreamer.haddock
/usr/lib/libgstreamermm_get_plugin_defs-0.10.so.2
/usr/lib/gstreamermm-0.10
/usr/lib/gstreamermm-0.10/include/gstreamermmconfig.h
/usr/lib/gstreamermm-0.10/gen/m4/plugingen_gstreamermm.m4
/usr/lib/libgstreamermm-0.10.so.2.0.1
/usr/lib/libgstreamermm-0.10.so.2
/usr/lib/debug/usr/lib/ruby/vendor_ruby/1.9.1/x86_64-linux/gstreamer.so
/usr/lib/debug/usr/lib/libgstreamermm_get_plugin_defs-0.10.so.2.0.1
/usr/lib/debug/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.0.0/gstreamer.so
/usr/lib/debug/usr/lib/x86_64-linux-gnu/libcanberra-0.30/libcanberra-gstreamer.so
/usr/lib/debug/usr/lib/gstreamer-0.10
/usr/lib/debug/usr/lib/gstreamermm-0.10
/usr/lib/debug/usr/lib/libgstreamermm-0.10.so.2.0.1
/usr/lib/libgstreamermm_get_plugin_defs-0.10.so
/usr/lib/ocaml/gstreamer
/usr/lib/ocaml/gstreamer/gstreamer.cmxa
/usr/lib/ocaml/gstreamer/gstreamer.cmi
/usr/lib/ocaml/gstreamer/gstreamer.mli
/usr/lib/ocaml/gstreamer/gstreamer.cma
/usr/lib/ocaml/gstreamer/gstreamer.cmx
/usr/lib/ocaml/gstreamer/gstreamer.a
/usr/lib/ocaml/gstreamer/libgstreamer_stubs.a
/usr/lib/ocaml/stublibs/dllgstreamer_stubs.so

I found that there are two versions of gstreamer installed. They are 0.10 and 1.0.
Is this the root cause of this issue?

Thanks!

**Comment by mradulan** [comment] 2018-02-07 19:43
Hi @peifeng000 , what is the gstreamer version? you can check by running the command `gst-inspect-1.0 --version`.
also can you paste the contents of `echo $PATH`

**Comment by peifeng000** [comment] 2018-02-08 01:48
Hi @mradulan

Thanks for your reply.

Here are the information:

peifeng@ubuntu:~$ gst-inspect-1.0 --version

(gst-plugin-scanner:2675): GStreamer-WARNING **: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgsteglglessink.so': /usr/lib/x86_64-linux-gnu/libgstegl-1.0.so.0: undefined symbol: eglDestroyImageKHR
gst-inspect-1.0 version 1.2.4
GStreamer 1.2.4
https://launchpad.net/distros/ubuntu/+source/gstreamer1.0



peifeng@ubuntu:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

**Comment by mradulan** [comment] 2018-02-08 17:46
The gstreamer version for the SDK should be greater than 1.8. You have gstreamer 1.2.4 installed. Can you install gstreamer 1.10.4? That is the version which works properly.

**Comment by yoelrc88** [comment] 2018-02-15 20:34
Installing:
 `sudo apt-get  install libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-good` 
solved it for me

**Comment by celinval** [comment] 2018-02-16 21:19
Hi @peifeng000, were you able to install a newer version of gstreamer? Did it fix your problem?

**Comment by johnnyhuziqin** [comment] 2018-02-20 16:02
@echcon Sorry, it seem that your issue haven't resolved, am i correct? For I also have this issue, and my platform is MacBook too. 
I can assume that the streamer has been install, but the cmake can not find the *.pc which tell the compiler where the resources are.
in the file: MediaPlayer.cmake, there has a line:
`pkg_check_modules(GST REQUIRED gstreamer-1.0>=1.8 gstreamer-app-1.0>=1.8)`
this line causes the error, if I mask this line, cmake will pass, but still can not pass the next step, because the compiler can not find gstreamer.
as far as i know, if i tell pkg_check_modules how to find the corresponding *.pc files ,it should solved this problem. and I actually know the *.pc files are located at: 
`/usr/local/Cellar/gstreamer//1.12.4/lib/pkgconfig/gstreamer-1.0.pc`
But I still don't know how to tell cmake to look into this directory.
It would be great appreciated if someone could help or enlighten me, with many thanks.

**Comment by sandeepajesh** [comment] 2018-02-20 16:18
Hi @johnnyhuziqin , I was also had same problem. I resolved it by setting PKG_CONFIG_PATH.
With **pkg-config --cflags --libs gstreamer-1.0** you can check your default gstreamer path.

**Comment by peifeng000** [comment] 2018-02-23 12:01
Hi @mradulan & celinval 

Thanks for your reply!

How to install a newer version of gstreamer?
Can I use `sudo apt-get install`? Do I have to install a newer version of gstreamer from source?
How to uninstall the old version of gstreamer?

**Comment by johnnyhuziqin** [comment] 2018-02-23 12:38
@sandeepajesh Thank you very much for your help! I had fixed this error now.
here is what I did:
`$ export PKG_CONFIG_PATH="/usr/local/Cellar/gstreamer/1.12.4/lib/pkgconfig/:/usr/local/Cellar//gst-plugins-base/1.12.4_1/lib/pkgconfig/"
 cd ~/sdk-folder/sdk-build && cmake /Users/huziqin/sdk-folder/sdk-source/avs-device-sdk -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/Users/huziqin/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/Users/huziqin/sdk-folder/third-party/portaudio/include`
and the ouput is:
`Creating the build directory for the AlexaClientSDK with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Checking for modules 'gstreamer-1.0>=1.8;gstreamer-app-1.0>=1.8'
--   Found gstreamer-1.0, version 1.12.4
--   Found gstreamer-app-1.0, version 1.12.4
CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
.......
`

**Comment by sandeepajesh** [comment] 2018-02-23 15:52
Hi @peifeng000,

Here is how I did it on my ARM/Ubuntu 16.04. May be it can help you.

apt install git cmake  build-essential libasound2-dev python-dev python-pip libsqlite3-dev libfaad-dev libsoup2.4-dev libgcrypt20-dev doxygen  python-setuptools automake autoconf autopoint libtool bison gettext flex ntp bison libatlas-base-dev libpulse-dev libjpeg-dev libmad0-dev libmpg123-dev libmpg123-0 libmpeg2-4-dev libmp3lame-dev libwavpack-dev libmpcdec-dev flex ntp bison

export LD_LIBRARY_PATH=/usr/local/lib/
export BUILD=<Where you want your libs e.g:- /use/local/>

git clone git://anongit.freedesktop.org/git/gstreamer/gstreamer
cd gstreamer
./autogen.sh --prefix=$BUILD --disable-gtk-doc
cd ..

export PKG_CONFIG_PATH=$BUILD/lib/pkgconfig:$PKG_CONFIG_PATH
git clone git://anongit.freedesktop.org/git/gstreamer/gst-plugins-base
cd gst-plugins-base
./autogen.sh --prefix=$BUILD --disable-gtk-doc
cd ..

git clone git://anongit.freedesktop.org/git/gstreamer/gst-plugins-good
cd gst-plugins-good
./autogen.sh --prefix=$BUILD --disable-gtk-doc
cd ..

git clone git://anongit.freedesktop.org/git/gstreamer/gst-plugins-bad
cd gst-plugins-bad
./autogen.sh --prefix=$BUILD --disable-gtk-doc
cd ..

git clone git://anongit.freedesktop.org/git/gstreamer/gst-plugins-ugly
cd gst-plugins-ugly
./autogen.sh --prefix=$BUILD --disable-gtk-doc
cd ..

git clone git://anongit.freedesktop.org/git/gstreamer/gst-libav
cd gst-libav
./autogen.sh --prefix=$BUILD --disable-gtk-doc

All the best.

Thx-
Sandy

**Comment by peifeng000** [comment] 2018-02-24 11:32
Hi @mradulan @frozenberg @sandeepajesh 

Thanks for all your help very much!

I have solved this issue by installing a newer version of gstreamer.

**Comment by kencecka** [comment] 2018-02-27 23:19
Glad to hear you have it working.  I'll go ahead and close this issue.  Please reopen if you have any further problems.

**Closed by kencecka** 2018-02-27 23:19 UTC

**Comment by ivinaymk** [comment] 2018-05-12 16:11
I could solve this issue on Mac with following commands:
Install the latest gstreamer version with the following command.
`brew link gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad
`
Relink the installed packages with following command
```
brew link --overwrite gstreamer
brew link --overwrite gst-plugins-base
brew link --overwrite gst-plugins-good
brew link --overwrite gst-plugins-bad
```
After this issuing sdk build command - goes on smoothly.

**Comment by avp24** [comment] 2018-09-20 06:04
Hi @sandeepajesh I am trying to cross compile gstreamer and its plugins for ARM and following the same steps as you mentioned but I am facing errors while compiling gstreamer.
Error is like : 
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: cannot find -lgobject-2.0
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: cannot find -lgmodule-2.0
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: cannot find -lglib-2.0
collect2: error: ld returned 1 exit status
Makefile:1006: recipe for target 'libgstreamer-1.0.la' failed

Can you please help me to solve this problem.
Thanks.

**Comment by ChrisIsKing** [comment] 2018-09-22 00:08
@peifeng000 How did you get to install the latest gstreamer on ubuntu 14.04?

**Comment by tjyuanxi** [comment] 2019-04-04 09:00
@johnnyhuziqin @echcon 
I have the question too.
I complier alexa media player in ubuntu for arm .
Now I have had all gstreamer lib, but i do not know how join them to media player 

My command:
source /opt/oecore-x86_64/environment-setup-cortexa7hf-neon-poky-linux-gnueabi
cmake ../MediaPlayer -DGSTREAMER_MEDIA_PLAYER=ON -DCMAKE_BUILD_TYPE=Debug -DARCH=arm
Error:
CMake Error at /opt/oecore-x86_64/sysroots/x86_64-oesdk-linux/usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /opt/oecore-x86_64/sysroots/x86_64-oesdk-linux/usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  /home/jiantang/blackwarrior/avs-device-sdk-master/build/cmake/MediaPlayer.cmake:14 (pkg_check_modules)
  /home/jiantang/blackwarrior/avs-device-sdk-master/build/BuildDefaults.cmake:25 (include)
  GStreamerMediaPlayer/CMakeLists.txt:4 (include)


-- Configuring incomplete, errors occurred!
See also "/home/jiantang/blackwarrior/avs-device-sdk-master/MediaPlayer_build/CMakeFiles/CMakeOutput.log".

Help me, thks

**Comment by tjyuanxi** [comment] 2019-04-09 06:05
I have set export PKG_CONFIG_PATH=/home/jiantang/blackwarrior/avs/gstplugin/lib/pkgconfig, but  this issue still occurs.
