### ISSUE TITLE
Build Failed due to broken packages 

### ISSUE THREAD

**Issue by Vaishnavikumara** [alexa/avs-device-sdk#1412] opened 2019-07-01 12:41 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

The following packages have unmet dependencies:
 libcurl4-openssl-dev : Conflicts: libssl1.0-dev but 1.0.2q-2 is to be installed
E: Unable to correct problems, you have held broken packages.

## What is the expected behavior?

The Build should be succesful

## Provide the steps to reproduce the issue, if applicable:

Followed the Guide lines provided in https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:

- [ ] Raspberry Pi 

### Tell us about your OS (Type & version):

- [ ] Raspbian Buster

**Comment by scotthea-amazon** [comment] 2019-07-01 15:32
Hello Vaishnavikumara,

This appears to be a duplicate of [issue 1405](https://github.com/alexa/avs-device-sdk/issues/1405).

I will resolve this issue as a duplicate in favor of the existing issue.

If this has been closed in error, feel free to re-open it.

Thank you,
-SWH

**Closed by scotthea-amazon** 2019-07-01 15:32 UTC
