### ISSUE TITLE
AuthServer.py cannot connect to voice service

### ISSUE THREAD

**Issue by scurdy** [alexa/avs-device-sdk#384] opened 2017-12-11 10:29 UTC
Alexa device SDK version 1.3 master
platform: macosx 10.13.2
hw: mac book pro Mid 2015, 2,5GHz intel Core i7

Sum up:
When trying to refresh token running python script AuthServer.py, python crashes with following trace:
Traceback (most recent call last):
  File "AuthServer/AuthServer.py", line 194, in <module>
    app.run(host='127.0.0.1',port='3000')
  File "/Users/gteudemo/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/Users/gteudemo/Library/Python/2.7/lib/python/site-packages/werkzeug/serving.py", line 733, in run_simple
    raise TypeError('port must be an integer')
**TypeError: port must be an integer**

expected result:
being able to refresh token

quick fix:
line 194
```
app.run(host='127.0.0.1',port='3000') ->app.run(host='127.0.0.1',port=3000)
```

Since AuthServer.py is auto-generated, it is a pity to have to modify it each time I make a clean build.

**Comment by scotthea-amazon** [comment] 2017-12-11 17:41
Hello scurdy,

Thank you very much for bringing this to our attention!  I just tried to reproduce the problem you described and have not been able to.  What version of Werkzeung are you running?  You should be able to find it via:

`pip freeze | grep Werkzeug`
 
Thank you,
-SWH

**Comment by Scoobadood** [comment] 2017-12-12 06:38
Plus one for this problem:
Python version 2.7.10 (default on OSX High Sierra clean install)
Werkzeug==0.13

**Comment by scurdy** [comment] 2017-12-12 09:45
yes the same here.
Werkzeug==0.13

**Comment by sanjayrd** [comment] 2017-12-12 22:55
Hi all,

Thank you for the information. We will investigate the issue and see if we can provide a fix soon.

Thanks,
Sanjay

**Comment by apowers313** [comment] 2017-12-12 23:51
Duplicated here, same fix works.

**Comment by hivie7510** [comment] 2018-01-01 17:03
I didn’t see the fix in the thread.  I am having the same issue, could you clarify please?

**Comment by apowers313** [comment] 2018-01-01 20:18
@hivie7510 Change this line:

``` js
app.run(host='127.0.0.1',port='3000')
```

to this (remove the quotes from around 3000):

``` js
app.run(host='127.0.0.1',port=3000)
```

**Comment by kclchan** [comment] 2018-01-02 23:11
Thanks to all!  We will be incorporating this fix in our next software release.

**Comment by hivie7510** [comment] 2018-01-02 23:17
I have gotten past the integer issue, but i am still not getting an open server to connect to at local host:3000

**Comment by kclchan** [comment] 2018-01-02 23:41
Hi @hivie7510, are you having problem with running "python AuthServer/AuthServer.py"?  Or are you having problem connecting to http://localhost:3000 with your browser?

Also, please make sure you have entered the Allowed Origins and Allowed Return URLs as described here:
https://github.com/alexa/alexa-avs-sample-app/wiki/Create-Security-Profile

**Comment by hivie7510** [comment] 2018-01-03 00:36
I checked the URLs for the return and they are correct.  What I am not seeing is a message from the run statement that there is a server ready to receive requests.  I did test my flask install by using a sample py file from flask and a server opens without issue.  This is just the sample app from the links.  I can post the whole config file if that helps.

**Comment by kclchan** [comment] 2018-01-03 01:39
Could you copy&paste the output after you run "python AuthServer/AuthServer.py"?

**Comment by hivie7510** [comment] 2018-01-03 03:38
I get the standard error message when a 200 is not received, but I expected to see something saying that the server is running so I can hit the localhost:3000 url.  Here is the output from the command line:

The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.

That is on line 121 when the response from the post to the LWA url.

What I am not understanding is why the server won't start.  

Here is the configs that I have:
 {
    "authDelegate":{
        // The Client Secret of the Product from developer.amazon.com
        "clientSecret":"REMOVED",
        // Unique device serial number. e.g. 123456
        "deviceSerialNumber":"123456",
        // Refresh Token populated by running AuthServer.py
        "refreshToken":"",
        // The Client ID of the Product from developer.amazon.com
        "clientId":"amzn1.application-oa2-client.{REMOVED}}",
        // Product ID from developer.amazon.com
        "productId":"Sample_App"
     },
   "alertsCapabilityAgent":{
        "databaseFilePath":"/Users/ME/sdk-folder/application-necessities/alerts.db"
   },
   "settings":{
        "databaseFilePath":"/Users/ME/sdk-folder/application-necessities/settings.db",
        "defaultAVSClientSettings":{
            "locale":"en-US"
        }
   },
   "certifiedSender":{
        "databaseFilePath":"/Users/ME/sdk-folder/application-necessities/certifiedSender.db"
   }
 }

**Comment by hivie7510** [comment] 2018-01-03 03:48
if it helps, here is the post data that is sent:
client_secret=bd644e9mysecret&grant_type=refresh_token&client_id=amzn1.application-oa2-client.myclientid&refresh_token=rtest

**Comment by hivie7510** [comment] 2018-01-03 04:41
Ok, I was able to make it work after a few changes.

I had to change the redirecturi to https:
redirectUri = 'https://127.0.0.1:3000/authresponse'

I also had to change the app run to use ad hoc ssl:
app.run(host='127.0.0.1',port=3000,ssl_context='adhoc')

**Comment by kclchan** [comment] 2018-01-03 18:08
Hi @hivie7510, I am happy to hear you finally got AuthServer.py to work for you.

But just curious, when I run Authserver.py, I also got this error message:
"The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file."

But I also see this message right after:
"* Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)"

And when I open a browser and navigate to http://localhost:3000, I see this:
"127.0.0.1 - - [03/Jan/2018 17:32:36] "GET / HTTP/1.1" 302 -"

So I am just wondering if you see the same?

**Closed** 2018-01-29 21:47 UTC
Labels: Authorization, bug
