### ISSUE TITLE
"Alexa, sing me a song" command not working

### ISSUE THREAD

**Issue by prateek-web** [alexa/avs-device-sdk#1851] opened 2020-12-21 06:55 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
 When I invoke alexa using command "Alexa, sing me a song", it starts playing song for 1-2 sec, then it stops and becomes unresponsive for ~10 sec.

## What is the expected behavior?
It should complete the song that is being played, when user invokes alexa using command "Alexa, sing me a song".

## What behavior are you observing?
When I invoke alexa using command "Alexa, sing me a song", it starts playing song for 1-2 sec, then it stops and becomes unresponsive for ~10 sec.

## Provide the steps to reproduce the issue, if applicable:
1. Invoke alexa using command - "Alexa, sing me a song"
2. Wait for 1-2 sec till it start playing.

## Tell us about your environment:
AVS SDK Version 1.18.0 Cross Compiled to run on below Hardware.
PulseAudio
Bluetooth
Spotify Adapter integrated
Alexa-communication integrated

### What version of the AVS Device SDK are you using?
AVS-DEVICE-SDK-1.18

### Tell us what hardware you're using:
artik305s (samsung's SOC) 1 gb ram, 4 gb emmc

### Tell us about your OS (Type & version):
linux (ubuntu)

**Comment by prateek-web** [comment] 2020-12-21 06:57
[alexa(1).log](https://github.com/alexa/avs-device-sdk/files/5722765/alexa.1.log)
DEBUG9 Logs of the issue.

**Comment by womw** [comment] 2020-12-22 17:12
Hi @prateek-web thanks for posting.

Looking into this issue I was able to reproduce a crash on 1.18 of our SampleApp with sing me a song. We are looking further into this issue.

**Comment by womw** [comment] 2020-12-22 21:29
Hi @prateek-web 
This is due to a known issue with the guiRenderer.cpp
This bug was fixed in version 1.21 of the SDK. Please update to a newer version of the SDK or update the guiRenderer.cpp file in your source code.

**Closed by womw** 2020-12-22 21:29 UTC
Labels: Under investigation
