### ISSUE TITLE
Can not set alexa audio output to Analog.

### ISSUE THREAD

**Issue by LotrForTheWin** [alexa/avs-device-sdk#1833] opened 2020-11-18 17:20 UTC
## Briefly summarize your issue:
After installing sample SDK, as in previous issues, I can not hear alexa through headphones.
Despite many found solutions audio is still set to HDMI output.

## What is the expected behavior?
Audio should be heard through headphones (mini jack output) 
Or, if possible, it would be good if I can set USB as default audio output.

## What behavior are you observing?

Standard for this issue:
Uppon starting sample app, and providing simple command : "Alexa what is the time"
the SDK goes from IDLE -> listening -> thinking -> speaking -> idle
But NO audio is heard.
When I connected my raspberry to TV, audio is heard through TV. 

## Provide the steps to reproduce the issue, if applicable:

run sample app

## Tell us about your environment:
My raspberry got connected:
USB Keyboard
USB mouse
USB headphones (mic included) Dell Jabra Uc VOICE 550a MS
Jack headphones (mic included)
Audio output is set to Analog
Audio input is set to Dell jabra UC VOICE 550a MS

## Used solutions (did something wrong, or they do not solve the issue)
*1* 
I checked in right upper corner if my output is set to analog
*did not work*

*2*
I did set in "raspi-config" audio output to headphones
*did not work neither*

*3*
I did try to change values in .asoundrc file, but without a success

*4*
So I have already tried:
 gst-launch-1.0 -m audiotestsrc ! alsasink
And audio is heard in headphones
As in found solutions I switched lines in MediaPlayer.cpp for following
 
    // # Orginal
    //ConfigurationNode::getRoot()[MEDIAPLAYER_CONFIGURATION_ROOT_KEY].getString(
        //MEDIAPLAYER_AUDIO_SINK_KEY, &audioSinkElement, "autoaudiosink");
    //m_pipeline.audioSink = gst_element_factory_make(audioSinkElement.c_str(), "audio_sink");
    
    // #1
    //m_pipeline.audioSink = gst_element_factory_make("alsasink", "audio_sink");
    
    // #2
    ConfigurationNode::getRoot()[MEDIAPLAYER_CONFIGURATION_ROOT_KEY].getString(
        MEDIAPLAYER_AUDIO_SINK_KEY, &audioSinkElement, "alsasink");

    m_pipeline.audioSink = gst_element_factory_make(audioSinkElement.c_str(), "audio_sink");
    // #2 end

After each swap I compiled:  sudo bash setup.sh config.json [-s 1234]
and run sample app: sudo bash startsample.sh 
*Did not work*

### What version of the AVS Device SDK are you using?
      1.2.1

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
-[X] Raspbian buster (10)

**Comment by caleighatamazon** [comment] 2020-11-19 20:57
Hi @LotrForTheWin , have you tried running the setup script without `sudo`? That should not be necessary. You will have to delete your workspace before re-running the script without `sudo`.

What was the path to the `.asound.rc` file that you mentioned you modified in "Used solutions" 3?

If you followed our raspberry pi guide (https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html), it tells you to modify `~/.asound.rc`. But if you're using `sudo` to build and run the app, it might be looking for the root user's sound configuration.

Please try deleting your workspace and re-running the setup script without `sudo`. Or, if you need to keep using `sudo` for some other reason (not recommended), then check out #1544 for more troubleshooting tips.

**Comment by LotrForTheWin** [comment] 2020-11-20 08:59
Hello, 
Just a quick response, 
I was using this tutorial:
https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/build-the-avs-device-sdk.html
Is it obsolete? In build SDK section, sudo is proposed to install the SDK.

_What was the path to the .asound.rc file that you mentioned you modified in "Used solutions" 3?_
It was in /home/pi

_If you followed our raspberry pi guide (https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html), it tells you to modify ~/.asound.rc. But if you're using sudo to build and run the app, it might be looking for the root user's sound configuration._
I thought so, but I'm new to raspberry PI, and tried to follow the tutorial step by step. 


I have also find other solution (working but not desire)
In boot/congi.txt I have comment out the "dtparm=audio=on" and reboot the raspberry. Now when I start alexa sdk I can hear music with my USB headphones.

Will try to reinstall the Alexa, and give more feedback ;)

**Comment by caleighatamazon** [comment] 2020-11-20 17:30
Hi @LotrForTheWin , looks like you might have found a bug in our documentation! I'll file a ticket to fix that up.

Let me know how re-trying the install works.

**Comment by LotrForTheWin** [comment] 2020-11-21 17:37
Hello, 
I believe that there might be a problem in guide for neewbes with ./asounrc. The values provided by author might differ on devices. It is better to check it in dev/snd or just set it in volume control (right upper corner of the screen)

Anyway, i did manage to install the SDK, I did only change "make sampleApp" to "make" so everything is made.
After the authorization, i discovered that the sound is played from audio jack (thumbs up)
However I notice that wakeword does not work (I can still input commands using 't' command)
Any tips to fix that?

**Comment by mvelegon-amzn** [comment] 2020-11-23 17:32
@LotrForTheWin when you built the SDK, did you enable Sensory Key Word Detector in the cmake command? Wake word detector is an optional build configuration to the SDK and the SDK can function without it using just the tap to talk feature.

**Comment by LotrForTheWin** [comment] 2020-11-24 07:40
Yes, I did exactlly like in Guide.

**Comment by mvelegon-amzn** [comment] 2020-11-24 17:38
@LotrForTheWin can you capture Debug9 logs when the issue occurs with wake word and add the logs here so that we can diagnose the issue further?

**Comment by LotrForTheWin** [comment] 2020-11-25 19:38
hello @mvelegon-amzn 
I did try to get the debug logs, but there are no debugs on my console :(
Bellow are my installation scripts.
I did add the "-DCMAKE_BUILD_TYPE=DEBUG" in instal3.sh but:
It did not provide any logs,
After the app authorize, the connecting steps takes long time. 

Here is the command that I start my app with:
PA_ALSA_PLUGHW=1 ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json DEBUG9

[instal.txt](https://github.com/alexa/avs-device-sdk/files/5598883/instal.txt)
[instal2.txt](https://github.com/alexa/avs-device-sdk/files/5598884/instal2.txt)
[instal3.txt](https://github.com/alexa/avs-device-sdk/files/5598885/instal3.txt)
[instal4.txt](https://github.com/alexa/avs-device-sdk/files/5598886/instal4.txt)
[instal5.txt](https://github.com/alexa/avs-device-sdk/files/5598887/instal5.txt)

Now I am facing 2 problems:
-wake word does not work
-when I switch to usb audio port output there is this issue:

**Comment by mvelegon-amzn** [comment] 2020-11-26 01:34
@LotrForTheWin 

1. Regarding why WW is not working: it appears to be because you are not using the startsample.sh . This script runs also passes the WW configuration argument. Please let me know if that works.

2. Regarding the issue with USB audio port output: I think we will need to look at the debug9 logs to see why this is happening. Can you let us know what happens when you run the startsample.sh script (you should ideally see logs on the console)

3. Regarding the comment on instructions:

The Sample App is provided as a reference for how to integrate with the SDK, and we suggest developers look at how the Sample App initializes the Default Client and registers for observer callbacks in order to learn how they might structure their own app. Since you're just starting out, you might just want to extend or simply modify the existing Sample App classes, or you could replace the Sample App with your own application. Start by reading through SampleApplication.cpp, UIManager.cpp, UserInputManager.cpp, and InteractionManager.cpp to see how we set up a very simple console application that lets a user interact with Alexa.

You're not limited to the Sample App, though. That is just provided as a simple example. Some developers actually replace the Default Client class itself, which is quite advanced and we do not recommend that to someone just starting out with creating a new app.

If you have a Solutions Architect, we encourage you to reach out to them for additional support with this.

**Comment by LotrForTheWin** [comment] 2020-11-26 14:27
> Hi @LotrForTheWin , have you tried running the setup script without `sudo`? That should not be necessary. You will have to delete your workspace before re-running the script without `sudo`.
> 
> What was the path to the `.asound.rc` file that you mentioned you modified in "Used solutions" 3?
> 
> If you followed our raspberry pi guide (https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html), it tells you to modify `~/.asound.rc`. But if you're using `sudo` to build and run the app, it might be looking for the root user's sound configuration.
> 
> Please try deleting your workspace and re-running the setup script without `sudo`. Or, if you need to keep using `sudo` for some other reason (not recommended), then check out #1544 for more troubleshooting tips.

1.
@mvelegon-amzn 
According to this post I should be using the other tutorial. (where startsample.sh is not used.) 
As mentioned by @caleighatamazon that guide got some bugs, so I switched to recommended one. 
To avoid any missmatches, can you make fix with my instal*.txt files so I can run with WW command instead? I believe that Cmake in instal3.txt got ww included. 

2. 
Im using the command provided in other guide (witch is same as the one from startsample.sh). There are no logs, the console is only providing info like:

**********************************
* Alexa is in idle *
*****************************

ETC.

**Comment by w0244079** [comment] 2020-11-28 23:24
I installed the sdk (1.21.1) on a Raspberry PI 4 and had the same audio issues (no audio over analog). I then installed version 1.19.1 of the sdk and that too did not produce audio over analog.
I then installed an earlier version of raspbian (Feb 14 2020) and then installed the latest version of the SDK (1.21.1) and this worked!

Does this mean that the issue lies in the latest version of Raspbian moreso than the SDK? (Aug 2020)

**Comment by mvelegon-amzn** [comment] 2020-11-30 16:03
Hi @LotrForTheWin Can you please run the following command:
`
PA_ALSA_PLUGHW=1 ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json  "/home/pi/sdk-folder/third-party/alexa-rpi/models" DEBUG9
`
This should fix the Wake Word issue. 

Regarding the audio output we would have to take a look at the debug9 logs . So please post the output displayed on the console here when you run the above command.

**Comment by mvelegon-amzn** [comment] 2020-11-30 16:05
@w0244079 We would need to take a look at the debug9 logs to understand why this is happening. It is possible this is happening because of a dependency not being installed correctly on the newest version of the raspbian. Also, were you using the same .asoundrc file and the same AlexaClientSDKConfig.json files in both cases?

**Comment by w0244079** [comment] 2020-11-30 21:11
@mvelegon-amzn Yes I didn't modify the installation procedure for both installs. And I didn't modify either the .asoundrc file or the AlexaClientSDKConfig.json file in either installation. I followed the instructions at https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/set-up-raspberry-pi.html

**Comment by w0244079** [comment] 2020-12-01 00:47
I wanted to add my findings re running the sdk....I mentioned that the sdk (1.20) ran properly with audio on the Feb2020 release of Raspbian. The sdk ran properly BEFORE running apt-get upgrade. Once latest updates were applied, the audio stopped working.

**Comment by caleighatamazon** [comment] 2021-01-07 00:33
Hi @w0244079 , it looks like you've resolved your issue and there have been no updates here for some time, so I'm going to close this. If you want some more support in investigating this, please open a new issue and also provide the DEBUG9 logs where you reproduce the problem. We won't be able to investigate more without the DEBUG9 logs. Thanks!

**Comment by w0244079** [comment] 2021-01-07 01:58
No the issue isn’t resolved. It’s just a workaround as far as I’m concerned.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by caleighatamazon** [comment] 2021-01-07 17:28
Hi @w0244079 , I'll reopen the issue if you'd like more support. Can you please provide DEBUG9 logs where you reproduce the problem? You can attach the logs as a file.

**Comment by caleighatamazon** [comment] 2021-02-19 22:06
Closing this due to inactivity. Please open a new issue with logs if you still have questions or concerns.

**Closed by caleighatamazon** 2021-02-19 22:06 UTC
Labels: Awaiting more information
