### ISSUE TITLE
Two previus cmd after paired bluetooth devices, when say "Alexa previus"

### ISSUE THREAD

**Issue by Hzd95** [alexa/avs-device-sdk#1534] opened 2019-10-21 02:20 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

1.14
## Briefly summarize your issue:
when device connected with phone  bluetooth,I say “Alexa previous”. Device will play previous sounds.But now ,when i say "Alexa,previous!".Device play Before the two songs.

## Provide the steps to reproduce the issue, if applicable:

1."Alexa connected my phone"
2."play music from phone"
3."Alexa,previous"
### What version of the AVS Device SDK are you using?
      <x.y.z>
1.14
### Tell us what hardware you're using:
- [ *] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ *] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
[two_previous_command.log](https://github.com/alexa/avs-device-sdk/files/3748804/two_previous_command.log)

**Comment by samcoult** [comment] 2019-10-22 18:16
Hi @Hzd95 , are you seeing this issue on the latest version of the SDK (1.15)?

What do you mean by "Device play Before the two songs. "

**Comment by Hzd95** [comment] 2019-10-23 02:00
Hi @samcoult  ,I didn't test this issue with the latest version of the SDK.I don't think this issue has anything to do with the SKD version.Because when I said "Alexa,previous "with bluetooth connected, the log shows the last two times the interface was called.So,The bluetooth playing the last of the last music .Maybe,the cloud has send two same command to control bluetooth .

**Comment by samcoult** [comment] 2019-10-23 18:23
Hi @Hzd95 ,

Thanks for reporting this issue. I have created an internal tracking issue to get this looked at.

**Comment by kjkh** [comment] 2019-11-05 01:30
Hi @Hzd95,

This is by design. In Bluetooth AVRCP, the first previous command will rewind the song to the beginning, and the second previous will go to the previous song. If done within the first few seconds of playback, depending on the application, this may cause navigation past multiple songs.

**Comment by Hzd95** [comment] 2019-11-07 02:54
Hi @kjkh 
What can we do to prevent this from happening?After all, this is not user-friendly.

**Comment by caleighatamazon** [comment] 2020-03-11 18:15
This is actually the intended behaviour for Bluetooth AVRCP profile, so we do not recommend preventing it from happening, since it's implemented in all Bluetooth devices that use that profile (not just the AVS SDK -- for example, this profile is commonly used in cars, too). Closing this issue.

**Closed by caleighatamazon** 2020-03-11 18:15 UTC
