### ISSUE TITLE
[Android] "Failed to create to SampleApplication!"

### ISSUE THREAD

**Issue by stevenguan-xmos** [alexa/avs-device-sdk#1522] opened 2019-10-11 05:18 UTC
## Briefly summarize your issue:

I am familiar with the AVS client as I support an audio front end processor that passes audio over to an RPi running the AVS client. I'm currently trying to bring up the client on an Android based AP.

I've tried following the [Android Quick Start Guide](
https://github.com/alexa/avs-device-sdk/wiki/Android-Quick-Start-Guide) to bring up the AVS SDK on an Android based AP. I've gotten things to a point where the AVS SDK has been cross-compiled on an Ubuntu machine and sent over to the Android device. Some slight tweaking to the scripts were made in order for the scripts to successfully perform adb pushes onto the Android device, but nothing about the actual SDK itself was changed. Running the Sample App unfortunately yields an error.

## What is the expected behavior?

I was expecting Alexa to come online and enter the "idle state".

## What behavior are you observing?

Here is the log when I run the Sample App. Note: the 'avsrun.sh' mentioned in the below log is just a script that I made to make calling the Sample App easier on the AP. The script itself just does the command found in the provided 'startsample.sh', minus the 'adb push' since I am running it on the Android device directly. The behavior is the same even if I use the provided 'startsample.sh'. For completeness, here is the command of my 'avsrun.sh':

`LD_LIBRARY_PATH=/avs-scripts/install/       /avs-scripts/install/bin/SampleApp       /avs-scripts/install/AlexaClientSDKConfig.json DEBUG9`

Here is the log when I try to start the AVS client:

```
2|odroidn2:/avs-scripts # ./avsrun.sh                                          
2019-10-11 01:57:56.689 [  1] I sdkVersion: 1.15.0
configFile /avs-scripts/install/AlexaClientSDKConfig.json
Running app with log level: DEBUG9
2019-10-11 01:57:56.708 [  1] 0 ConfigurationNode:initializeSuccess
2019-10-11 01:57:56.711 [  1] 1 InMemoryEqualizerConfiguration:validateConfiguration::Validating Equalizer configuration
2019-10-11 01:57:56.711 [  1] 1 InMemoryEqualizerConfiguration:validateConfiguration::Validating default Equalizer state
2019-10-11 01:57:56.711 [  1] 1 InMemoryEqualizerConfiguration:validateConfiguration::Validating Equalizer configuration
2019-10-11 01:57:56.711 [  1] 1 InMemoryEqualizerConfiguration:validateConfiguration::Validating default Equalizer state
2019-10-11 01:57:56.712 [  1] 0 SQLiteDatabase:open::File specified does not exist.:file path=~/avs-scripts/install/databases/miscDatabase.db
2019-10-11 01:57:56.712 [  1] 0 SQLiteMiscStorage:openDatabaseFailed
2019-10-11 01:57:56.712 [  1] 3 MiscDBEqualizerStorage:initialize::Couldn't open misc database. Creating.
2019-10-11 01:57:56.712 [  1] E SQLiteUtils:openSQLiteDatabaseHelperFailed::Could not open database.:rcode=14,file path=~/avs-scripts/install/databases/miscDatabase.db,error message=unable to open database file
2019-10-11 01:57:56.712 [  1] E SQLiteUtils:createSQLiteDatabaseFailed::Could not create database.
2019-10-11 01:57:56.712 [  1] E SQLiteDatabase:initialize::Database could not be created.:file path=~/avs-scripts/install/databases/miscDatabase.db
2019-10-11 01:57:56.712 [  1] E SQLiteMiscStorage:createDatabaseFailed
2019-10-11 01:57:56.712 [  1] E MiscDBEqualizerStorage:initializeFailed:reason=Could not create misc database.
2019-10-11 01:57:56.712 [  1] E MiscDBEqualizerStorage:createFailed:reason=Failed to initialize.
2019-10-11 01:57:56.726 [  1] 5 AndroidSLESMediaPlayer:initializeEqualizer
2019-10-11 01:57:56.726 [  1] 7 AndroidSLESMediaPlayer:initializeEqualizer:Bands: =5
2019-10-11 01:57:56.727 [  1] 7 AndroidSLESMediaPlayer:initializeEqualizer:Min=-15,Max=15
2019-10-11 01:57:56.755 [  1] 5 SQLiteDeviceSettingStorage:create
2019-10-11 01:57:56.755 [  1] 5 SQLiteBluetoothStorage:create
2019-10-11 01:57:56.755 [  1] I LocaleAssetsManager:initialize:supportedWakeWords=NONE
2019-10-11 01:57:56.755 [  1] 5 CBLAuthDelegate:create
2019-10-11 01:57:56.755 [  1] 5 CBLAuthDelegate:CBLAuthDelegate
2019-10-11 01:57:56.755 [  1] 5 CBLAuthDelegate:init
2019-10-11 01:57:56.755 [  1] 5 CBLAuthDelegateConfiguration:create
2019-10-11 01:57:56.755 [  1] 5 CBLAuthDelegateConfiguration:init
2019-10-11 01:57:56.755 [  1] 5 CBLAuthDelegateConfiguration:initScopeData
2019-10-11 01:57:56.755 [  1] 9 CBLAuthDelegateConfiguration:initScopeDataSucceeded
2019-10-11 01:57:56.756 [  1] 5 SQLiteCBLAuthDelegateStorage:open
2019-10-11 01:57:56.756 [  1] 0 SQLiteDatabase:open::File specified does not exist.:file path=~/avs-scripts/install/databases/cblAuthDelegate.db
2019-10-11 01:57:56.756 [  1] 0 SQLiteCBLAuthDelegateStorage:openFailed:reason=openSQLiteDatabaseFailed
2019-10-11 01:57:56.756 [  1] 5 CBLAuthDelegate:init::openStorageFailed
2019-10-11 01:57:56.756 [  1] 5 SQLiteCBLAuthDelegateStorage:createDatabase
2019-10-11 01:57:56.756 [  1] E SQLiteUtils:openSQLiteDatabaseHelperFailed::Could not open database.:rcode=14,file path=~/avs-scripts/install/databases/cblAuthDelegate.db,error message=unable to open database file
2019-10-11 01:57:56.756 [  1] E SQLiteUtils:createSQLiteDatabaseFailed::Could not create database.
2019-10-11 01:57:56.756 [  1] E SQLiteDatabase:initialize::Database could not be created.:file path=~/avs-scripts/install/databases/cblAuthDelegate.db
2019-10-11 01:57:56.756 [  1] E SQLiteCBLAuthDelegateStorage:createDatabaseFailed:reason=SQLiteCreateDatabaseFailed
2019-10-11 01:57:56.756 [  1] E CBLAuthDelegate:initFailed:reason=createDatabaseFailed
2019-10-11 01:57:56.756 [  1] 5 CBLAuthDelegate:stop
2019-10-11 01:57:56.756 [  1] 5 SQLiteCBLAuthDelegateStorage:~SQLiteCBLAuthDelegateStorage
2019-10-11 01:57:56.756 [  1] 5 SQLiteCBLAuthDelegateStorage:close
2019-10-11 01:57:56.756 [  1] C SampleApplication:Creation of AuthDelegate failed!
2019-10-11 01:57:56.756 [  1] 5 SQLiteDeviceSettingStorage:close
2019-10-11 01:57:56.756 [  1] C SampleApplication:Failed to initialize SampleApplication
2019-10-11 01:57:56.756 [  1] 9 AndroidSLESMediaPlayer:doShutdown:name=SpeakMediaPlayer
2019-10-11 01:57:56.756 [  1] 9 AndroidSLESMediaPlayer:doShutdown:name=AudioMediaPlayer
2019-10-11 01:57:56.756 [  1] 9 AndroidSLESMediaPlayer:doShutdown:name=AlertsMediaPlayer
2019-10-11 01:57:56.757 [  1] 9 AndroidSLESMediaPlayer:doShutdown:name=NotificationsMediaPlayer
2019-10-11 01:57:56.757 [  1] 9 AndroidSLESMediaPlayer:doShutdown:name=BluetoothMediaPlayer
2019-10-11 01:57:56.757 [  1] 9 AndroidSLESMediaPlayer:doShutdown:name=SystemSoundMediaPlayer
2019-10-11 01:57:56.757 [  1] 9 AndroidSLESMediaPlayer:doShutdown:name=RingtoneMediaPlayer
2019-10-11 01:57:56.757 [  1] 9 AndroidSLESMediaPlayer:~AndroidSLESMediaPlayer:name=RingtoneMediaPlayer
2019-10-11 01:57:56.757 [  1] 9 AndroidSLESMediaPlayer:doShutdown:name=RingtoneMediaPlayer
2019-10-11 01:57:56.758 [  1] 9 AndroidSLESMediaPlayer:~AndroidSLESMediaPlayer:name=SystemSoundMediaPlayer
2019-10-11 01:57:56.758 [  1] 9 AndroidSLESMediaPlayer:doShutdown:name=SystemSoundMediaPlayer
2019-10-11 01:57:56.759 [  1] 9 AndroidSLESMediaPlayer:~AndroidSLESMediaPlayer:name=BluetoothMediaPlayer
2019-10-11 01:57:56.759 [  1] 9 AndroidSLESMediaPlayer:doShutdown:name=BluetoothMediaPlayer
2019-10-11 01:57:56.760 [  1] 9 AndroidSLESMediaPlayer:~AndroidSLESMediaPlayer:name=NotificationsMediaPlayer
2019-10-11 01:57:56.760 [  1] 9 AndroidSLESMediaPlayer:doShutdown:name=NotificationsMediaPlayer
2019-10-11 01:57:56.761 [  1] 9 AndroidSLESMediaPlayer:~AndroidSLESMediaPlayer:name=AlertsMediaPlayer
2019-10-11 01:57:56.761 [  1] 9 AndroidSLESMediaPlayer:doShutdown:name=AlertsMediaPlayer
2019-10-11 01:57:56.761 [  1] 9 AndroidSLESMediaPlayer:~AndroidSLESMediaPlayer:name=AudioMediaPlayer
2019-10-11 01:57:56.762 [  1] 9 AndroidSLESMediaPlayer:doShutdown:name=AudioMediaPlayer
2019-10-11 01:57:56.762 [  1] 9 AndroidSLESMediaPlayer:~AndroidSLESMediaPlayer:name=SpeakMediaPlayer
2019-10-11 01:57:56.763 [  1] 9 AndroidSLESMediaPlayer:doShutdown:name=SpeakMediaPlayer
Failed to create to SampleApplication!
```

## Provide the steps to reproduce the issue, if applicable:

Following the steps as outlined should replicate the problem as far as I can tell. I did not modify any of the scripts except for adb_push() at the end of android.sh. It appears the adb push commands were failing due to the DEVICE_INSTALL_PATH and DEVICE_BIN_PATH variables started with a '~' . Removing the tilde allowed the script to move the necessary files onto the Android device.

### What version of the AVS Device SDK are you using?
     SDK 1.15.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:

I'm using an ODROID N2, which is an Amlogic based Android Applications Processor board:

https://www.hardkernel.com/shop/odroid-n2-with-4gbyte-ram/

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:

Android 9 (Pie). v4.9.113 to be exact.

**Comment by scotthea-amazon** [comment] 2019-10-11 23:49
Hello  @stevenguan-xmos 

From the logs it looks pretty clearly like the issue is with opening a database file:

`2019-10-11 01:57:56.756 [  1] 5 SQLiteCBLAuthDelegateStorage:createDatabase
2019-10-11 01:57:56.756 [  1] E SQLiteUtils:openSQLiteDatabaseHelperFailed::Could not open database.:rcode=14,file path=~/avs-scripts/install/databases/cblAuthDelegate.db,error message=unable to open database file`

It looks like you probably have the tilde '~' in the database paths specified in AlexaClientSDKConfig.json.  Have you checked that and replaced the tilde in database paths with absolute paths?

You should also verify that your application have permission to write to the databases directory.

Best regards,
-SWH

**Comment by stevenguan-xmos** [comment] 2019-10-15 17:29
Hi @scotthea-amazon 

Thanks for the reply! I appreciate you giving me an idea of where to look. The pathing issue sounds promising.

I do have a bigger picture type question if you're willing to humor me: the current AVS SDK for Android seems to only be push-to-talk. Are there any plans for an "always listening" version like the RPi version of the AVS SDK? Being able to summon Alexa via keyword will make this immensely more useful!

**Comment by caleighatamazon** [comment] 2019-10-28 21:37
Hi there! We can't speak to particular road map plans, unfortunately. Hopefully you were able to fix the path issue. I'm going to close this issue for now but please feel free to re-open this if you still have trouble.

**Closed by caleighatamazon** 2019-10-28 21:37 UTC
