### ISSUE TITLE
[Auto SDK]: Alexa responds "Music and radio playback are not supported in this device"

### ISSUE THREAD

**Issue by DeepikaBalaga** [alexa/avs-device-sdk#1792] opened 2020-09-13 13:43 UTC
# Briefly summarize your issue:
Alexa says 'Music and radio playback are not supported in this device"

## What is the expected behavior?
• Music plays on the connected device, NOT on the Smartphone or tablet.
• After the Alexa Auto device is disconnected, ensure that Music stops playing.

## What behavior are you observing?
Alexa says 'Music and radio playback are not supported in this device"

**[Precondition]**
Music - Verify play on Smartphone and Tablet

Ensure that a smartphone or tablet AVS Application will NOT stream any music unless connected to the Alexa Auto client device it supports.

Connect the Alexa Auto client device which is running on a Smartphone or tablet application to the appropriate Audio speaker (i.e. connect a wired or Bluetooth device to an external speaker system).

## Provide the steps to reproduce the issue, if applicable:
[Test steps]
1. Play music.
2. Verify Music is playing on the connected Alexa Auto client.
3. Disconnect or switch off the Alexa Auto device.
4. Stop the music.

Utterance:
1. Play music
2. Stop

## Tell us about your environment:
SW:  app-local-debug.apk on Android Mobile

### What version of the AVS Device SDK are you using?
     AUTO SDK

### Tell us what hardware you're using:
- [ ] Other - Android phone

### Tell us about your OS (Type & version):
- [ ] Other - Android Phone

**Comment by scotthea-amazon** [comment] 2020-09-14 17:47
Hello @DeepikaBalaga,

Please use this link for assistance with the Auto SDK: https://github.com/alexa/alexa-auto-sdk/blob/2.3/NEED_HELP.md

Best regards,
-SWH

**Comment by scotthea-amazon** [comment] 2020-09-15 17:27
Hello @DeepikaBalaga,

Closing as this is an Auto SDK issue. Of course, if it the root cause is found to be in the AVS Device SDK, please feel free to create a new issue with information to help is reproduce and diagnose the issue.

Best regards,
-SWH

**Closed by scotthea-amazon** 2020-09-15 17:27 UTC
