### ISSUE TITLE
Make install installs only headers and shared objects, not SampleAPP

### ISSUE THREAD

**Issue by Renegade85** [alexa/avs-device-sdk#1677] opened 2020-04-20 16:45 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

The "make install" invocation installs only shared objects and headers

## What is the expected behavior?

I would expect that it would also install the SampleApp somewhere. We are integrating AVS into our Yocto build and the missing install step of SampleApp requires to do it manually, however, it's quite complicated to reproduce the exact procedure by hand as is carried over following the build procedure - https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/linux.html

## What behavior are you observing?

Only shared objects and headers being installed, not the sample app

### What version of the AVS Device SDK are you using?
1.18.0 - 1.19.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:
i.MX8M/Mini EVK from NXP

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:
Embedded Linux from NXP (code aurora)

**Comment by samcoult** [comment] 2020-04-20 18:35
Hi @Renegade85 

The SDK is a library that allows users to develop Alexa enabled applications. As such the "make install" target installs the necessary library and header files to begin development of your application. The Sample App is provided as a reference or starting point for your application, but generally speaking should not be "installed" on a development machine. As such the "make install" target is working as intended.

If necessary, I would recommend modifying the Sample App CMake files to include it in the install target. However guidance on how exactly to modify CMake files is outside the scope of this support board.

I am going to close this ticket, please open a new ticket if you have more questions.
Sam

**Closed by samcoult** 2020-04-20 18:35 UTC
