### ISSUE TITLE
AVS is not able to determine the number of days to Xmas

### ISSUE THREAD

**Issue by IeiuniumLux** [alexa/avs-device-sdk#1655] opened 2020-03-27 21:53 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I installed the AVS SDK 1.18.0 and launched the `SampleApp` using the `AlexaClientSDKConfig.json` file. I If you ask how many days before Cinco de Mayo, then it answers: `It's in 40 days on Tuesday, May 5th 2020`; which is correct. Same with Thanksgiving and other holidays.

However, if you ask, how many days before Christmas? Then, the answer is: `Christmas is in 2100 days on Thursday, Dec 25th 2025.`

## What is the expected behavior?
The expected answer should be: `it's in 273 days on Friday, December 25, 2020`

## What behavior are you observing?
`Christmas is in 2100 days on Thursday, Dec 25th in 2025.` instead.

## Provide the steps to reproduce the issue, if applicable:
$ cd ~/sdk_folder/sdk-build
$ ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json

Press `t` + `Enter`, and ask: `how many days before Christmas?`

## Tell us about your environment:
SDK Version 1.18.0

### Tell us what hardware you're using:
- [ ] UDOO X86 Ultra (https://shop.udoo.org/udoo-x86-ii-ultra.html)

### Tell us about your OS (Type & version):
- [ ] Linux (Ubuntu 18.04)

**Comment by kjkh** [comment] 2020-03-31 01:06
Hi @IeiuniumLux,

Thank you for reaching out. Is this consistently reproducible? If so, can you please attach DEBUG logs? In general, this would be out of scope of the AVS SDK, since we do not generate the contents of responses. However, we can take a quick look at the logs to verify the SDK is behaving as expected.

If this is related to users settings, you may have luck posting on the general Alexa forum:
https://www.amazonforum.com/s/topic/0TO4P000000t6lkWAA/general-echo-alexa

**Comment by IeiuniumLux** [comment] 2020-03-31 17:49
@kjkh,

Yes, this is consistently reproducible.  Debug logs attached.  Cheers!

[logs.txt](https://github.com/alexa/avs-device-sdk/files/4410670/logs.txt)

**Comment by kjkh** [comment] 2020-04-01 21:57
Hi @IeiuniumLux,

I took a look through the logs and the SDK is behaving correctly. I have filed a ticket internally to the cloud team, and will update this ticket with the progress.

**Comment by IeiuniumLux** [comment] 2020-04-01 22:00
Copy that, thanks @kjkh

**Comment by scotthea-amazon** [comment] 2020-04-16 01:27
Hello @IeiuniumLux,

We have a task in our backlog to fix this, so I am closing out the issue.  We will announce a fix in our [release notes](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/release-notes.html) when the fix is released.

Thank you again for bringing this to our attention!

Best regards,
-SWH

**Closed by scotthea-amazon** 2020-04-16 01:27 UTC

**Comment by kjkh** [comment] 2020-04-24 18:13
Hi @IeiuniumLux,

Is this issue still reproducible? If so, can you attach fresh logs and reopen the ticket?
