### ISSUE TITLE
Incorrect playback behavior of Prime music

### ISSUE THREAD

**Issue by fallouter007** [alexa/avs-device-sdk#634] opened 2018-04-20 09:15 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Playlist of Prime music is played but songs are played twice after issuing some commands, such as loop and shuffle. The command itself works, i.e. playlist is looped or shuffled. 

This seems to be controlled by AVS server (or Prime music service), instead of device.
Just to clarify if there's information or data that device doesn't update to AVS correctly and results in such issue.

When 1st song is playing, I ask to enable loop mode. Leave device to play song for several minutes.
Ask to disable loop mode in the playback of 4th song.
Part of log is showed below. 
```
2018-04-20 07:20:48.072 [ 14] 9 AudioPlayer:PLAY:payload={"audioItem"\:{"audioItemId"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:1"\,"stream"\:{"offsetInMilliseconds"\:0\,"expiryTime"\:"2018-04-20T07\:21\:42+0000"\,"progressReport"\:{"progressReportDelayInMilliseconds"\:1000}\,"url"\:"https\://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m3u8?m\=m&dmid\=284445540&c\=cf&f\=ts&t\=10&bl\=256k&s\=true&e1\=1524210300000&e2\=1524210300000&v\=V2&n\=P2EKUKH2ROISS&h\=d16ac44896180e3fd809669a6d7db6ccc857edbe22083e150565663492f0a111"\,"token"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:1"}}\,"playBehavior"\:"REPLACE_ALL"}
2018-04-20 07:21:08.721 [ 14] 9 AudioPlayer:PLAY:payload={"audioItem"\:{"audioItemId"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:2"\,"stream"\:{"offsetInMilliseconds"\:0\,"expiryTime"\:"2018-04-20T07\:22\:08+0000"\,"progressReport"\:{"progressReportDelayInMilliseconds"\:1000}\,"url"\:"https\://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m3u8?m\=m&dmid\=282719011&c\=cf&f\=ts&t\=10&bl\=256k&s\=true&e1\=1524210300000&e2\=1524210300000&v\=V2&n\=4OYMS3LOW2FEC&h\=d5afd03c0ae11e3afbd2888603733db586abf84482fd203884e54d7bc63c33de"\,"token"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:2"}}\,"playBehavior"\:"REPLACE_ENQUEUED"}
2018-04-20 07:23:39.984 [ 14] 9 AudioPlayer:PLAY:payload={"audioItem"\:{"audioItemId"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:2"\,"stream"\:{"offsetInMilliseconds"\:0\,"expiryTime"\:"2018-04-20T07\:24\:39+0000"\,"progressReport"\:{"progressReportDelayInMilliseconds"\:1000}\,"url"\:"https\://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m3u8?m\=m&dmid\=282719011&c\=cf&f\=ts&t\=10&bl\=256k&s\=true&e1\=1524210300000&e2\=1524210300000&v\=V2&n\=4OYMS3LOW2FEC&h\=d5afd03c0ae11e3afbd2888603733db586abf84482fd203884e54d7bc63c33de"\,"token"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:2"}}\,"playBehavior"\:"ENQUEUE"}
2018-04-20 07:27:06.298 [ 14] 9 AudioPlayer:PLAY:payload={"audioItem"\:{"audioItemId"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:3"\,"stream"\:{"offsetInMilliseconds"\:0\,"expiryTime"\:"2018-04-20T07\:28\:06+0000"\,"progressReport"\:{"progressReportDelayInMilliseconds"\:1000}\,"url"\:"https\://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m3u8?m\=m&dmid\=279853433&c\=cf&f\=ts&t\=10&bl\=256k&s\=true&e1\=1524210300000&e2\=1524210300000&v\=V2&n\=LPCVFLYXADTPG&h\=4319cd5aacff2718e46de943f5d00ffc611856667814aab3b5e776cbff371a20"\,"token"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:3"}}\,"playBehavior"\:"ENQUEUE"}
2018-04-20 07:30:32.797 [ 14] 9 AudioPlayer:PLAY:payload={"audioItem"\:{"audioItemId"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:3"\,"stream"\:{"offsetInMilliseconds"\:0\,"expiryTime"\:"2018-04-20T07\:31\:32+0000"\,"progressReport"\:{"progressReportDelayInMilliseconds"\:1000}\,"url"\:"https\://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m3u8?m\=m&dmid\=279853433&c\=cf&f\=ts&t\=10&bl\=256k&s\=true&e1\=1524211200000&e2\=1524211200000&v\=V2&n\=RPL453OW255S4&h\=dbfeb7490a39bcab2732b0a2d42e8da5121f8a5797e792c0ba0b26b8e5c4fcd3"\,"token"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:3"}}\,"playBehavior"\:"ENQUEUE"}
2018-04-20 07:34:42.806 [ 14] 9 AudioPlayer:PLAY:payload={"audioItem"\:{"audioItemId"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:4"\,"stream"\:{"offsetInMilliseconds"\:0\,"expiryTime"\:"2018-04-20T07\:35\:42+0000"\,"progressReport"\:{"progressReportDelayInMilliseconds"\:1000}\,"url"\:"https\://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m3u8?m\=m&dmid\=278438138&c\=cf&f\=ts&t\=10&bl\=256k&s\=true&e1\=1524211200000&e2\=1524211200000&v\=V2&n\=PRYB3NLTBE2SY&h\=8dbf8faa8949fbd3a61d838c9321eb498fd78fa9e031e36bee3005ceedb64677"\,"token"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:4"}}\,"playBehavior"\:"ENQUEUE"}
2018-04-20 07:38:54.307 [ 14] 9 AudioPlayer:PLAY:payload={"audioItem"\:{"audioItemId"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:4"\,"stream"\:{"offsetInMilliseconds"\:0\,"expiryTime"\:"2018-04-20T07\:39\:54+0000"\,"progressReport"\:{"progressReportDelayInMilliseconds"\:1000}\,"url"\:"https\://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m3u8?m\=m&dmid\=278438138&c\=cf&f\=ts&t\=10&bl\=256k&s\=true&e1\=1524211200000&e2\=1524211200000&v\=V2&n\=PRYB3NLTBE2SY&h\=8dbf8faa8949fbd3a61d838c9321eb498fd78fa9e031e36bee3005ceedb64677"\,"token"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:4"}}\,"playBehavior"\:"ENQUEUE"}
2018-04-20 07:42:24.270 [ 14] 9 AudioPlayer:PLAY:payload={"audioItem"\:{"audioItemId"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:5"\,"stream"\:{"offsetInMilliseconds"\:0\,"expiryTime"\:"2018-04-20T07\:43\:23+0000"\,"progressReport"\:{"progressReportDelayInMilliseconds"\:1000}\,"url"\:"https\://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m3u8?m\=m&dmid\=282287675&c\=cf&f\=ts&t\=10&bl\=256k&s\=true&e1\=1524211200000&e2\=1524211200000&v\=V2&n\=GGPK7ENXNTYSG&h\=18e1de4129fafa5967b304d941bcb682ac262c31058c12c18ba61c46b035fcb2"\,"token"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:5"}}\,"playBehavior"\:"REPLACE_ENQUEUED"}
2018-04-20 07:43:26.057 [ 14] 9 AudioPlayer:PLAY:payload={"audioItem"\:{"audioItemId"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:5"\,"stream"\:{"offsetInMilliseconds"\:0\,"expiryTime"\:"2018-04-20T07\:44\:25+0000"\,"progressReport"\:{"progressReportDelayInMilliseconds"\:1000}\,"url"\:"https\://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m3u8?m\=m&dmid\=282287675&c\=cf&f\=ts&t\=10&bl\=256k&s\=true&e1\=1524211200000&e2\=1524211200000&v\=V2&n\=GGPK7ENXNTYSG&h\=18e1de4129fafa5967b304d941bcb682ac262c31058c12c18ba61c46b035fcb2"\,"token"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:5"}}\,"playBehavior"\:"ENQUEUE"}
2018-04-20 07:46:11.731 [ 14] 9 AudioPlayer:PLAY:payload={"audioItem"\:{"audioItemId"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:6"\,"stream"\:{"offsetInMilliseconds"\:0\,"expiryTime"\:"2018-04-20T07\:47\:11+0000"\,"progressReport"\:{"progressReportDelayInMilliseconds"\:1000}\,"url"\:"https\://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m3u8?m\=m&dmid\=278396723&c\=cf&f\=ts&t\=10&bl\=256k&s\=true&e1\=1524212100000&e2\=1524212100000&v\=V2&n\=EHYEXHRUF633Q&h\=3da718d69b58b6333bfcecc6a1685cfee9a2eb7cb384cad383f0799c8f6e10d3"\,"token"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:6"}}\,"playBehavior"\:"ENQUEUE"}
2018-04-20 07:48:57.345 [ 14] 9 AudioPlayer:PLAY:payload={"audioItem"\:{"audioItemId"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:6"\,"stream"\:{"offsetInMilliseconds"\:0\,"expiryTime"\:"2018-04-20T07\:49\:57+0000"\,"progressReport"\:{"progressReportDelayInMilliseconds"\:1000}\,"url"\:"https\://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m3u8?m\=m&dmid\=278396723&c\=cf&f\=ts&t\=10&bl\=256k&s\=true&e1\=1524212100000&e2\=1524212100000&v\=V2&n\=EHYEXHRUF633Q&h\=3da718d69b58b6333bfcecc6a1685cfee9a2eb7cb384cad383f0799c8f6e10d3"\,"token"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:6"}}\,"playBehavior"\:"ENQUEUE"}
2018-04-20 07:52:44.773 [ 14] 9 AudioPlayer:PLAY:payload={"audioItem"\:{"audioItemId"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:7"\,"stream"\:{"offsetInMilliseconds"\:0\,"expiryTime"\:"2018-04-20T07\:53\:44+0000"\,"progressReport"\:{"progressReportDelayInMilliseconds"\:1000}\,"url"\:"https\://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m3u8?m\=m&dmid\=275481006&c\=cf&f\=ts&t\=10&bl\=256k&s\=true&e1\=1524212100000&e2\=1524212100000&v\=V2&n\=5WHIIPT4HIETI&h\=ecc432628636ac7dd4504bd0533fd8edf24065b90520409686c0bcc1ab6261e2"\,"token"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#2702ad7b-6bd1-46cd-b6c7-b2a3e96486ed\:7"}}\,"playBehavior"\:"ENQUEUE"}
```

Detailed log can be found from attached log.
[issue_prime_duplicate.txt](https://github.com/alexa/avs-device-sdk/files/1931460/issue_prime_duplicate.txt)

## What is the expected behavior?

The playlist should be looped after last song is finished. Each song is played once during each iteration.

## What behavior are you observing?

Songs are played twice during tests. After a certain time, it will become normal and play song once in each iteration.

## Provide the steps to reproduce the issue, if applicable:

1. Ask Alexa to play music from prime ("Alexa, play The Top 50 Most Played from Prime")
2. Ask Alexa to enable loop mode  ("Alexa, loop mode on")
3. Leave device to play songs
(In our case, we ask Alexa to disable loop mode while playing 4th song. "Alexa, loop mode off")

### What version of the AVS Device SDK are you using?
      <1.6.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:
       ARM A7

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:
       Linux OpenWRT

**Comment by fallouter007** [comment] 2018-06-13 02:10
Hi @kencecka,

Thank you for update.

**Comment by mvelegon-amzn** [comment] 2019-03-29 23:03
Hi @fallouter007 I will be closing this issue now. Could you please test this on the latest version of the SDK (1.12) and let us know if its still an issue? Feel free to reopen the ticket if you have more questions.

Thanks!
Mahesh

**Comment by fallouter007** [comment] 2019-04-01 04:16
Hi Mahesh,

Tested wit SDK v1.12 and this issue still happened.
I enabled loop mode when 3rd song was playing. After that, each song were played twice.

You can refer to attached log for more information.
[20190401_prime_test.zip](https://github.com/alexa/avs-device-sdk/files/3027746/20190401_prime_test.zip)

**Comment by mvelegon-amzn** [comment] 2019-04-01 17:55
@fallouter007 thank you for testing this on the latest version of the SDK. I will reopen the issue and will post an update here once I have more info. Thanks.

**Comment by kclchan** [comment] 2019-07-05 18:19
I believe this issue is fixed in the cloud side.  Please re-open this if the issue is still reproducible.  Thanks!

**Closed by kclchan** 2019-07-05 18:19 UTC
