### ISSUE TITLE
Alexa taking 3 to 4 sec to respond for the very first command for every RPI 3 reboot

### ISSUE THREAD

**Issue by satishc4u** [alexa/avs-device-sdk#491] opened 2018-02-01 11:50 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Integrated Alexa device sdk 1.4 into the RPI 3 board with custom codec. Alexa taking ~3 to 4 sec to give response for the very first command. From second command onwards alexa responses are quickly compared to first command.

## What is the expected behavior?
Expecting first command response time should be as quickly as subsequent commands.

## What behavior are you observing?
Integrated Alexa device sdk 1.4 into the RPI 3 board with custom codec. Alexa taking ~3 to 4 sec to give response for the very first command. From second command onwards alexa responses are quickly compared to first command.

## Provide the steps to reproduce the issue, if applicable:
1).Integrated Alexa device sdk 1.4 into the RPI 3 board.
2). Provide amazon credentials to get refresh token
3). Execute the sample app 
4). Provide any voice command to get response from amazon cloud
5). Then you will get response after ~ 3 to 4 seconds.

### What version of the AVS Device SDK are you using?
     **v1.4**

### Tell us what hardware you're using:
 **Raspberry Pi 3**

### Tell us about your OS (Type & version):
 **Raspbian Stretch**

**Comment by frozenberg** [comment] 2018-02-01 17:56
Hi @satishc4u,

I can't seem to be able to reproduce this problem on my pi. Could you send the relevant logs? It might be useful to have logs from the startup of the program up to the end of the second interaction.

Make sure you do a DEBUG build and pass the DEBUG9 flag to get all the juicy logs.

Thanks,
Fede

**Comment by satishc4u** [comment] 2018-02-02 05:31
Hi Fede,

Thanks for the reply, I have attached the log **"avs_v1.4.log"** up to the second command.
[avs_v1.4.log](https://github.com/alexa/avs-device-sdk/files/1688167/avs_v1.4.log)

2018-02-02 05:19:39.626 [  1] I sdkVersion: 1.4.0
Running app with log level: DEBUG9
2018-02-02 05:19:39.667 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2018-02-02 05:19:39.675 [  1] I ConfigurationNode:initializeSuccess
2018-02-02 05:19:40.100 [  1] I MediaPlayer:noOutputConversion
2018-02-02 05:19:40.103 [  1] I MediaPlayer:noOutputConversion
2018-02-02 05:19:40.106 [  1] I MediaPlayer:noOutputConversion
2018-02-02 05:19:40.109 [  1] I MediaPlayer:noOutputConversion
2018-02-02 05:19:40.117 [  2] E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=6,error=Couldn't resolve host name
2018-02-02 05:19:40.117 [  2] E AuthDelegate:handleLwaResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.
2018-02-02 05:19:40.122 [  2] E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=6,error=Couldn't resolve host name
2018-02-02 05:19:40.122 [  2] E AuthDelegate:handleLwaResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.
2018-02-02 05:19:40.226 [  1] I AlertScheduler:executeScheduleNextAlertForRendering::no work to do.
2018-02-02 05:19:40.246 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0x1ffb040,policy=BLOCKING
2018-02-02 05:19:40.246 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=ClearQueue,handler=0x1ffbeb0,policy=NON_BLOCKING
2018-02-02 05:19:40.246 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Stop,handler=0x1ffbeb0,policy=NON_BLOCKING
2018-02-02 05:19:40.246 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Play,handler=0x1ffbeb0,policy=NON_BLOCKING
2018-02-02 05:19:40.246 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0x1ffa5b0,policy=NON_BLOCKING
2018-02-02 05:19:40.246 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=StopCapture,handler=0x1ffa5b0,policy=NON_BLOCKING
2018-02-02 05:19:40.246 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=DeleteAlert,handler=0x1ffcb88,policy=NON_BLOCKING
2018-02-02 05:19:40.246 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=SetAlert,handler=0x1ffcb88,policy=NON_BLOCKING
2018-02-02 05:19:40.246 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=SetEndpoint,handler=0x200a2b8,policy=NON_BLOCKING
2018-02-02 05:19:40.247 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=ResetUserInactivity,handler=0x1ffa36c,policy=NON_BLOCKING
2018-02-02 05:19:40.247 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=AdjustVolume,handler=0x2008bf0,policy=NON_BLOCKING
2018-02-02 05:19:40.247 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetMute,handler=0x2008bf0,policy=NON_BLOCKING
2018-02-02 05:19:40.247 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetVolume,handler=0x2008bf0,policy=NON_BLOCKING
2018-02-02 05:19:40.247 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=TemplateRuntime,name=RenderPlayerInfo,handler=0x2009128,policy=HANDLE_IMMEDIATELY
2018-02-02 05:19:40.247 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=TemplateRuntime,name=RenderTemplate,handler=0x2009128,policy=HANDLE_IMMEDIATELY
2018-02-02 05:19:40.247 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Notifications,name=ClearIndicator,handler=0x200071c,policy=HANDLE_IMMEDIATELY
2018-02-02 05:19:40.247 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Notifications,name=SetIndicator,handler=0x200071c,policy=HANDLE_IMMEDIATELY
2018-02-02 05:19:41.262 [  2] E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=6,error=Couldn't resolve host name
2018-02-02 05:19:41.263 [  2] E AuthDelegate:handleLwaResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.
2018-02-02 05:19:43.636 [  2] E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=6,error=Couldn't resolve host name
2018-02-02 05:19:43.637 [  2] E AuthDelegate:handleLwaResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.
2018-02-02 05:19:50.871 [  1] I HTTP2Transport:setupDownchannelStream:url=https\://avs-alexa-na.amazon.com/v20160207/directives
#############################
#       Connecting...       #
#############################

2018-02-02 05:19:52.249 [  3] I DirectiveSequencer:onDirective:directive={"namespace\:"System"\,name\:"SetEndpoint"\,messageId\:"5c41ebdc-b3fd-4b44-942c-111936988981"\,dialogRequestId\:""}
2018-02-02 05:19:52.249 [  4] I DirectiveRouter:preHandleDirective:messageId=5c41ebdc-b3fd-4b44-942c-111936988981,action=calling
2018-02-02 05:19:52.249 [  5] I DirectiveRouter:handleDirective:messageId=5c41ebdc-b3fd-4b44-942c-111936988981,action=calling
#####################################
#       Client not connected!       #
#####################################

2018-02-02 05:19:52.262 [  5] I HTTP2Transport:setupDownchannelStream:url=https\://avs-alexa-eu.amazon.com/v20160207/directives
########################################
#       Alexa is currently idle!       #
########################################

#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

2018-02-02 05:19:54.031 [  1] I SensoryKeywordDetector:License expires on 28 May 2018 00:00:00 GMT
2018-02-02 05:19:54.031 [  1] I SensoryKeywordDetector:Sensory library license does not expire for at least 60 more days.
                  #    #     #  #####      #####  ######  #    #              
                 # #   #     # #     #    #     # #     # #   #               
                #   #  #     # #          #       #     # #  #                
               #     # #     #  #####      #####  #     # ###                 
               #######  #   #        #          # #     # #  #                
               #     #   # #   #     #    #     # #     # #   #               
               #     #    #     #####      #####  ######  #    #              
                                                                              
       #####                                           #                      
      #     #   ##   #    # #####  #      ######      # #   #####  #####      
      #        #  #  ##  ## #    # #      #          #   #  #    # #    #     
       #####  #    # # ## # #    # #      #####     #     # #    # #    #     
            # ###### #    # #####  #      #         ####### #####  #####      
      #     # #    # #    # #      #      #         #     # #      #          
       #####  #    # #    # #      ###### ######    #     # #      #          

       SDK Version 1.4.0

+----------------------------------------------------------------------------+
|                                  Options:                                  |
| Wake word:                                                                 |
|       Simply say Alexa and begin your query.                               |
| Tap to talk:                                                               |
|       Press 't' and Enter followed by your query (no need for the 'Alexa').|
| Hold to talk:                                                              |
|       Press 'h' followed by Enter to simulate holding a button.            |
|       Then say your query (no need for the 'Alexa').                       |
|       Press 'h' followed by Enter to simulate releasing a button.          |
| Stop an interaction:                                                       |
|       Press 's' and Enter to stop an ongoing interaction.                  |
| Privacy mode (microphone off):                                             |
|       Press 'm' and Enter to turn on and off the microphone.               |
| Playback Controls:                                                         |
|       Press '1' for a 'PLAY' button press.                                 |
|       Press '2' for a 'PAUSE' button press.                                |
|       Press '3' for a 'NEXT' button press.                                 |
|       Press '4' for a 'PREVIOUS' button press.                             |
| Settings:                                                                  |
|       Press 'c' followed by Enter at any time to see the settings screen.  |
| Speaker Control:                                                           |
|       Press 'p' followed by Enter at any time to adjust speaker settings.  |
| Firmware Version:                                                          |
|       Press 'f' followed by Enter at any time to report a different        |
|       firmware version.                                                    |
| Info:                                                                      |
|       Press 'i' followed by Enter at any time to see the help screen.      |
| Quit:                                                                      |
|       Press 'q' followed by Enter at any time to quit the application.     |
+----------------------------------------------------------------------------+

############################
#       Listening...       #
############################

2018-02-02 05:20:22.783 [  6] I DirectiveProcessor:setDialogRequestIdLocked:oldValue=,newValue=107b81f8-e919-4d6f-b1f7-026c854845b9
2018-02-02 05:20:24.779 [  3] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechRecognizer"\,name\:"StopCapture"\,messageId\:"1013f778-8bc6-46c5-bad1-a26aff06c5c4"\,dialogRequestId\:""}
2018-02-02 05:20:24.779 [  4] I DirectiveRouter:preHandleDirective:messageId=1013f778-8bc6-46c5-bad1-a26aff06c5c4,action=calling
2018-02-02 05:20:24.779 [  5] I DirectiveRouter:handleDirective:messageId=1013f778-8bc6-46c5-bad1-a26aff06c5c4,action=calling
###########################
#       Thinking...       #
###########################

2018-02-02 05:20:24.790 [  7] I InProcessAttachmentReader:readFailed:reason=SDS is closed
2018-02-02 05:20:25.221 [  3] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechSynthesizer"\,name\:"Speak"\,messageId\:"996d4d17-c7b6-4046-b035-e301dd7804a0"\,dialogRequestId\:"107b81f8-e919-4d6f-b1f7-026c854845b9"}
2018-02-02 05:20:25.221 [  4] I DirectiveRouter:preHandleDirective:messageId=996d4d17-c7b6-4046-b035-e301dd7804a0,action=calling
2018-02-02 05:20:25.222 [  5] I DirectiveRouter:handleDirective:messageId=996d4d17-c7b6-4046-b035-e301dd7804a0,action=calling
2018-02-02 05:20:25.225 [  8] E MediaPlayer:saveOffsetBeforeTeardown - gst_element_query_position failed
2018-02-02 05:20:25.324 [  8] I InProcessAttachmentReader:readFailed:reason=SDS is closed
###########################
#       Speaking...       #
###########################

########################################
#       Alexa is currently idle!       #
########################################

2018-02-02 05:25:28.948 [  7] I HTTP2Transport:setupDownchannelStream:url=https\://avs-alexa-eu.amazon.com/v20160207/directives
#############################
#       Connecting...       #
#############################

########################################
#       Alexa is currently idle!       #
########################################

############################
#       Listening...       #
############################

2018-02-02 05:25:33.526 [  6] I DirectiveProcessor:setDialogRequestIdLocked:oldValue=107b81f8-e919-4d6f-b1f7-026c854845b9,newValue=23aaa835-252a-4567-809e-972c98444be4
2018-02-02 05:25:35.343 [  3] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechRecognizer"\,name\:"StopCapture"\,messageId\:"843ee9d3-c0e3-495a-abcd-3299b84bd7ae"\,dialogRequestId\:""}
2018-02-02 05:25:35.343 [  4] I DirectiveRouter:preHandleDirective:messageId=843ee9d3-c0e3-495a-abcd-3299b84bd7ae,action=calling
2018-02-02 05:25:35.343 [  5] I DirectiveRouter:handleDirective:messageId=843ee9d3-c0e3-495a-abcd-3299b84bd7ae,action=calling
###########################
#       Thinking...       #
###########################

2018-02-02 05:25:35.354 [  9] I InProcessAttachmentReader:readFailed:reason=SDS is closed
2018-02-02 05:25:35.939 [  3] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechSynthesizer"\,name\:"Speak"\,messageId\:"99e138aa-ae89-40dd-9c60-fffe14e9a648"\,dialogRequestId\:"23aaa835-252a-4567-809e-972c98444be4"}
2018-02-02 05:25:35.940 [  4] I DirectiveRouter:preHandleDirective:messageId=99e138aa-ae89-40dd-9c60-fffe14e9a648,action=calling
2018-02-02 05:25:35.940 [  5] I DirectiveRouter:handleDirective:messageId=99e138aa-ae89-40dd-9c60-fffe14e9a648,action=calling
2018-02-02 05:25:35.942 [  8] E MediaPlayer:saveOffsetBeforeTeardown - gst_element_query_position failed
2018-02-02 05:25:35.962 [  8] I InProcessAttachmentReader:readFailed:reason=SDS is closed
###########################
#       Speaking...       #
###########################

########################################
#       Alexa is currently idle!       #
########################################

**Comment by frozenberg** [comment] 2018-02-02 17:41
Hi @satishc4u,

Thanks for those logs. Could you rebuild as DEBUG? When you run cmake, pass `-DCMAKE_BUILD_TYPE=DEBUG` 

Thanks

**Comment by satishc4u** [comment] 2018-02-05 08:46
Hi fede,
Please find the attached log with DEBUG enabled.

[avs_initial_delay_with_debug.log](https://github.com/alexa/avs-device-sdk/files/1694390/avs_initial_delay_with_debug.log)

Thanks

**Comment by mradulan** [comment] 2018-02-07 22:53
Hi @satishc4u , are you in the North America region or Europe? From the logs it shows that SetEndpoint directive comes and changes the endpoint from avs-alexa-na.amazon.com to avs-alexa-eu.amazon.com

Can you set the endpoint in the config file AlexaClientSDKConfig.json as below:

`    "sampleApp":{
        // To specify if the SampleApp supports display cards.
        "displayCardsSupported":true
        "endpoint": "https://avs-alexa-na.amazon.com"
    }
`
and then run the SampleApp?

**Comment by satishc4u** [comment] 2018-02-08 04:38
Hi , 
I am in india so Europe region right ? 
As per the logs it seems changing server from na to eu happening before giving alexa command so there will be no problem , right ?
I added europe endpoint to the .json, it seems the issue still remains. Please find the attached log file.

[avs_initial_delay_after_endpoint_change.log](https://github.com/alexa/avs-device-sdk/files/1705719/avs_initial_delay_after_endpoint_change.log)

**Comment by mradulan** [comment] 2018-02-08 17:59
do you have a valid  AlexaClientSDKConfig.json file? It looks like some field is wrong. There is a message `AuthDelegate:handleLwaResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty`

**Comment by satishc4u** [comment] 2018-02-09 13:49
I was getting that error when AVS sample starts automatically after rebooting, right now i don't know the exact reason.

Steps to reproduce my initial command delay issue :- 

1). After rebooting got refresh token through my amazon credentials.
2). Then started the AVS Sample App , for the very first command AVS took almost ~5 seconds to give response.
3). For the second command it took only ~2 seconds.

I have attached the log.
[avs.log](https://github.com/alexa/avs-device-sdk/files/1711183/avs.log)

**Comment by satishc4u** [comment] 2018-02-15 08:45
Hi mradulan/Fede,

Do you have any comment on this ?

**Comment by frozenberg** [comment] 2018-02-15 18:11
Hi again,

It looks like the stalling is happening at MediaPlayer, but I can't reproduce it on my pi. This might be an issue with your custom codec. Can I have some more info on that?

Fede

**Comment by scotthea-amazon** [comment] 2018-03-15 19:06
Hi satishc4u,

There has not been any activity on this thread since the last question was posted four weeks ago.  I am closing the issue.  Please feel free to re-open it if it has been closed in error.

Thank you,
-SWH

**Closed by scotthea-amazon** 2018-03-15 19:06 UTC
