### ISSUE TITLE
Pandora music goes to Idle state unexpectedly

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#747] opened 2018-05-30 11:45 UTC
Hi AVS team,

SDK 1.7.1

After about one hour, Pandora music goes to Idle state automatically.
From the log, I saw the last display card message at line#62589.

Actually, this issue also can be found on Prime Music or TuneIn radio test.
Here I attached Pandora log.

[19416.txt](https://github.com/alexa/avs-device-sdk/files/2053712/19416.txt)

**Comment by visayamv** [comment] 2018-05-31 17:50
@zeusshuang , I'm reviewing the log you submitted

**Comment by visayamv** [comment] 2018-05-31 22:39
@zeusshuang , The log shows "Connecting" at the end which means that your device was disconnected from the network. During this time, the device failed to fetch the next audio stream to be played.

**Comment by visayamv** [comment] 2018-06-01 23:19
The player will stop if it can play the music or was not able to receive the appropriate directive. Please reference this doc: https://developer.amazon.com/docs/alexa-voice-service/audioplayer.html

**Comment by BennyAvramson** [comment] 2018-07-19 22:16
Hi,

(Looking on the 2nd logs)
The issue starts with getting exceptions from the cloud:
```
2018-06-27 22:24:49.069 [ 4c] E MessageRequest:onExceptionReceived:exception={"header"\:{"namespace"\:"System"\,"name"\:"Exception"\,"messageId"\:"8cd30a1c-079d-4e98-9de7-df58c7b6b1dc"}\,"payload"\:{"code"\:"INTERNAL_SERVICE_EXCEPTION"\,"description"\:"Request could not be executed due to an internal service error."}}
```
 In order to investigate the reason for the exception, could you reproduce the issue?

Then the SDK is getting into abnormal state:
```
2018-06-28 10:55:11.985 [  a] E ContextManager:updateStatesLoopFailed case#473:waiting on=PlaybackState,nameSpace=AudioPlayer
2018-06-28 10:55:11.985 [  a] E ContextManager:updateStatesLoopFailed:reason=stateProviderTimedOut
2018-06-28 10:55:11.986 [  a] E SpotifyESDKAdapter:contextRetrievalFailed:reason=contextRequestErrorOccurred,error=STATE_PROVIDER_TIMEDOUT
```
which is a bug (See: #727) we'll fix in the next release.


Thanks,
Benny

**Comment by zeusshuang** [comment] 2018-07-19 23:54
Hi @BennyAvramson ,

In our site, I still cannot find a way to reproduce this case by steps.
By users reports, it looks like happens during playing music and seems not only happen on Pandora, also a user reported on iHeartRadio and TuneIn.
And by users' feedback, the symptom ever happen in 15 minutes, but could not reproduce again after a restart.

Thanks,

**Comment by celinval** [comment] 2018-07-24 00:49
As Benny pointed out, this is likely to have the same root cause as #727.

I'm going to close this issue now, but please feel free to reopen it if you find any new information related to this problem.

Thanks

**Closed by celinval** 2018-07-24 00:49 UTC
Labels: bug

**Comment by zeusshuang** [comment] 2018-07-26 15:00
Hi @celinval ,

Just got the same case from user site, and it's the same symptom, but this user playing TuneIn radio for two hours.
