### ISSUE TITLE
[Auto SDK]: Alexa responds "Audible is not supported in this device"

### ISSUE THREAD

**Issue by DeepikaBalaga** [alexa/avs-device-sdk#1793] opened 2020-09-13 13:48 UTC
## Briefly summarize your issue:
Alexa responds "Audible is not supported in this device" when asked to read an Audible book

## What is the expected behavior?
Alexa starts to read the book.

"Now Playing" appears in the Amazon Alexa app down.
## What behavior are you observing?
"Audible is not supported on this device" is the message given by Alexa

## Provide the steps to reproduce the issue, if applicable:
[Precondition]
DUT log in an Alexa  account with a audible book available to read in it. An account that has an Audible book "The sandman" has been signed in.

1) On DUT, set Alexa language as english
2) Request to read a known book title "The sandman" from Audible.
3) Read The "sandman"

## Tell us about your environment:
SW:  app-local-debug.apk, Installed on Android Phone

### What version of the AVS Device SDK are you using?
AUTO SDK v2.3

### Tell us what hardware you're using:
- [ ] Other -App installed on Android Phone

### Tell us about your OS (Type & version):
- [ ] Other -App installed on Android Phone

**Comment by scotthea-amazon** [comment] 2020-09-14 17:48
Hello @DeepikaBalaga,

Please use this link for assistance with the Auto SDK: https://github.com/alexa/alexa-auto-sdk/blob/2.3/NEED_HELP.md

Best regards,
-SWH

**Comment by scotthea-amazon** [comment] 2020-09-15 17:27
Hello @DeepikaBalaga,

Closing as this is an Auto SDK issue. Of course, if it the root cause is found to be in the AVS Device SDK, please feel free to create a new issue with information to help is reproduce and diagnose the issue.

Best regards,
-SWH

**Closed by scotthea-amazon** 2020-09-15 17:27 UTC
