### ISSUE TITLE
"VRT Radio 1" keeps looping radio fragments

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1737] opened 2020-06-19 12:58 UTC
Hi AVS team,

There is a US user reported that "VRT Radio 1" will keep looping radio fragments after playing 5 minutes.
User just user voice command :  play VRT Radio 1 , to starts the radio program
I cannot reproduce this case in my site, but user mentioned he can see the same issue everyday.
Is it a known issue ?
[VRT_Radio_1.log](https://github.com/alexa/avs-device-sdk/files/4804700/VRT_Radio_1.log)

SDK version 1.12.1
ARM based linux system.

I attached a log here for reference.

**Comment by scotthea-amazon** [comment] 2020-06-19 21:33
Hi @zeusshuang,

So far I  am also unable to reproduce this with 1.12.1.  Is that log from the customer?  It spans over a month of activity, with many AudioPlayer Play directives, so it is not clear where I should focus.  Looking closer the logs for the later ones I don't see any evidence of directives that would cause the audio to restart after 5 minutes.  Unfortunately, the logs also do not include enough detail to see if the MediaPlayer is looping over the same buffer.

I expect you will need to get more detailed logs from the customer device to diagnose this problem.

Best regards,
-SWH

**Comment by zeusshuang** [comment] 2020-06-20 09:38
Hi SWH,
Thanks for the comment, I will try to reach the user and try to have a debug mode AVS to get enough log.

**Comment by scotthea-amazon** [comment] 2020-07-30 01:23
Hello @zeusshuang ,

It has been several weeks since this issue was updated, so I am closing it.  If you get additional information, please feel to create a new issue (and refer to this one) to continue the investigation.

Best regards,
-SWH

**Closed by scotthea-amazon** 2020-07-30 01:23 UTC
Labels: Awaiting more information
