### ISSUE TITLE
HTTP2Stream request handling appears to cut off exception messages

### ISSUE THREAD

**Issue by jshslt** [alexa/avs-device-sdk#67] opened 2017-08-01 13:40 UTC
Hi,
We noticed that when we get a `MessageRequest::onExceptionReceived` callback, the exception message tends to look cut off. since this is often (always?) JSON, it leads to improperly formatted content.

It looks like this is due to how `HTTP2Stream::m_exceptionBeingProcessed` is used; as soon as it's non-zero length, `HTTP2Stream::notifyRequestObserver` assumes the message is complete and sends it to the request callback.

**Comment by kclchan** [comment] 2017-10-03 16:26
The issue is fixed in v1.1.0.  Thanks!

**Closed by kclchan** 2017-10-03 16:26 UTC
