### ISSUE TITLE
Bluetooth automatically plays music when a message comes from the phone

### ISSUE THREAD

**Issue by Hzd95** [alexa/avs-device-sdk#1417] opened 2019-07-05 07:50 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

First：“Alexa paire my phone”，then waiting for Bluetooth connection successful
Second：Play music with the App on your phone
Third：Stop the playing
Then，when some notification comes on my phone，the music autoplay.
## What is the expected behavior?

The notification has sound but music don't play.
## What behavior are you observing?

Music automatically plays when the phone is notified
## Provide the steps to reproduce the issue, if applicable:

First：“Alexa paire my phone”，then waiting for Bluetooth connection successful
Second：Play music with the App on your phone
Third：Stop the playing
Then，when some notification comes on my phone，the music autoplay.
### What version of the AVS Device SDK are you using?
     1.13 <x.y.z>

### Tell us what hardware you're using:
- [* ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [* ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment] 2019-07-05 17:41
Hi @Hzd95, thanks for the detailed reproduction steps.  We have identified the cause and will fix this issue in a future release of the SDK.  Thanks again!

**Comment by Hzd95** [comment] 2019-07-06 02:32
> Hi @Hzd95, thanks for the detailed reproduction steps. We have identified the cause and will fix this issue in a future release of the SDK. Thanks again!

Hi @kclchan Thanks for your attention

**Comment by Hzd95** [comment] 2019-07-06 08:12
> > Hi @Hzd95, thanks for the detailed reproduction steps. We have identified the cause and will fix this issue in a future release of the SDK. Thanks again!
> 
> Hi @kclchan Thanks for your attention

could you tell me what caused it

**Comment by Hzd95** [comment] 2019-07-11 02:34
Hi @kclchan  I tried bluetooth with the new SDK，but the issue is still exist. I used the bluetooth analyzer to grab the airbag and found that when the message came, the phone sent AVDTP start commond, which I think is the key to the problem.I hope to get your help to solve this problem.

**Comment by mvelegon-amzn** [comment] 2019-07-11 06:41
Hi @Hzd95 could you please attach logs when this happens. Also, just to confirm you are using the 1.14 version of the SDK correct?

**Comment by Hzd95** [comment] 2019-07-11 07:26
Hi @mvelegon-amzn  sorry,I don't have a complete new SDK .I just finished the bluetooth modification.I will replace all the SDKS before testing，and then I will reply to your results. Thanks for your help.

**Comment by irfankhanharman** [comment] 2019-07-18 12:19
@kclchan We are also facing the same issue on 1.12.1 is there any patch available for the same?
Appreciate your help.

**Comment by womw** [comment] 2019-07-23 00:21
@irfankhanharman we don't intend on releasing a patch for previous versions. Please update to version 1.14.0 which contains the fix for this issue.

**Comment by kclchan** [comment] 2019-08-22 22:46
I am closing this issue due to inactivity. Please feel free to re-open it if it has been closed in error.

**Closed by kclchan** 2019-08-22 22:46 UTC
