### ISSUE TITLE
Failed to create SampleApplication!

### ISSUE THREAD

**Issue by udop1** [alexa/avs-device-sdk#1413] opened 2019-07-01 15:22 UTC
## Briefly summarise your issue:
Starting the SampleApp and never making it to the authorisation check repeat. Instead errors, which look like ALSA audio ones, appear.

## What is the expected behaviour?
No errors should occur and the terminal should keep checking authorisation until I have successfully done so.

## What behaviour are you observing?
```
pi@raspberrypi:~/sdk-folder/sdk-build $ ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json ../third-party/alexa-rpi/models
2019-07-01 14:41:18.324 [  1] I sdkVersion: 1.13.0
configFile ./Integration/AlexaClientSDKConfig.json
#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 923
###################################
#       DoNotDisturb is OFF       #
###################################

Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 923
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.front.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 923
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2043
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2714
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2838
2019-07-01 14:41:19.451 [  1] C PortAudioMicrophoneWrapper:Failed to open PortAudio default stream:errorCode=-9997
2019-07-01 14:41:19.451 [  1] C PortAudioMicrophoneWrapper:Failed to initialize PortAudioMicrophoneWrapper
2019-07-01 14:41:19.452 [  1] C SampleApplication:Failed to create PortAudioMicrophoneWrapper!
2019-07-01 14:41:19.554 [  1] C SampleApplication:Failed to initialize SampleApplication
##################################
#       NOT YET AUTHORIZED       #
##################################

################################################################################################
#       To authorize, browse to: 'https://amazon.com/us/code' and enter the code: JYMSAQ       #
################################################################################################

Failed to create to SampleApplication!
```

## Provide the steps to reproduce the issue, if applicable:
Using this guide at the respectively linked location: https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide#run-and-authorize

Running this in the console: `./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json ../third-party/alexa-rpi/models`

### What version of the AVS Device SDK are you using?
      1.13.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment] 2019-07-01 19:24
Hello udop1,

This sounds like a duplicate of the [issue 1359](https://github.com/alexa/avs-device-sdk/issues/1359).  

It is not clear yet what exactly is causing the issue, but some folks have had success resolving this use by installing older versions of Raspbian.

Best regards,
-SWH

**Comment by udop1** [comment] 2019-07-01 19:27
Alright, I'll attempt using an older version of Raspbian. Ill reply with any updates, or if it still doesn't work afterwards.

Thanks for the suggestion.

**Comment by metalivedev** [comment] 2019-07-03 00:32
I've had success building on buster with the following changes:

Update some versions for buster in `pi.sh`:
```
install_dependencies() {
    sudo apt-get -y install git gcc cmake build-essential libsqlite3-dev libcurl4-openssl-dev \
      libssl1.1 libfaad-dev libsoup2.4-dev libgcrypt20 libgstreamer-plugins-bad1.0 \
      gstreamer1.0-plugins-good libasound2 sox gedit vim python3-pip
}
```

and in `avs-device-sdk/SampleApp/src/CMakelists.txt` add -latomic:
```
target_link_libraries(SampleApp
    DefaultClient
    CapabilitiesDelegate
    CBLAuthDelegate
    SQLiteStorage
    ESP
    EqualizerImplementations
    "${PORTAUDIO_LIB_PATH}"
    -latomic
)
```

I don't think I'll do a pull request with these changes because I haven't got time to do a completely clean install to test, so I encourage someone else to try it out and if it works, make the PR.

**Comment by Vaishnavikumara** [comment] 2019-07-04 08:42
@metalivedev I tried doing what you said , but no luck . I am still facing the error . Please help .
dio default stream:errorCode=-9997
2019-07-04 08:38:23.061 [  1] C PortAudioMicrophoneWrapper:Failed to initialize                                                                                                              PortAudioMicrophoneWrapper
2019-07-04 08:38:23.061 [  6] 9 LibCurlHttpContentFetcher:transferThread:numTran                                                                                                             sfersLeft=1
2019-07-04 08:38:23.063 [  1] C SampleApplication:Failed to create PortAudioMicr                                                                                                             ophoneWrapper!
2019-07-04 08:38:23.063 [  1] 5 DefaultClient:DirectiveSequencerShutdown
2019-07-04 08:38:23.063 [  1] 9 DirectiveSequencer:doShutdown
2019-07-04 08:38:23.064 [  1] 9 DirectiveProcessor:queueAllDirectivesForCancella                                                                                                             tionLocked

**Comment by Vaishnavikumara** [comment] 2019-07-04 08:48
@scotthea-amazon 
What about buster ? The sample app does not work on buster is it ?

**Comment by metalivedev** [comment] 2019-07-04 17:14
the official stable Debian version (where [Raspbian comes from](https://en.wikipedia.org/wiki/Raspbian)) is still [_stretch_](https://wiki.debian.org/DebianStable). I don't know why Raspbian is pushing people to _buster_ when it is still in [test](https://wiki.debian.org/DebianTesting).

You can still get _stretch_ from raspberrypi.org:
http://downloads.raspberrypi.org/raspbian/images/raspbian-2019-04-09/

**Comment by kclchan** [comment] 2019-07-04 20:39
Please note that the official avs-device-sdk supported version of Raspbian is Stretch.

That said, the error log seems to point to a problem with PortAudio initialization.
```
2019-07-01 14:41:19.451 [  1] C PortAudioMicrophoneWrapper:Failed to open PortAudio default stream:errorCode=-9997
```

I would suggest making sure you have an usb microphone connected to your pie, listing the recording device on your system with `arecord -l`, and making sure the `~/.asoundrc` file is configured according to [this](https://alsa-project.org/wiki/Asoundrc).

If you are running the SampleApp in sudo, please make sure to modify the .asoundrc file in `/root/.asoundrc`.  You should be able to access this by using `sudo su -`.

Hope this helps.

**Comment by Vaishnavikumara** [comment] 2019-07-05 02:30
@kclchan , I have done what you said . And the asoundrc file(in the home directory ) looks as follows 

pcm.!default {
  type hw
   playback.pcm {
     type hw
     slave.pcm "hw:0,0"
     format S16_LE
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}


pcm.!default {
	type hw
	card 1
}

ctl.!default {
	type hw
	card 1
}

Also the asoundrc file in the root directory is as follows :
pcm.!default {
    type asym
     playback.pcm {
       type plug
       slave.pcm "hw:0,0"
     }
     capture.pcm {
       type plug
       slave.pcm "hw:1,0"
     }
  }


I could not find where the problem lies. Is it because of the buster version.

**Comment by kclchan** [comment] 2019-07-05 20:36
Hi @Vaishnavikumara, could you also do `arecord -l` to list out all the recording devices on your pi?

**Comment by khassel** [comment] 2019-07-10 21:20
Had this problem after upgrading my rpi to the latest kernel. This seems to be a problem with portaudio. Setting environment variable `PA_ALSA_PLUGHW=1` solved this for my setup.

**Comment by Vaishnavikumara** [comment] 2019-07-11 03:30
@kclchan  , I have done that and it is listing out the devices connected .

**Comment by Vaishnavikumara** [comment] 2019-07-11 03:31
@khassel  , can you please tell me where can I access that environment variable

**Comment by khassel** [comment] 2019-07-11 18:30
If you are starting the App with the script `startsample.sh` you have to edit this file and replace 

````
./SampleApp "$OUTPUT_CONFIG_FILE" "$THIRD_PARTY_PATH/alexa-rpi/models" DEBUG9
````

with

````
env PA_ALSA_PLUGHW=1 ./SampleApp "$OUTPUT_CONFIG_FILE" "$THIRD_PARTY_PATH/alexa-rpi/models" DEBUG9
````
But I don't use this setup, so this is untested ...

**Comment by udop1** [comment] 2019-07-11 20:07
@khassel  After vigorous testing, your script worked!
```
env PA_ALSA_PLUGHW=1 ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json /home/pi/sdk-folder/third-party/alexa-rpi/models
``
It now successfully checks for authorization and no error for 'Failed to create SampleApplication!'
It successfully authorizes and Alexa works completely.
Thank you so much for your help.
@Vaishnavikumara May I suggest you try this as well. It may work.

**Comment by Vaishnavikumara** [comment] 2019-07-12 04:46
@udop1 I will try this and let you know , Thanks .

**Comment by Vaishnavikumara** [comment] 2019-07-12 04:55
###################################################################
#       UNRECOVERABLE CAPABILITIES API ERROR: UNKNOWN_ERROR       #
#       Entering limited interaction mode.                        #
###################################################################


It is getting authorized but I am facing the above error . Please help @udop1

**Comment by mvelegon-amzn** [comment] 2019-07-12 05:24
@Vaishnavikumara could you post your full DEBUG9 logs here? It will help us debug the issue further.

**Comment by Vaishnavikumara** [comment] 2019-07-15 07:25
@udop1 @mvelegon-amzn  Now it is working fine. I just started doing everything from scratch . Thanks for the help . 
Note : I tried it on Stretch not on buster .

**Closed** 2019-07-15 16:35 UTC

**Comment by sagnikbiswas2004** [comment] 2020-07-06 17:33
i am facing this issue ----

2020-07-06 17:19:51.995 [  1] 9 SettingEventSender:cancel
2020-07-06 17:19:51.996 [  1] 9 SettingEventSender:cancel
2020-07-06 17:19:51.996 [  1] 9 SettingEventSender:cancel
2020-07-06 17:19:51.996 [  1] 9 SettingEventSender:cancel
2020-07-06 17:19:51.997 [  1] 9 SettingEventSender:cancel
2020-07-06 17:19:51.997 [  1] 9 SettingEventSender:cancel
2020-07-06 17:19:51.998 [  1] 5 SQLiteDeviceSettingStorage:close
2020-07-06 17:19:51.998 [  1] 9 SettingEventSender:cancel
2020-07-06 17:19:51.998 [  1] 5 InternetConnectionMonitor:stopMonitoring
2020-07-06 17:19:52.005 [  1] 5 SQLiteCBLAuthDelegateStorage:~SQLiteCBLAuthDelegateStorage
2020-07-06 17:19:52.005 [  1] 5 SQLiteCBLAuthDelegateStorage:close
Failed to create SampleApplication!


can any one help me to solve this?****
