### ISSUE TITLE
No template directive send when toggle tumbs up 

### ISSUE THREAD

**Issue by elfdie00475** [alexa/avs-device-sdk#1087] opened 2018-11-22 04:00 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Hi everyone,

This problem is the same as #1072
I implemented the "now playing" card, and I clicked the thumbs up button on Alexa APP
But I didn't receive directive event. 

Could help me check this issue?

Here is my log
[log.TXT](https://github.com/alexa/avs-device-sdk/files/2606526/log.TXT)

## What is the expected behavior?

When I clicked the thumbs up on Alexa APP , SampleApp would receive the directive event includes the string "{"selected":true,"name":"THUMBS_UP","enabled":true,"type":"TOGGLE"}"

## What behavior are you observing?

SampleApp didn't receive the directive event.

## Provide the steps to reproduce the issue, if applicable:

1. Open Alexa App, and play "The Weekend" station on iHeartRadio
2. Click the "thumbs up" button
3. Check the SampleApp have get the directive event

![2018-11-22 11-38-01](https://user-images.githubusercontent.com/43197587/48880933-99801280-ee4d-11e8-9690-fbcde83f2f24.png)
### What version of the AVS Device SDK are you using?
      <1.9.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: arm-linux embedded system

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mavamazon** [comment] 2018-11-27 01:12
Hi!
It looks like an issue and we are going to investigate it. We will update this issue once we have any news.
Thank you for reporting it!

**Comment by kclchan** [comment] 2019-07-05 18:28
This issue is fixed on the cloud side.  Please re-open this issue if it's still reproducible.  Thanks!

**Closed by kclchan** 2019-07-05 18:28 UTC
