### ISSUE TITLE
AVS did not respond after receiving any questions when the radio was playing.

### ISSUE THREAD

**Issue by CarlosHua** [alexa/avs-device-sdk#402] opened 2017-12-20 09:05 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## What version of the AVS Device SDK are you using?
      <1.3>
      
## Briefly summarize your issue:

AVS did not respond after receiving any questions when the radio was playing.
## What is the expected behavior?

Music should be paused and response the "what's time is it" request, then back to work on streaming the music.

## What behavior are you observing?

Now AVS playing the streaming now, status as idle.
-- The status be changes as follows,
     ########################################
     #       Alexa is currently idle!       #
     ########################################

"Alexa, What's time is it ?"
      ############################
      #       Listening...       #
      ############################

      ############################
      #      Thinking...       #
      ############################
 No any audio response for the request, then the radio starting back to work now. 
 AVS need to response the question in this time but it didn't.
     ###########################
     #       Speaking...       #
     ###########################

    ########################################
    #       Alexa is currently idle!       #
    ########################################
## Provide the steps to reproduce the issue, if applicable:

1. "Alexa, Play happy on iHeartRadio!"
-- Now AVS starting streaming the music ..
2. "Alexa, What's time is it ?"
-- Music should be paused and response the "what's time is it" request, then back to work on streaming the music.

### Tell us what hardware you're using:
- [X] Other - tell us more:
Cross compile on embedded

### Tell us about your OS (Type & version):
- [X] Linux

We have try AVS based on v1.0.1/v1.2.1/v1.3 versions, but  all have the same issues, please help to check it. Thanks.

Log provide on here. Thanks.
[avs-no-response.log](https://github.com/alexa/avs-device-sdk/files/1574851/avs-no-response.log)

**Comment by kjkh** [comment] 2017-12-21 00:11
Hi @CarlosHua,

We're not able to reproduce the problem, but the symptoms look similar to another issue we are tracking. I looked at server logs and AVS does correctly send the Speak directive. Your logs also indicate that the SpeechSynthesizer correctly receives and buffers the data, but before it gets a chance to play, receives and end of stream message from the pipeline and stops. Is this reproducible 100% of the time? Can you also try two things independently:

1. Set sync = TRUE on MediaPlayer.cpp line 571:
g_object_set(m_pipeline.audioSink, "sync", FALSE, NULL); =>
g_object_set(m_pipeline.audioSink, "sync", TRUE, NULL);

2. Increase SLEEP_AFTER_END_OF_AUDIO in MediaPlayer.cpp line 81.

**Comment by CarlosHua** [comment] 2017-12-21 04:11
Hi kjkh,

Thanks for your reply.
Yep, this issue could 100% reproducible on all release version(v1.1.0/v1.2.1/v1.3).
I have follow your recommend make necessary changes and test independently. but it still don't works.

My changes as follows, 
1.   g_object_set(m_pipeline.audioSink, "sync", TRUE, NULL);
2.  SLEEP_AFTER_END_OF_AUDIO{300} => SLEEP_AFTER_END_OF_AUDIO{1000}. 
(even try increase value to 2000, still not works.)

I'm not sure what's the problems might cause this issue, have any recommends on it ? Thanks.

**Comment by kjkh** [comment] 2017-12-22 23:52
Hi @CarlosHua, 

Another thought, which version of GStreamer are you using?

**Comment by CarlosHua** [comment] 2017-12-23 10:32
Hi @kjkh,

We using the related packages as follows, 
 glib-2.50.3
 glib-networking-2.54.1
 gstreamer-1.12.2
 gst-plugins-base-1.12.2
 gst-libav-1.12.2
 gst-plugins-good-1.12.2
 gst-plugins-ugly-1.12.2
 gst-plugins-bad-1.12.2

**Comment by CarlosHua** [comment] 2017-12-26 12:48
Hi @kjkh,

Continue to check the log, is it caused by follows ? 
2017-12-20 09:01:31.306 [  2] I InProcessAttachmentReader:readFailed:reason=SDS is closed\

Why AttachmentReader got readFailed at this moment ?   Thanks

**Comment by mradulan** [comment] 2017-12-28 00:12
@CarlosHua , we are looking into the issue. Thanks

**Comment by kclchan** [comment] 2018-01-12 17:33
Closing issue.

**Closed by kclchan** 2018-01-12 17:33 UTC
