### ISSUE TITLE
Kindle book Rewind/back , Skip/fast forward test fail

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#828] opened 2018-07-04 10:02 UTC
Hi AVS team,

Its SDK 1.8 on ARM based OpenWRT Linux platform.

We tried the AVS functional test 2.24/2.25 for Kindle book tests ;  Rewind / Back ,  Skip / Fast Forward,
It will say :  Nothing is currently playing.

For these 4 actions, all return the same TTS. I checked the history, the commands are correct.
Is it SDK issue or server site issue ?

Thanks,

**Comment by kjkh** [comment] 2018-07-05 19:32
Hi @zeusshuang,

I tried those commands and the SDK acted correctly according to those commands. Can you retry to see if they are reproducible? If so, can you attach the logs?

**Comment by zeusshuang** [comment] 2018-07-09 02:29
Hi @kjkh 

attached is the log. I ask Alexa to play my kindle book, and ask to rewind. 
then I asked to skip, the result are all the same.

Video for this case, only show the "rewind" case (also in the log)
https://www.dropbox.com/s/uxx99xkb9926fbf/VID_20180709_100224.zip?dl=0

[1.log](https://github.com/alexa/avs-device-sdk/files/2174416/1.log)

**Comment by celinval** [comment] 2018-07-26 22:55
Hi @zeusshuang, 

I was wondering if that's always the behavior for rewinding a kindle book. Does the same issue happen with other content providers?

Thanks,

**Comment by celinval** [comment] 2018-07-26 22:55
Also, do you mind providing a more recent log?

**Comment by zeusshuang** [comment] 2018-07-27 00:09
Hi @celinval ,

attached is the log for rewind today. It still say "Nothing is currently playing".
I tried it with "audible book", it seems no such issue.


[kindle.log](https://github.com/alexa/avs-device-sdk/files/2233958/kindle.log)

**Comment by subjectxbj** [comment] 2018-08-23 14:37
Today I found this issue with 1.8.1. When I play audible book, I ask "alexa, skip". It just reply "Nothing is currently playing". I did not found this issue with 1.7.1 or 1.6.

**Comment by zeusshuang** [comment] 2018-12-28 10:05
Hi AVS team,
There is an issue while testing audible book or Kindle book.
While playing Audible or Kindle, and reboot DUT, it will start from previous chapter, not stopped chapter.
Is it a known issue in AVS SDK ?

**Comment by zeusshuang** [comment] 2019-01-18 08:15
Hi AVS team,
Could you have comment for this behavior ? Maybe it's known issue or limitation ?

**Comment by kclchan** [comment] 2019-08-22 22:45
Hi @zeusshuang, is this still an issue?  If not, do you mind if we close this?

**Comment by samcoult** [comment] 2019-09-23 21:45
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them. We therefore assume that the user has lost interest or resolved the problem on their own.
Closing issue due to inactivity. Feel free to re-open if you run into issues around this again or there are further comments.

**Closed by samcoult** 2019-09-23 21:45 UTC
