### ISSUE TITLE
MediaDescription.h errors during installation

### ISSUE THREAD

**Issue by F1n3P1Tr1** [alexa/avs-device-sdk#2046] opened 2022-08-12 17:29 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Running into errors during install on Raspberry Pi. Used instructions from https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi-script.html

## What is the expected behavior?
System should install

## What behavior are you observing?
After running this command:

sudo bash setup.sh config.json [-s 1234]

I get the following:
Proceeding with installation
################################################################################
[  0%] Built target acsdkCryptoInterfaces
[  0%] Built target acsdkCodecUtils
[  0%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/DialogUXStateAggregator.cpp.o
[  0%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils/CallbackData.cpp.o
In file included from /home/pi/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/MediaPlayer/SourceConfig.h:23:0,
                 from /home/pi/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/MediaPlayer/MediaPlayerInterface.h:32,
                 from /home/pi/avs-device-sdk/AVSCommon/SDKInterfaces/include/AVSCommon/SDKInterfaces/SpeechSynthesizerObserverInterface.h:22,
                 from /home/pi/avs-device-sdk/AVSCommon/AVS/include/AVSCommon/AVS/DialogUXStateAggregator.h:31,
                 from /home/pi/avs-device-sdk/AVSCommon/AVS/src/DialogUXStateAggregator.cpp:18:
/home/pi/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/MediaPlayer/MediaDescription.h: In function ‘alexaClientSDK::avsCommon::utils::mediaPlayer::MediaDescription alexaClientSDK::avsCommon::utils::mediaPlayer::emptyMediaDescription()’:
/home/pi/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/MediaPlayer/MediaDescription.h:73:34: error: converting to ‘std::unordered_map<std::basic_string<char>, std::basic_string<char> >’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = std::basic_string<char>; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::basic_string<char> > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, std::basic_string<char> > >]’
                             false};
                                  ^
[  0%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils/CurlEasyHandleWrapper.cpp.o
[  0%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils/CurlMultiHandleWrapper.cpp.o
make[3]: *** [AVSCommon/CMakeFiles/AVSCommon.dir/build.make:284: AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/DialogUXStateAggregator.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:9327: AVSCommon/CMakeFiles/AVSCommon.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:16520: SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [Makefile:4192: SampleApp] Error 2

## Provide the steps to reproduce the issue, if applicable:
Follow basic install instructions

### What version of the AVS Device SDK are you using?
      <Using the most recent>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X] Raspbian Buster
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by wryley-amzn** [comment] 2022-08-15 17:35
Hi, this looks like a compiler issue based on the error that comes up. You could try to use the steps suggested here to resolve - https://github.com/tqchen/tinyflow/issues/16 - will consider updating code for all compiler versions.

**Comment by F1n3P1Tr1** [comment] 2022-08-18 17:17
Hi - 
I looked at that link; is there by any chance something a bit simpler? I have basically no experience with this stuff. The link delves heavily into technospeak, so I really have no idea what I should do.

**Comment by wryley-amzn** [comment] 2022-08-18 21:52
No worries - in AVSCommon/Utils/include/AVSCommon/Utils/MediaPlayer/MediaDescription.h, you can try replacing the code in line 76 - constructor's `{}` (empty list) parameter - to `std::unordered_map<std::string, std::string>()`. 
A fix is currently in review as well, will post again here when that has been merged to mainline.

**Comment by kclchan** [comment] 2022-09-09 01:47
I believe the issue is now resolved.  Please open another ticket if it's not the case.

**Closed by kclchan** 2022-09-09 01:47 UTC
Labels: Awaiting Requester Action
