### ISSUE TITLE
Long playback for amazon music - stops after 3 hours

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1430] opened 2019-07-15 13:08 UTC
## Briefly summarize your issue:
We have created a playlist of 110 songs from our registered Alexa prime account through Alexa app.
We are starting playback of this playlist from our device/product on which we have integrated AVS SDK , expecting it to play for more than 8 hours.
But it stops almost within 3 hours of playback time.

## What is the expected behavior?
Alexa should shuffle music for more than 8+ hours.

## What behavior are you observing?
Alexa plays music for maximum 5 hours. Most of the times playback stops after 3 hours only, even though internet connectivity is good.

**Our Initial Analysis of Logs :**
We think that below logs denote the reason of failure :- 

> 2019-07-09 10:15:44.203 [ 19] 3 TemplateRuntime:executeRenderPlayerInfoCallbacks:isClearCard=True
> 
> ################################################################
> #     RenderPlayerInfoCard - Cleared                                          
> ################################################################
> 2019-07-09 10:28:54.967 [  5] 5 InternetConnectionMonitor:updateConnectionStatus:connected=true
> 2019-07-09 10:32:03.529 [  1] E SdsReader:seekFailed:reason=seekBeyondCloseIndex,position=196378624,readerCloseIndex=196373952
> 2019-07-09 10:32:03.529 [  1] 5 DefaultClient:DirectiveSequencerShutdown
> 2019-07-09 10:32:03.529 [  1] 9 DirectiveSequencer:doShutdown
> 
> 2019-07-09 10:32:03.551 [  1] 0 AudioPlayer:onDeregistered
> 2019-07-09 10:32:03.551 [  1] 9 DirectiveRouter:onDeregisteredCalled:handler=0xe5d489e0
> 2019-07-09 10:32:03.552 [  1] 9 DirectiveRouter:onDeregisteredCalled:handler=0xe5d6c180
> 2019-07-09 10:32:03.552 [  1] 9 SpeechSynthesizer:onDeregistered
> 2019-07-09 10:32:03.552 [  1] 5 DefaultClient:SpeakerManagerShutdown
> 2019-07-09 10:32:03.552 [  1] 5 DefaultClient:TemplateRuntimeShutdown
> 2019-07-09 10:32:03.552 [  1] 1 AudioPlayer:removeObserver
> 2019-07-09 10:32:03.552 [  1] 5 DefaultClient:AIPShutdown
> 2019-07-09 10:32:03.553 [  1] 5 DefaultClient:AudioPlayerShutdown
> 
> 2019-07-09 10:33:58.293 [  5] 5 InternetConnectionMonitor:updateConnectionStatus:connected=true

From the AVS SDK logs itself, we could see that internet connectivity is available during the playback for streaming the music. We have also checked the internet connectivity on our device when playback stopped, through radio logs and making data calls. It was in good strength.

**Queries:**
1. Why the music playback stops eventhough internet connectivity is available?
2.  What areas we should look into for the root cause i.e. either AVS SDK perspective or Alexa Cloud dependencies and issues?

## Provide the steps to reproduce the issue, if applicable:
Start Alexa application integrated on our product and say "Alexa play music from amazon"

## Tell us about your environment:
AVS SDK version 1.12.0

### Tell us what hardware you're using:
SDM450

### Tell us about your OS (Type & version):
Android P

**Comment by dipalisb** [comment] 2019-07-15 13:09
[Alexa_AVS_Logs_LongPlayBack_9Jul.txt](https://github.com/alexa/avs-device-sdk/files/3392405/Alexa_AVS_Logs_LongPlayBack_9Jul.txt)

**Comment by dhpp** [comment] 2019-07-17 22:33
Hi @dipalisb - looking at your logfile, it appears that at the end your client detected the "Alexa" keyword in the rendered audio, as we can see the client transition to the "Listening" and "Thinking" mode.  This occurs at 10:18:59.229 - and while afterwards AudioPlayer does return to Foreground status after the client returns to the Idle state, there is no further activity from it.

We will look into this further and update this ticket regarding possible causes.  Thanks.

**Comment by dipalisb** [comment] 2019-07-25 05:33
Hi @dhpp 
Can you please provide update if any, after the above mentioned root cause? We are stuck at this test scenario.

**Comment by womw** [comment] 2019-07-26 23:01
hi @dipalisb we are still investigating this issue

**Comment by dipalisb** [comment] 2019-08-01 06:27
Hi @womw 
Do you need any additional input for this? 
In one of the official documentation of AVS SDK, I read that Alexa goes in Speech recognition mode/ Listening state on the utterance of words similar to wake word like Alex, Election etc.
At our end also, we tried speaking words like **Alasca**, **election** etc, and the Alexa gone into Listening mode.
Do you think the same could have happened in this case?
I have checked the logs according to this, I could trace down the point from where the Speech recognition started, however the reason for this recognition mode is not clear from the logs 

**Note:-** We always start AVS self test at a place where nobody is around, hence wondering if any similar word utterance could have caused the Listening... mode

We need to resolve this issue as soon as possible. Please provide your observations at the earliest.
Thanks.

**Comment by celinval** [comment] 2019-08-07 23:20
Hi @dipalisb, we were not able to reproduce the issue on our side yet.

Is it possible for you to rerun the same test but actively turn off the microphone as soon as you start playing Amazon Music? It would be great if we can determine if the issue is with the barge-in logic or not.

Thanks!

**Comment by celinval** [comment] 2019-08-08 01:24
@dipalisb can you also check 2 things for me whenever you are able to reproduce this issue (with or without turning off the microphone).

1. Are you able to play any other music after playback stopped?
2. Does the SampleApp exit without any problem or do you have to kill the process?

Thanks again!

**Comment by dipalisb** [comment] 2019-08-12 05:13
Hi @celinval 
We will run the test case again with Microphone on Mute and update the results here.

For your queries :
1.  Yes, we can play other music on new command, even after the playback stopped.
2.   I will check this again and update shortly.

Thanks

**Comment by scotthea-amazon** [comment] 2019-08-12 19:53
Hello @dipalisb,

Looking at your logs this appears to be a duplicate of [Issue 1406](https://github.com/alexa/avs-device-sdk/issues/1406).  See the following:

```
2019-07-09 09:47:26.710 [  f] 0 EventBuilder:buildJsonEventString:messageId=9f40f448-9ed8-411e-868a-98b15e41a785,namespace=AudioPlayer,nam
2019-07-09 09:47:26.710 [  f] 5 HTTP2Transport:send
2019-07-09 09:47:26.710 [  f] 5 HTTP2Transport:enqueueRequest:beforeConnected=false
2019-07-09 09:47:26.711 [  f] E HTTP2Transport:enqueueRequestFailed:reason=notInAllowedState,m_state=CONNECTING
```
I will resolve this as a duplicate.  Please feel free to re-open this issue if you think this has been closed in error.

Thank you for helping us diagnose this bug!
-SWH

**Closed by scotthea-amazon** 2019-08-12 19:53 UTC

**Comment by dipalisb** [comment] 2019-10-03 11:08
Hi @scotthea-amazon ,
Can you please update on this issue - is it addressed/fixed under any new release?

**Comment by maidisula** [comment] 2019-11-15 10:09
I have the same problem，sdk version 1.12.0 and I don't see any error message
