### ISSUE TITLE
Alexa AVS install using script does it work?

### ISSUE THREAD

**Issue by 01ZerosOnes01** [alexa/avs-device-sdk#2006] opened 2022-01-06 19:10 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I have tried 2 time to install Alexa AVS using the script method but it never  works. 

## What is the expected behavior?

Successful installation of Alexa AVS using script method

## What behavior are you observing?

Unsuccessful installation of Alexa AVS using script method

## Provide the steps to reproduce the issue, if applicable:

Followed the install steps found here ↓
 https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi-script.html

### What version of the AVS Device SDK are you using?
      <SDK v1.26.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi 4 2GB
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [X] Other - tell us more:
Buster Latest version of Raspberry Pi OS that was sudo apt-get upgrade before the install of Alexa AVS sampleapp

Can anyone tell me if they have been able to install Alexa AVS with Wake Word Sensor successfully since the script version process installation red warning that the script method did not work was removed from the instructions?

T I A

**Comment by 01ZerosOnes01** [comment] 2022-01-09 22:32
I tried to install the AVS SDK sample app using a fresh clean install of Buster OS and about 25 minutes after running the command sudo bash setup.sh config.json [-s 1234] I get this error and the install stops.
[ 19%] Linking CXX executable ContextManagerTest
/usr/bin/ld: ../../AVSCommon/libAVSCommon.so: undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: ../../AVSCommon/libAVSCommon.so: undefined reference to `__atomic_store_8'
/usr/bin/ld: ../../AVSCommon/libAVSCommon.so: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make[2]: *** [ContextManager/test/CMakeFiles/ContextManagerTest.dir/build.make:107: ContextManager/test/ContextManagerTest] Error 1
make[1]: *** [CMakeFiles/Makefile2:14305: ContextManager/test/CMakeFiles/ContextManagerTest.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
pi@raspberrypi:~ $ 


Any help would be appreciated.
Has anyone got this install method to work?

TIA

**Comment by valeri-atamaniouk** [comment] 2022-01-12 19:13
Hello @01ZerosOnes01 

I'm closing this issue as a duplicate of https://github.com/alexa/avs-device-sdk/issues/2007

We will follow up there.

**Closed by valeri-atamaniouk** 2022-01-12 19:13 UTC
Labels: Closed - Duplicate
