### ISSUE TITLE
[Alexa] In Auto SDK Address book module, navigation favorites cannot be added or removed

### ISSUE THREAD

**Issue by DeepikaBalaga** [alexa/avs-device-sdk#1794] opened 2020-09-13 13:51 UTC
## Briefly summarize your issue:
In Auto SDK Address book module, navigation favorites cannot be added or removed

## What is the expected behavior?
[Expected result]
It should add/remove navigation favorite from addressbook

## What behavior are you observing?
[Actual result]
Not able to set/remove navigation favorites for address book

## Provide the steps to reproduce the issue, if applicable:
[Precondition]
DUT log in an Alexa  account

[Test steps]
1) On DUT, set Alexa language as English
2) Request to set destination /remove destination

## Tell us about your environment:
SW:  app-local-debug.apk Installed on Android Mobile

### What version of the AVS Device SDK are you using?
      AUTO SDK v3.2

### Tell us what hardware you're using:
- [ ] Other -Installed on Android Mobile

### Tell us about your OS (Type & version):
- [ ] Other -Installed on Android Mobile

**Comment by scotthea-amazon** [comment] 2020-09-14 17:48
Hello @DeepikaBalaga,

Please use this link for assistance with the Auto SDK: https://github.com/alexa/alexa-auto-sdk/blob/2.3/NEED_HELP.md

Best regards,
-SWH

**Comment by scotthea-amazon** [comment] 2020-09-15 17:26
Hello @DeepikaBalaga,

Closing as this is an Auto SDK issue. Of course, if it the root cause is found to be in the AVS Device SDK, please feel free to create a new issue with information to help is reproduce and diagnose the issue.

Best regards,
-SWH

**Closed by scotthea-amazon** 2020-09-15 17:26 UTC
