### ISSUE TITLE
Miss from cloudfront when download displaycard's image

### ISSUE THREAD

**Issue by DonghuaZheng** [alexa/avs-device-sdk#1065] opened 2018-11-12 03:53 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

     I invoked libcurl API to download displaycard's image, but I can't get image data since audio playback is over, there was a long delay to get image.
     At the same time, I got verbose curl info : 
> GET /premium/image?key=awi/2549/667ad1085cb9d10fca394ae3ac31fdbe1ccc42c0d218286dc2c622c824b0bcdb.jpg HTTP/1.1
Host: img.giq-viz-img-amazon.com
Accept: */*

< HTTP/1.1 200 OK
< Content-Type: image/png
< Content-Length: 106333
< Connection: keep-alive
< Date: Mon, 12 Nov 2018 03:39:20 GMT
< x-amzn-RequestId: 89d2c053-e62c-11e8-a716-57938ba01616
< x-amz-apigw-id: QOtcQHVWoAMFfkA=
< X-Amzn-Trace-Id: Root=1-5be8f5e8-d9011a58907b7c10130bda30;Sampled=0
< X-Cache: Miss from cloudfront
< Via: 1.1 34a84b82ff144b427f99aaae61510d21.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: 8RllezaOTJfCZWRkSw6x6qMiYH3mJLsGIQEPerDCw_VEX08TM2G2oA==
<

## What is the expected behavior?

Image should be downloaded when audio playback start.
## What behavior are you observing?

Image wasn't be downloaded  when audio playback is over, and i got X-Cache: Miss from cloudfront info.
## Provide the steps to reproduce the issue, if applicable:

My network location is HongKong, and my libcurl version is 7.61.0
### What version of the AVS Device SDK are you using?
      <x.y.z>1.9.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ *] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by aumatsui** [comment] 2018-11-14 23:41
Hi DonghuaZheng,

Can you provide the DEBUG9 logs for us to take a look? In order to make sure that the cause of the problem is not related to your application not being able to download the image (the X-Cache comment), you can try to use the same device to download the image using the same URL. Please let us know, so we can assist you further.

**Comment by DonghuaZheng** [comment] 2018-11-16 02:09
@aumatsui here is the log，
[log.txt](https://github.com/alexa/avs-device-sdk/files/2587716/log.txt)

**Comment by DonghuaZheng** [comment] 2018-11-16 02:12
@aumatsui by the way, if I set curl_easy_setopt(curl, CURLOPT_LOW_SPEED_TIME, 3L) and curl_easy_setopt(curl, CURLOPT_LOW_SPEED_LIMIT, 100L) two curl option, it works. But I can't figure out why.

**Comment by kclchan** [comment] 2018-12-10 22:10
@DonghuaZheng, this question is about downloading the image in the application code that's outside the scope of the SDK.  I am not sure if we would be able to provide meaningful help with this.  I am going to close this issue now.  Thanks!

**Closed by kclchan** 2018-12-10 22:10 UTC
