### ISSUE TITLE
Failed to create to Sample Application

### ISSUE THREAD

**Issue by InFamus14** [alexa/avs-device-sdk#1241] opened 2019-02-23 23:28 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
After simply testing Alexa like I do everyday, this dumb error decides to pop out for no reason.

## What is the expected behavior?
Alexa should be idle

## What behavior are you observing?
Failed to create to Sample Application

## Provide the steps to reproduce the issue, if applicable:
sudo bash startsample.sh

### What version of the AVS Device SDK are you using?
      Latest Version

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

[sdWDRWbB.txt](https://github.com/alexa/avs-device-sdk/files/2897377/sdWDRWbB.txt)

**Comment by InFamus14** [comment] 2019-02-23 23:31
Someone please reply asap as this project due on Monday.

**Comment by jcrist678** [comment] 2019-02-24 08:00
Your error is: error=Out of memory. Check if you have processes consuming memory

**Comment by kjkh** [comment] 2019-02-25 21:56
Hi @jcrist678,

This looks like a duplicate of https://github.com/alexa/avs-device-sdk/issues/1240.  I will be closing this and continuing resolution on the other ticket.

**Closed by kjkh** 2019-02-25 21:56 UTC
