### ISSUE TITLE
"Segmentation fault" error when playing Amazon music

### ISSUE THREAD

**Issue by boyce-xx** [alexa/avs-device-sdk#340] opened 2017-11-14 11:32 UTC
Hi,
I got a "segmentation fault" error during the playing of amazon music, then my APP was forced to exit.
[Here](https://gist.github.com/boyce-xx/91d7f91ecb7045d0dd13b29d447848f3) is the test log.

the re-creation procedure as below:
1. say "Alexa, play Taylor Swift", then start playing music.
2. Go to [Now playing](https://pitangui.amazon.com/spa/index.html#player), you will see a Queue playlist, then random click the list item, repeatly within a short time, until you see a warning message in this page: Your Alexa device is not connected.

**Comment by priyagsenthil** [comment] 2017-11-15 06:25
Hi boyce-xx,

We tried the exact steps few times from SampleApp on MAC and I did not see the warning message or the segmentation fault. The app was navigating across the different albums.  Whats the version of the SDK that you are using and whats the platform you are trying this on? Whats the version of gstreamer that you are using? Please provide more details and we can try to see what's different in your environment.

Thanks
Priya

**Comment by kencecka** [comment] 2017-11-29 21:18
Hi @boyce-xx,

I'm not able to reproduce this either.  I'm going to go ahead and close the issue for now - please reopen if you are still seeing this problme and provide more details and steps to reproduce.

Ken

**Closed by kencecka** 2017-11-29 21:18 UTC
