### ISSUE TITLE
SampleApp init failed during connecting to AVS server

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#131] opened 2017-09-02 04:24 UTC
Hi AVS team,
 
I could run AVS C++ SDK under x86 ubuntu and Respberry Pi correctly by following the steps in the Wiki.
Now, I porting the whole requirements to our embeded system (ARM based system with GCC 5.2).

While connecting the AVS in initialization process, it failed. I tried to get packet sniffer and found HTTPS negotiation failed. I could see TLSv1.2 between my device and 54.239.26.114, and saw key exchanged..
I have no idea how to debug it in advanced, could you have any hints ? (see my log below)

I also check the previous issue report, and some tester could run self-test and get log, but how can I do it while I am under a non-Respaberry Pi embeded system?
 
Thanks,
Eric

===============
TZ=UTC ./SampleApp AlexaClientSDKConfig.json DEBUG9
Running app with log level: DEBUG9
2017-09-02 03:05:28.960 [  1] 9 MediaPlayer:createCalled
2017-09-02 03:05:28.987 [  1] 9 MediaPlayer:createCalled
2017-09-02 03:05:28.987 [  1] 9 MediaPlayer:createCalled
2017-09-02 03:05:29.047 [  1] 9 MediaPlayer:setObserverCalled
2017-09-02 03:05:29.048 [  2] 0 MediaPlayer:handleSetObserverCalled
2017-09-02 03:05:29.050 [  1] 9 SpeechSynthesizer:addObserver:observer=0x24993c
2017-09-02 03:05:29.053 [  1] 9 MediaPlayer:setObserverCalled
2017-09-02 03:05:29.053 [  2] 0 MediaPlayer:handleSetObserverCalled
2017-09-02 03:05:29.055 [  1] 9 MediaPlayer:setObserverCalled
2017-09-02 03:05:29.055 [  2] 0 MediaPlayer:handleSetObserverCalled
2017-09-02 03:05:29.068 [  3] I AlertsCapabilityAgent:executeScheduleNextAlertForRendering::no work to do.
2017-09-02 03:05:29.074 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0x24f688,policy=BLOCKING
2017-09-02 03:05:29.076 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=ClearQueue,handler=0x2501d0,policy=NON_BLOCKING
2017-09-02 03:05:29.076 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Stop,handler=0x2501d0,policy=NON_BLOCKING
2017-09-02 03:05:29.076 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Play,handler=0x2501d0,policy=NON_BLOCKING
2017-09-02 03:05:29.077 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0x24ed48,policy=NON_BLOCKING
2017-09-02 03:05:29.077 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=StopCapture,handler=0x24ed48,policy=NON_BLOCKING
2017-09-02 03:05:29.077 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=DeleteAlert,handler=0x250c58,policy=NON_BLOCKING
2017-09-02 03:05:29.077 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=SetAlert,handler=0x250c58,policy=NON_BLOCKING
2017-09-02 03:05:29.079 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=SetEndpoint,handler=0x2863a0,policy=NON_BLOCKING
2017-09-02 03:05:29.080 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=ResetUserInactivity,handler=0x24eb14,policy=NON_BLOCKING
2017-09-02 03:05:30.592 [  4] E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=51,error=SSL peer certificate or SSH remote key was not OK
2017-09-02 03:05:30.593 [  4] E AuthDelegate:handleLwaResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.
2017-09-02 03:05:30.594 [  4] 0 AuthDelegate:calculatedTimeToRetry:delayMs=0
2017-09-02 03:05:31.758 [  4] E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=51,error=SSL peer certificate or SSH remote key was not OK
2017-09-02 03:05:31.758 [  4] E AuthDelegate:handleLwaResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.
2017-09-02 03:05:31.759 [  4] 0 AuthDelegate:calculatedTimeToRetry:delayMs=1213
2017-09-02 03:05:34.168 [  4] E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=51,error=SSL peer certificate or SSH remote key was not OK
2017-09-02 03:05:34.169 [  4] E AuthDelegate:handleLwaResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.
2017-09-02 03:05:34.169 [  4] 0 AuthDelegate:calculatedTimeToRetry:delayMs=1063
2017-09-02 03:05:37.178 [  4] E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=51,error=SSL peer certificate or SSH remote key was not OK
2017-09-02 03:05:37.178 [  4] E AuthDelegate:handleLwaResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.
2017-09-02 03:05:37.178 [  4] 0 AuthDelegate:calculatedTimeToRetry:delayMs=2302
2017-09-02 03:05:40.650 [  4] E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=51,error=SSL peer certificate or SSH remote key was not OK
2017-09-02 03:05:40.650 [  4] E AuthDelegate:handleLwaResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.
2017-09-02 03:05:40.650 [  4] 0 AuthDelegate:calculatedTimeToRetry:delayMs=9184
repeater_routine(2571): OUT SOLID MAGENTA!! NO BACKHAUL INTERFACES EXIST.
Failed to authorize SDK client!
2017-09-02 03:05:49.081 [  1] I DirectiveSequencer:doShutdown
2017-09-02 03:05:49.091 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=System,name=SetEndpoint,handler=0x2863a0,policy=NON_BLOCKING
2017-09-02 03:05:49.096 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=Alerts,name=DeleteAlert,handler=0x250c58,policy=NON_BLOCKING
2017-09-02 03:05:49.097 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=Alerts,name=SetAlert,handler=0x250c58,policy=NON_BLOCKING
2017-09-02 03:05:49.098 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0x24ed48,policy=NON_BLOCKING
2017-09-02 03:05:49.099 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=SpeechRecognizer,name=StopCapture,handler=0x24ed48,policy=NON_BLOCKING
2017-09-02 03:05:49.100 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=System,name=ResetUserInactivity,handler=0x24eb14,policy=NON_BLOCKING
2017-09-02 03:05:49.101 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=SpeechSynthesizer,name=Speak,handler=0x24f688,policy=BLOCKING
2017-09-02 03:05:49.102 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=AudioPlayer,name=ClearQueue,handler=0x2501d0,policy=NON_BLOCKING
2017-09-02 03:05:49.103 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=AudioPlayer,name=Stop,handler=0x2501d0,policy=NON_BLOCKING
2017-09-02 03:05:49.103 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=AudioPlayer,name=Play,handler=0x2501d0,policy=NON_BLOCKING
2017-09-02 03:05:49.104 [  1] I DirectiveRouter:onDeregisteredCalled:handler=0x2863a0
2017-09-02 03:05:49.105 [  1] I DirectiveRouter:onDeregisteredCalled:handler=0x250c58
2017-09-02 03:05:49.105 [  1] I DirectiveRouter:onDeregisteredCalled:handler=0x24ed48
2017-09-02 03:05:49.108 [  1] I DirectiveRouter:onDeregisteredCalled:handler=0x24eb14
2017-09-02 03:05:49.108 [  1] I DirectiveRouter:onDeregisteredCalled:handler=0x24f688
2017-09-02 03:05:49.109 [  1] 9 SpeechSynthesizer:onDeregistered
2017-09-02 03:05:49.109 [  1] I DirectiveRouter:onDeregisteredCalled:handler=0x2501d0
2017-09-02 03:05:49.111 [  1] 9 AudioPlayer:executestop:m_currentActivity=IDLE
2017-09-02 03:05:49.125 [  1] 9 AudioPlayer:executestop:m_currentActivity=IDLE
2017-09-02 03:05:49.125 [  1] 9 MediaPlayer:setObserverCalled
2017-09-02 03:05:49.126 [  2] 0 MediaPlayer:handleSetObserverCalled
2017-09-02 03:05:49.131 [  1] 0 ContextManager:setStateProvider:action=removedStateProvider,namespace=AudioPlayer,name=PlaybackState
2017-09-02 03:05:49.131 [  1] 9 SpeechSynthesizer:doShutdown
2017-09-02 03:05:49.132 [  1] 9 MediaPlayer:setObserverCalled
2017-09-02 03:05:49.133 [  2] 0 MediaPlayer:handleSetObserverCalled
2017-09-02 03:05:49.174 [  1] 9 MediaPlayer:~MediaPlayerCalled
2017-09-02 03:05:49.174 [  1] 9 MediaPlayer:stopCalled
2017-09-02 03:05:49.175 [  2] 0 MediaPlayer:handleStopCalled

(SampleApp:6439): GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
2017-09-02 03:05:49.177 [  2] E MediaPlayer:doStopFailed:reason=gstElementGetStateFailed

(SampleApp:6439): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed
2017-09-02 03:05:49.182 [  1] 9 MediaPlayer:resetPipeline

(SampleApp:6439): GLib-CRITICAL **: Source ID 7235938 was not found when attempting to remove it
2017-09-02 03:05:49.183 [  1] 9 MediaPlayer:~MediaPlayerCalled
2017-09-02 03:05:49.184 [  1] 9 MediaPlayer:stopCalled
2017-09-02 03:05:49.184 [  2] 0 MediaPlayer:handleStopCalled

(SampleApp:6439): GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
2017-09-02 03:05:49.185 [  2] E MediaPlayer:doStopFailed:reason=gstElementGetStateFailed

(SampleApp:6439): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed
2017-09-02 03:05:49.188 [  1] 9 MediaPlayer:resetPipeline

(SampleApp:6439): GLib-CRITICAL **: Source ID 1398223172 was not found when attempting to remove it
Failed to initialize SampleApplication
Failed to create to SampleApplication!

**Comment by sundq** [comment] 2017-09-04 01:57
Hi @zeusshuang

In config file **AlexaClientSDKConfig.json**， there is some audio file configure item like this:
```
    "alertsCapabilityAgent":{
        "timerShortSoundFilePath":"/root/med_system_alerts_melodic_02_short._TTH_.wav",
        "alarmSoundFilePath":"/root/med_system_alerts_melodic_01._TTH_.mp3",
        "databaseFilePath":"/root/db",
        "timerSoundFilePath":"/root/med_system_alerts_melodic_02._TTH_.mp3",
        "alarmShortSoundFilePath":"/root/med_system_alerts_melodic_01_short._TTH_.wav"
    }
```

**Comment by zeusshuang** [comment] 2017-09-04 08:29
Hi @sundq 

Yes, these wav files are in the system as defined in the json file.  
It seems the SSL/TLS connection issue in my case, but I could not understand why it failed.

**Comment by sundq** [comment] 2017-09-05 01:34
It not the SSL problem， you can see `gst_object_unref: assertion 'object != NULL' failed` errror message, I think this is `gstreamer init` failed,  I also got this error when first time run SampleApp， the root cause is **the wav and mp3 file does not exist in disk**

**Comment by scotthea-amazon** [comment] 2017-09-07 18:00
Hi zeusshuang,

Your log does show a connectivity problem (and AuthDelegate retry) several second before the glib errors that are being reported on shutdown.

For debugging the connectivity problem it may be helpful to enable libcurl logging.  That can be done by adding  -DACSDK_EMIT_SENSITIVE_LOGS=ON to your cmake command line.

Note that if you do enable sensitive logs, your logs may include information that you would not want to post publicly (e.g. configuration information used to authorize you client).  So, you should be sure to scrub that kind of information before posting any such logs to this forum.

Thank you,
-SWH

**Comment by BennyAvramson** [comment] 2017-10-17 17:54
Hi @zeusshuang,

As we didn't got your response, I assume the issue has been solved. I'm closing the issue. Please reopen it if you have further questions.

Thanks,
Benny

**Closed by BennyAvramson** 2017-10-17 17:54 UTC

**Comment by vsthirunavukkarasu** [comment] 2017-12-27 12:14
Hi,
I got below error when asking something, 

**############################
#       Listening...       #
############################

2017-12-27 12:11:05.245 [  5] I DirectiveProcessor:setDialogRequestIdLocked:oldValue=,newValue=79c19b9a-a9b4-42d1-ab32-851a0c296673
SampleApp: http2.c:411: on_frame_recv: Assertion `conn->data == data_s' failed.
Aborted**

Note: using yocto based linux platform
and Wake word is working fine.

Any one having any idea about this issue kindly help me to solve this.
Thanks,
Thiru.
